import Schubert.FlagVarieties.Normality.Fulton.Expansion

/-!
# The ideal of `π⁻¹ X_S` is generated by semi-invariants

**`orbitIdeal_le_of_vanishSpan`**: for every set of permutations `S` and every ideal `𝔞` of
`𝒪(GL_n)`: if every element of `I_S^A ∩ A_λ` (every column shape) lies in `𝔞`, then so does every
function vanishing on `π⁻¹ X_S = orbitSet K S`. Geometrically: the ideal sheaf of `X_S` is
generated, chart by chart, by the global sections of the line bundles `𝓛(-λ)` that vanish on `X_S`.

The proof is chart descent along the big cells `G_v` (`isGoodOn_of_chart`): there
`g = L(g) b(g)` with `L(g) = g β(g)` and `b(g) = sign(v) · adj(L(g)) · g = β(g)⁻¹` upper triangular
(`det L(g) = sign v`), and a polynomial vanishing on `orbitSet K S`, evaluated at `L(g)`,
homogenizes into the flag-minor algebra (`exists_homogenize_poly`).

**`orbitIdeal_inter`**: with the intersection identity,
`I(π⁻¹ X_{S ∩ S'}) = I(π⁻¹ X_S) + I(π⁻¹ X_{S'})` in `𝒪(GL_n)` for Bruhat ideals: the
scheme-theoretic intersection of two Schubert unions is reduced.
-/

open Schubert Demazure.FlagModule Demazure.SchubertUnions FinPermutation

namespace FlagVarieties.PointModel

noncomputable section

set_option backward.isDefEq.respectTransparency false

variable {K : Type*} [Field K] {n : ℕ}

theorem chartMinor_ne_zero_of_chartPoly {v : Equiv.Perm (Fin n)} {g : Matrix (Fin n) (Fin n) K}
    (hg : evalAt g (chartPoly K v) ≠ 0) (c : Fin n) : evalAt g (chartMinor K v c) ≠ 0 := by
  rw [chartPoly, map_prod] at hg
  exact Finset.prod_ne_zero_iff.mp hg c (Finset.mem_univ c)

/-- `b(g) = sign(v) · adj(L(g)) · g`; on the big cell `G_v` it is `β(g)⁻¹`. -/
def chartInvBeta (K : Type*) [Field K] (v : Equiv.Perm (Fin n)) (g : Matrix (Fin n) (Fin n) K) :
    Matrix (Fin n) (Fin n) K :=
  (Equiv.Perm.sign v : K) • ((chartMatrix K v g).adjugate * g)

theorem chartMatrix_mul_chartInvBeta {v : Equiv.Perm (Fin n)} {g : Matrix (Fin n) (Fin n) K}
    (hg : ∀ c, evalAt g (chartMinor K v c) ≠ 0) :
    chartMatrix K v g * chartInvBeta K v g = g := by
  rw [chartInvBeta, Matrix.mul_smul, ← Matrix.mul_assoc, Matrix.mul_adjugate, Matrix.smul_mul,
    Matrix.one_mul, smul_smul, det_chartMatrix v g hg, one_smul]

theorem chartInvBeta_eq_inv {v : Equiv.Perm (Fin n)} {g : GL (Fin n) K}
    (hg : ∀ c, evalAt (g : Matrix (Fin n) (Fin n) K) (chartMinor K v c) ≠ 0) :
    chartInvBeta K v g = (chartBeta K v g)⁻¹ := by
  have hgu : IsUnit (g : Matrix (Fin n) (Fin n) K).det :=
    (Matrix.isUnit_iff_isUnit_det _).mp g.isUnit
  have h1 : (g : Matrix (Fin n) (Fin n) K) * (chartBeta K v g * chartInvBeta K v g) =
      (g : Matrix (Fin n) (Fin n) K) * 1 := by
    rw [← Matrix.mul_assoc, show (g : Matrix (Fin n) (Fin n) K) * chartBeta K v g =
      chartMatrix K v g from rfl, chartMatrix_mul_chartInvBeta hg, Matrix.mul_one]
  have h2 : chartBeta K v g * chartInvBeta K v g = 1 := by
    calc chartBeta K v g * chartInvBeta K v g =
        (g : Matrix (Fin n) (Fin n) K)⁻¹ *
          ((g : Matrix (Fin n) (Fin n) K) * (chartBeta K v g * chartInvBeta K v g)) := by
          rw [← Matrix.mul_assoc, Matrix.nonsing_inv_mul _ hgu, Matrix.one_mul]
      _ = 1 := by rw [h1, Matrix.mul_one, Matrix.nonsing_inv_mul _ hgu]
  exact (Matrix.inv_eq_right_inv h2).symm

theorem chartInvBeta_blockTriangular {v : Equiv.Perm (Fin n)} {g : GL (Fin n) K}
    (hg : ∀ c, evalAt (g : Matrix (Fin n) (Fin n) K) (chartMinor K v c) ≠ 0) :
    (chartInvBeta K v g).BlockTriangular fun i : Fin n => i.val := by
  rw [chartInvBeta_eq_inv hg]
  have := Matrix.invertibleOfIsUnitDet _ (chartBeta_det_isUnit v g hg)
  have hup := Matrix.blockTriangular_inv_of_blockTriangular
    (chartBeta_isUpperTriangular v (g : Matrix (Fin n) (Fin n) K))
  intro i j hij
  exact hup hij

theorem evalAt_adjugate_mvPolynomialX (X : Matrix (Fin n) (Fin n) K) (i j : Fin n) :
    evalAt X ((Matrix.mvPolynomialX (Fin n) (Fin n) K).adjugate i j) = X.adjugate i j := by
  have h := (evalAt X).toRingHom.map_adjugate (Matrix.mvPolynomialX (Fin n) (Fin n) K)
  have hX : (evalAt X).toRingHom.mapMatrix (Matrix.mvPolynomialX (Fin n) (Fin n) K) = X := by
    ext a b
    simp [Matrix.mvPolynomialX_apply]
  rw [hX] at h
  exact congrFun (congrFun h i) j

theorem isRegularOn_chartMatrix (v : Equiv.Perm (Fin n)) (P : MatrixEntryPolynomial K n) :
    IsRegularOn (chartPoly K v) fun g => evalAt (chartMatrix K v g) P := by
  obtain ⟨N, a, -, ha⟩ := exists_homogenize_poly v P
  exact ⟨N, a, fun g hg => ha _ (chartMinor_ne_zero_of_chartPoly hg)⟩

theorem chartInvBeta_apply (v : Equiv.Perm (Fin n)) (g : Matrix (Fin n) (Fin n) K) (i j : Fin n) :
    chartInvBeta K v g i j =
      (Equiv.Perm.sign v : K) * ∑ l, (chartMatrix K v g).adjugate i l * g l j := by
  rw [chartInvBeta, Matrix.smul_apply, Matrix.mul_apply, smul_eq_mul]

theorem isRegularOn_entry {D : MatrixEntryPolynomial K n} (i j : Fin n) :
    IsRegularOn D fun g : GL (Fin n) K => (g : Matrix (Fin n) (Fin n) K) i j :=
  (isRegularOn_poly (MvPolynomial.X (i, j))).congr fun _ _ => evalAt_X _ i j

theorem isRegularOn_chartInvBeta (v : Equiv.Perm (Fin n)) (i j : Fin n) :
    IsRegularOn (chartPoly K v) fun g => chartInvBeta K v g i j := by
  have hadj : ∀ a b : Fin n,
      IsRegularOn (chartPoly K v) fun g => (chartMatrix K v g).adjugate a b := fun a b =>
    (isRegularOn_chartMatrix v ((Matrix.mvPolynomialX (Fin n) (Fin n) K).adjugate a b)).congr
      fun g _ => evalAt_adjugate_mvPolynomialX _ a b
  have hsum : IsRegularOn (chartPoly K v) fun g : GL (Fin n) K =>
      ∑ l, (chartMatrix K v g).adjugate i l * (g : Matrix (Fin n) (Fin n) K) l j :=
    IsRegularOn.sum Finset.univ
      (fun l (g : GL (Fin n) K) =>
        (chartMatrix K v g).adjugate i l * (g : Matrix (Fin n) (Fin n) K) l j)
      fun l _ => (hadj i l).mul (isRegularOn_entry l j)
  exact ((isRegularOn_const (Equiv.Perm.sign v : K)).mul hsum).congr fun g _ =>
    (chartInvBeta_apply v _ i j).symm

/-- A polynomial vanishing on `orbitSet K S`, read in the chart `G_v`, is good for every ideal
containing the semi-invariant parts of the ideal of `orbitSet K S`. -/
theorem isGoodOn_chartMatrix_of_vanish (S : Finset (Equiv.Perm (Fin n)))
    (𝔟 : Ideal (MatrixEntryPolynomial K n)) (h𝔟 : ∀ (m : ColumnShape n), ∀ p ∈ vanishSpan K m S,
        p ∈ 𝔟)
    (v : Equiv.Perm (Fin n)) (P : MatrixEntryPolynomial K n)
    (hP : ∀ g ∈ orbitSet K S, evalAt (g : Matrix (Fin n) (Fin n) K) P = 0) :
    IsGoodOn (chartPoly K v) 𝔟 fun g => evalAt (chartMatrix K v g) P := by
  obtain ⟨N, a, ha, hav⟩ := exists_homogenize_poly v P
  refine ⟨N + 1, a * chartPoly K v,
    h𝔟 _ _ ⟨mul_mem_minorSpan ha (chartPoly_mem_minorSpan v), ?_⟩, fun g hg => ?_⟩
  · intro g hg
    by_cases hgv : ∀ c, evalAt (g : Matrix (Fin n) (Fin n) K) (chartMinor K v c) ≠ 0
    · obtain ⟨β, hβdef⟩ : ∃ β : GL (Fin n) K, (β : Matrix (Fin n) (Fin n) K) = chartBeta K v g :=
        ⟨unitOfDet (chartBeta K v g) (chartBeta_det_isUnit v g hgv), coe_unitOfDet _ _⟩
      have hβ : IsBorel β := by
        unfold IsBorel
        rw [hβdef]
        exact chartBeta_isUpperTriangular v (g : Matrix (Fin n) (Fin n) K)
      have hL := hP _ (orbitSet_mul_borel hg hβ)
      rw [Units.val_mul, hβdef] at hL
      have hL' : evalAt (chartMatrix K v g) P = 0 := hL
      rw [map_mul, hav _ hgv, hL', mul_zero, zero_mul]
    · push Not at hgv
      obtain ⟨c, hc⟩ := hgv
      rw [map_mul, chartPoly, map_prod, Finset.prod_eq_zero (Finset.mem_univ c) hc, mul_zero]
  · rw [map_mul, hav _ (chartMinor_ne_zero_of_chartPoly hg), pow_succ]
    ring

/-- **Descent to semi-invariants.** -/
theorem orbitIdeal_le_of_vanishSpan [IsAlgClosed K] (S : Finset (Equiv.Perm (Fin n)))
    (𝔞 : Ideal (GLCoord K n))
    (h𝔞 : ∀ (m : ColumnShape n), ∀ p ∈ vanishSpan K m S,
      algebraMap (MatrixEntryPolynomial K n) (GLCoord K n) p ∈ 𝔞) :
    orbitIdeal K S ≤ 𝔞 := by
  intro t ht
  obtain ⟨r, e, hre⟩ := exists_mul_det_pow t
  have hr : ∀ g ∈ orbitSet K S, evalAt (g : Matrix (Fin n) (Fin n) K) r = 0 :=
    fun g hg => evalAt_eq_zero_of_mul_det_pow hre (ht g hg)
  refine mem_of_mul_det_pow hre (Ideal.map_comap_le (algebraMap_mem_of_isGoodOn
    (fun v => chartPoly K v) exists_chartPoly_ne_zero
    (𝔟 := 𝔞.comap (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n))) fun v => ?_))
  exact isGoodOn_of_chart (fun i : Fin n => i.val) (Z := orbitSet K S)
    (fun g hg p hp => orbitSet_mul_borel hg fun i j hij => hp hij) hr (chartPoly K v) _
    (fun g => chartMatrix K v g) (fun g => chartInvBeta K v g)
    (fun g hg => ⟨(chartMatrix_mul_chartInvBeta (chartMinor_ne_zero_of_chartPoly hg)).symm,
      chartInvBeta_blockTriangular (chartMinor_ne_zero_of_chartPoly hg)⟩)
    (isRegularOn_chartInvBeta v)
    (fun P hP => isGoodOn_chartMatrix_of_vanish S _ (fun m p hp => h𝔞 m p hp) v P hP)

theorem algebraMap_mem_orbitIdeal {S : Finset (Equiv.Perm (Fin n))} {p : MatrixEntryPolynomial K n}
    (hp : ∀ g ∈ orbitSet K S, evalAt (g : Matrix (Fin n) (Fin n) K) p = 0) :
    algebraMap (MatrixEntryPolynomial K n) (GLCoord K n) p ∈ orbitIdeal K S := fun g hg => by
  rw [glEval_algebraMap_eq_evalAt]
  exact hp g hg

theorem orbitIdeal_anti {S S' : Finset (Equiv.Perm (Fin n))} (h : S ⊆ S') :
    orbitIdeal K S' ≤ orbitIdeal K S := fun _ ht g hg => ht g (orbitSet_mono h hg)

/-- **The intersection identity in `𝒪(GL_n)`**: the scheme-theoretic intersection of two Schubert
unions is the
Schubert union of the intersection. -/
theorem orbitIdeal_inter [IsAlgClosed K] (hSMT : StandardMonomialTheory K)
    {S S' : Finset (Equiv.Perm (Fin n))}
    (hS : BruhatLower S) (hS' : BruhatLower S') :
    orbitIdeal K (S ∩ S') = orbitIdeal K S ⊔ orbitIdeal K S' := by
  apply le_antisymm
  · refine orbitIdeal_le_of_vanishSpan _ _ fun m p hp => ?_
    rw [vanishSpan_inter hSMT m hS hS'] at hp
    obtain ⟨a, ha, b, hb, rfl⟩ := Submodule.mem_sup.mp hp
    rw [map_add]
    exact Submodule.add_mem_sup (algebraMap_mem_orbitIdeal ha.2) (algebraMap_mem_orbitIdeal hb.2)
  · exact sup_le (orbitIdeal_anti Finset.inter_subset_left)
      (orbitIdeal_anti Finset.inter_subset_right)

end

end FlagVarieties.PointModel
