import Schubert.FlagVarieties.PointModel.SectionBasis
import Schubert.FlagVarieties.PointModel.Complex.ChainCount

/-!
# Grassmannian conditions in a single height

Fix a height `k` and a row set `R` with `k + 1` elements.

* `galeLE S T`: the Gale order on row sets, in counting form. `v ≤ᴮ w` iff `v{0..k} ≤ w{0..k}` for
  every `k` (`strongBruhat_iff_galeLE`).
* `grassSet k R = {v | v{0..k} ≤ R}`, a Bruhat ideal: the preimage in `Fl_n` of a Schubert variety
  of the Grassmannian. `lowerSet w = ⋂_k grassSet k (w{0..k})` (`lowerSet_eq_inf`).
* `forbiddenIdeal K k R ⊆ K[x_ij]`: generated by the flag minors `Δ_T` of height `k` with `T ≰ R`.
  They vanish on `orbitSet K (grassSet k R)`, and an invertible matrix at which they all vanish
  lies there (`mem_orbitSet_grassSet_iff`). Hence this set is stable under right multiplication by
  the parabolic subgroup `P_k` of matrices that are block-upper-triangular for the blocks
  `{0..k}`, `{k+1..}` (`orbitSet_grassSet_mul`).
* `mem_forbiddenIdeal_of_mem_vanishSpan`: in a single height `k`, every element of `A_{d ϖ_k}`
  vanishing on `orbitSet K (grassSet k R)` lies in the forbidden ideal. Indeed a standard product
  whose columns are all `≤ R` is standard on `grassSet k R` (take the top of its defining chain),
  so by the standard-monomial basis (over a field of characteristic `0`) the kernel is spanned by
  the standard products with a forbidden column.
-/

open Schubert Demazure.FlagModule Demazure.SchubertUnions FinPermutation

namespace FlagVarieties.PointModel

noncomputable section

set_option backward.isDefEq.respectTransparency false

variable {K : Type*} [Field K] {n : ℕ}

/-! ### The Gale order and Grassmannian conditions -/

/-- The Gale order on row sets of the same size, in counting form: `S ≤ T` iff, for every `q`,
`S` has at most as many elements `≥ q` as `T`. -/
def galeLE {k : Fin n} (S T : FlagMinorRowSet k) : Prop :=
  ∀ q : Fin n, (S.val.filter fun x => q ≤ x).card ≤ (T.val.filter fun x => q ≤ x).card

theorem galeLE_refl {k : Fin n} (S : FlagMinorRowSet k) : galeLE S S := fun _ => le_rfl

theorem galeLE.trans {k : Fin n} {S T U : FlagMinorRowSet k} (h₁ : galeLE S T)
    (h₂ : galeLE T U) : galeLE S U := fun q => (h₁ q).trans (h₂ q)

theorem galeLE_of_rows_le {k : Fin n} {S T : FlagMinorRowSet k}
    (h : ∀ i, S.rows i ≤ T.rows i) : galeLE S T :=
  card_filter_le_of_rows_le h

/-- The tableau criterion: `v ≤ᴮ w` iff all prefixes compare in the Gale order. -/
theorem strongBruhat_iff_galeLE {v w : Equiv.Perm (Fin n)} :
    v ≤ᴮ w ↔ ∀ k, galeLE (flagPrefixRows v k) (flagPrefixRows w k) := by
  constructor
  · intro h k q
    rw [← bruhatRank_eq_card_filter, ← bruhatRank_eq_card_filter]
    exact h k q
  · intro h k q
    have := h k q
    rwa [← bruhatRank_eq_card_filter, ← bruhatRank_eq_card_filter] at this

/-- `G(k, R) = {v | v{0..k} ≤ R}`. -/
def grassSet (k : Fin n) (R : FlagMinorRowSet k) : Finset (Equiv.Perm (Fin n)) := by
  classical exact Finset.univ.filter fun v => galeLE (flagPrefixRows v k) R

theorem mem_grassSet {k : Fin n} {R : FlagMinorRowSet k} {v : Equiv.Perm (Fin n)} :
    v ∈ grassSet k R ↔ galeLE (flagPrefixRows v k) R := by
  classical
  simp [grassSet]

theorem bruhatLower_grassSet (k : Fin n) (R : FlagMinorRowSet k) : BruhatLower (grassSet k R) :=
  fun _ hw _ hvw =>
    mem_grassSet.mpr ((strongBruhat_iff_galeLE.mp hvw k).trans (mem_grassSet.mp hw))

theorem lowerSet_subset_grassSet (w : Equiv.Perm (Fin n)) (k : Fin n) :
    lowerSet w ⊆ grassSet k (flagPrefixRows w k) := fun _ hv =>
  mem_grassSet.mpr (strongBruhat_iff_galeLE.mp (mem_lowerSet.mp hv) k)

/-- **`↓w = ⋂_k G(k, w{0..k})`.** -/
theorem lowerSet_eq_inf (w : Equiv.Perm (Fin n)) :
    lowerSet w = Finset.univ.inf fun k => grassSet k (flagPrefixRows w k) := by
  ext v
  simp only [Finset.mem_inf, Finset.mem_univ, true_implies, mem_grassSet, mem_lowerSet]
  exact strongBruhat_iff_galeLE

/-! ### The forbidden flag minors -/

/-- The ideal generated by the flag minors `Δ_T` of height `k` with `T ≰ R`. -/
def forbiddenIdeal (K : Type*) [Field K] (k : Fin n) (R : FlagMinorRowSet k) :
    Ideal (MatrixEntryPolynomial K n) :=
  Ideal.span {p | ∃ T : FlagMinorRowSet k, ¬ galeLE T R ∧ p = rowMinor K k T.rows}

theorem rowMinor_mem_forbiddenIdeal {k : Fin n} {R T : FlagMinorRowSet k} (hT : ¬ galeLE T R) :
    rowMinor K k T.rows ∈ forbiddenIdeal K k R :=
  Ideal.subset_span ⟨T, hT, rfl⟩

/-- The chart minor `D_k = Δ_{v 0, …, v k}` is, up to sign, the sorted flag minor of `v{0..k}`. -/
theorem evalAt_chartMinor_eq (v : Equiv.Perm (Fin n)) (k : Fin n) (g : Matrix (Fin n) (Fin n) K) :
    evalAt g (chartMinor K v k) = (Equiv.Perm.sign (flagPrefixPermutation v k) : K) *
      evalAt g (rowMinor K k (flagPrefixRows v k).rows) := by
  rw [chartMinor, evalAt_rowMinor, evalAt_rowMinor]
  have hsub : g.submatrix (leadRows v k) (prefixIndex k) =
      (g.submatrix (flagPrefixRows v k).rows (prefixIndex k)).submatrix
        (flagPrefixPermutation v k) id := by
    ext a b
    simp only [Matrix.submatrix_apply, leadRows, flagPrefixPermutation_spec, id]
  rw [hsub, Matrix.det_permute]

/-- **The forbidden minors vanish on `π⁻¹ X_{G(k,R)}`.** -/
theorem evalAt_rowMinor_eq_zero_of_mem_orbitSet {k : Fin n} {R T : FlagMinorRowSet k}
    (hT : ¬ galeLE T R) {g : GL (Fin n) K} (hg : g ∈ orbitSet K (grassSet k R)) :
    evalAt (g : Matrix (Fin n) (Fin n) K) (rowMinor K k T.rows) = 0 := by
  refine (forall_mem_orbitSet_iff (rowMinor_mem_minorSpan k T.rows) _).mpr
    (fun v hv u hu => ?_) g hg
  rw [evalAt_unitriangular_mul_rowMinor v k T,
    upperTriangular_minor_zero u hu.1 T.rows (flagPrefixRows v k).rows
      (fun hle => hT ((galeLE_of_rows_le hle).trans (mem_grassSet.mp hv))), mul_zero]

theorem evalAt_eq_zero_of_mem_forbiddenIdeal {k : Fin n} {R : FlagMinorRowSet k}
    {p : MatrixEntryPolynomial K n}
    (hp : p ∈ forbiddenIdeal K k R) {g : GL (Fin n) K} (hg : g ∈ orbitSet K (grassSet k R)) :
    evalAt (g : Matrix (Fin n) (Fin n) K) p = 0 := by
  induction hp using Submodule.span_induction with
  | mem p hp =>
    obtain ⟨T, hT, rfl⟩ := hp
    exact evalAt_rowMinor_eq_zero_of_mem_orbitSet hT hg
  | zero => exact map_zero _
  | add p q _ _ hp hq => rw [map_add, hp, hq, add_zero]
  | smul a p _ hp => rw [smul_eq_mul, map_mul, hp, mul_zero]

/-- **Set-theoretic description**: `g ∈ π⁻¹ X_{G(k,R)}` iff all forbidden minors vanish at `g`. -/
theorem mem_orbitSet_grassSet_iff {k : Fin n} {R : FlagMinorRowSet k} {g : GL (Fin n) K} :
    g ∈ orbitSet K (grassSet k R) ↔ ∀ T : FlagMinorRowSet k, ¬ galeLE T R →
      evalAt (g : Matrix (Fin n) (Fin n) K) (rowMinor K k T.rows) = 0 := by
  refine ⟨fun hg T hT => evalAt_rowMinor_eq_zero_of_mem_orbitSet hT hg, fun h => ?_⟩
  obtain ⟨v, hv⟩ := exists_mem_bruhatCell g
  refine mem_orbitSet.mpr ⟨v, mem_grassSet.mpr ?_, hv⟩
  by_contra hne
  have h1 := evalAt_chartMinor_ne_zero_of_mem_bruhatCell hv k
  rw [evalAt_chartMinor_eq, h _ hne, mul_zero] at h1
  exact h1 rfl

/-! ### Stability under the parabolic subgroup `P_k` -/

/-- The blocks `{0..k}` (`0`) and `{k+1..}` (`1`). -/
def prefixBlock (k : Fin n) (i : Fin n) : ℕ := if i ≤ k then 0 else 1

theorem submatrix_mul_prefixBlock (g p : Matrix (Fin n) (Fin n) K) (k : Fin n)
    (hp : p.BlockTriangular (prefixBlock k)) (s : Fin (k.val + 1) → Fin n) :
    (g * p).submatrix s (prefixIndex k) =
      g.submatrix s (prefixIndex k) * p.submatrix (prefixIndex k) (prefixIndex k) := by
  classical
  ext i j
  simp only [Matrix.submatrix_apply, Matrix.mul_apply]
  have hsub : ∑ l, g (s i) l * p l (prefixIndex k j) =
      ∑ l ∈ Finset.univ.image (prefixIndex k), g (s i) l * p l (prefixIndex k j) := by
    symm
    refine Finset.sum_subset (Finset.subset_univ _) fun l _ hl => ?_
    have hlk : ¬ l ≤ k := by
      intro hle
      exact hl (Finset.mem_image.mpr ⟨⟨l.val, by have : l.val ≤ k.val := hle; omega⟩,
        Finset.mem_univ _, Fin.ext rfl⟩)
    have hjk : prefixIndex k j ≤ k := by
      change (prefixIndex k j).val ≤ k.val
      simp only [prefixIndex]
      omega
    have hlt : prefixBlock k (prefixIndex k j) < prefixBlock k l := by
      simp [prefixBlock, hlk, hjk]
    rw [hp hlt, mul_zero]
  rw [hsub, Finset.sum_image (fun a _ b _ h => prefixIndex_injective k h)]

theorem evalAt_mul_prefixBlock_rowMinor (g p : Matrix (Fin n) (Fin n) K) (k : Fin n)
    (hp : p.BlockTriangular (prefixBlock k)) (s : Fin (k.val + 1) → Fin n) :
    evalAt (g * p) (rowMinor K k s) =
      (p.submatrix (prefixIndex k) (prefixIndex k)).det * evalAt g (rowMinor K k s) := by
  rw [evalAt_rowMinor, evalAt_rowMinor, submatrix_mul_prefixBlock g p k hp, Matrix.det_mul,
      mul_comm]

/-- **`π⁻¹ X_{G(k,R)}` is stable under the right action of `P_k`.** -/
theorem orbitSet_grassSet_mul {k : Fin n} {R : FlagMinorRowSet k} {g : GL (Fin n) K}
    (hg : g ∈ orbitSet K (grassSet k R)) (p : GL (Fin n) K)
    (hp : (p : Matrix (Fin n) (Fin n) K).BlockTriangular (prefixBlock k)) :
    g * p ∈ orbitSet K (grassSet k R) := by
  rw [mem_orbitSet_grassSet_iff] at hg ⊢
  intro T hT
  rw [Units.val_mul, evalAt_mul_prefixBlock_rowMinor _ _ k hp, hg T hT, mul_zero]

/-! ### The standard-monomial basis -/

/-- **Independence of standard products modulo the ideal of `X_S`** (characteristic `0`). -/
theorem eq_zero_of_sum_mem_vanishSpan [CharZero K] {d : ℕ} (h : Fin d → Fin n)
    (S : Finset (Equiv.Perm (Fin n))) (c : {T // T ∈ chainSet h S} → K)
    (hv : ∑ T : {T // T ∈ chainSet h S}, c T • colProd K h T.1 ∈
      vanishSpan K (columnMultiplicity h) S) : c = 0 := by
  have hmem : ∑ T : {T // T ∈ chainSet h S}, c T • colProd K h T.1 ∈ flagSpan K h :=
    Submodule.sum_mem _ fun T _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨T.1, rfl⟩)
  have hcoord := (mem_vanishSpan_iff_coordMap K h S hmem).mp hv
  have hsum : ∑ T : {T // T ∈ chainSet h S}, c T • ratVec K (ratCoords h S T.1) = 0 := by
    rw [← hcoord, map_sum]
    simp only [map_smul, coordMap_colProd]
  funext T
  exact (Fintype.linearIndependent_iff.mp (linearIndependent_ratCoords (K := K) h S)) c hsum T

/-- **The standard products span `A_h`** (characteristic `0`). -/
theorem flagSpan_eq_span_chainSet [CharZero K] {d : ℕ} (h : Fin d → Fin n) :
    flagSpan K h = Submodule.span K
      (Set.range fun T : {T // T ∈ chainSet h Finset.univ} => colProd K h T.1) := by
  have : Infinite K := Infinite.of_injective (Nat.cast : ℕ → K) Nat.cast_injective
  symm
  apply Submodule.eq_of_le_of_finrank_eq
  · exact Submodule.span_le.mpr (by rintro _ ⟨T, rfl⟩; exact Submodule.subset_span ⟨T.1, rfl⟩)
  · have hli : LinearIndependent K
        (fun T : {T // T ∈ chainSet h Finset.univ} => colProd K h T.1) := by
      rw [Fintype.linearIndependent_iff]
      intro c hc T
      exact congrFun (eq_zero_of_sum_mem_vanishSpan h _ c (by rw [hc]; exact Submodule.zero_mem _))
        T
    rw [finrank_span_eq_card hli, Fintype.card_coe]
    have hdim := (standardMonomialTheory_of_charZero K).dim h (bruhatLower_univ (n := n))
    rw [vanishSpan_univ, finrank_bot] at hdim
    omega

theorem columnMultiplicity_const (k : Fin n) (d : ℕ) :
    columnMultiplicity (fun _ : Fin d => k) = d • Pi.single k 1 := by
  funext k'
  rw [columnMultiplicity_apply]
  by_cases hk : k = k'
  · subst hk
    simp
  · simp [hk, Ne.symm hk]

/-- **Single height**: an element of `A_{(N+1) ϖ_k}` vanishing on `π⁻¹ X_{G(k,R)}` is a combination
of products of flag minors with a forbidden factor. -/
theorem mem_forbiddenIdeal_of_mem_vanishSpan [CharZero K] (k : Fin n) (R : FlagMinorRowSet k)
    (N : ℕ) {p : MatrixEntryPolynomial K n}
        (hp : p ∈ vanishSpan K ((N + 1) • Pi.single k 1) (grassSet k R)) :
    p ∈ forbiddenIdeal K k R := by
  classical
  have hcm : columnMultiplicity (fun _ : Fin (N + 1) => k) = (N + 1) • Pi.single k 1 :=
    columnMultiplicity_const k (N + 1)
  have hpF : p ∈ flagSpan K (fun _ : Fin (N + 1) => k) := by
    rw [← minorSpan_columnMultiplicity, hcm]
    exact hp.1
  rw [flagSpan_eq_span_chainSet] at hpF
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun K).mp hpF
  let c' : ((j : Fin (N + 1)) → FlagMinorRowSet k) → K := fun T =>
    if hT : T ∈ chainSet (fun _ : Fin (N + 1) => k) Finset.univ then c ⟨T, hT⟩ else 0
  have hsum : p = ∑ T ∈ chainSet (fun _ : Fin (N + 1) => k) Finset.univ,
      c' T • colProd K (fun _ : Fin (N + 1) => k) T := by
    rw [← hc, ← Finset.sum_coe_sort (chainSet (fun _ : Fin (N + 1) => k) Finset.univ)]
    refine Finset.sum_congr rfl fun T _ => ?_
    simp [c', T.2]
  have hsub : chainSet (fun _ : Fin (N + 1) => k) (grassSet k R) ⊆
      chainSet (fun _ : Fin (N + 1) => k) Finset.univ := fun T hT => by
    obtain ⟨w, -, hw⟩ := mem_chainSet.mp hT
    exact mem_chainSet.mpr ⟨w, Finset.mem_univ w, hw⟩
  -- a standard tuple which is not standard on `G(k,R)` has a forbidden column
  have hbad : ∀ T ∈ chainSet (fun _ : Fin (N + 1) => k) Finset.univ \
      chainSet (fun _ : Fin (N + 1) => k) (grassSet k R),
      colProd K (fun _ : Fin (N + 1) => k) T ∈ forbiddenIdeal K k R := by
    intro T hT
    rw [Finset.mem_sdiff] at hT
    have hj : ∃ j, ¬ galeLE (T j) R := by
      by_contra hall
      push Not at hall
      apply hT.2
      obtain ⟨w, -, v, hmono, hpre, -⟩ := mem_chainSet.mp hT.1
      have hlast := hall (Fin.last N)
      rw [← hpre (Fin.last N)] at hlast
      exact mem_chainSet.mpr ⟨v (Fin.last N), mem_grassSet.mpr hlast, v, hmono, hpre,
        fun j => hmono j (Fin.last N) (Fin.le_last j)⟩
    obtain ⟨j, hj⟩ := hj
    exact Ideal.prod_mem _ (Finset.mem_univ j) (rowMinor_mem_forbiddenIdeal hj)
  have hbadmem : ∑ T ∈ chainSet (fun _ : Fin (N + 1) => k) Finset.univ \
      chainSet (fun _ : Fin (N + 1) => k) (grassSet k R),
      c' T • colProd K (fun _ : Fin (N + 1) => k) T ∈ forbiddenIdeal K k R :=
    Submodule.sum_mem _ fun T hT => Submodule.smul_of_tower_mem _ _ (hbad T hT)
  have hsplit : p = ∑ T ∈ chainSet (fun _ : Fin (N + 1) => k) (grassSet k R),
      c' T • colProd K (fun _ : Fin (N + 1) => k) T +
      ∑ T ∈ chainSet (fun _ : Fin (N + 1) => k) Finset.univ \
        chainSet (fun _ : Fin (N + 1) => k) (grassSet k R),
        c' T • colProd K (fun _ : Fin (N + 1) => k) T := by
    rw [hsum]
    exact (Finset.sum_sdiff hsub).symm.trans (add_comm _ _)
  have hgood : ∑ T : {T // T ∈ chainSet (fun _ : Fin (N + 1) => k) (grassSet k R)},
      c' T.1 • colProd K (fun _ : Fin (N + 1) => k) T.1 ∈
        vanishSpan K (columnMultiplicity (fun _ : Fin (N + 1) => k)) (grassSet k R) := by
    rw [Finset.sum_coe_sort (chainSet (fun _ : Fin (N + 1) => k) (grassSet k R))
      (fun T => c' T • colProd K (fun _ : Fin (N + 1) => k) T)]
    refine ⟨?_, fun g hg => ?_⟩
    · rw [minorSpan_columnMultiplicity]
      exact Submodule.sum_mem _ fun T _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨T, rfl⟩)
    · have h1 : evalAt (g : Matrix (Fin n) (Fin n) K) p = 0 := hp.2 g hg
      have h2 := evalAt_eq_zero_of_mem_forbiddenIdeal hbadmem hg
      rw [hsplit, map_add, h2, add_zero] at h1
      exact h1
  have hc0 := eq_zero_of_sum_mem_vanishSpan _ _ _ hgood
  have hgood0 : ∑ T ∈ chainSet (fun _ : Fin (N + 1) => k) (grassSet k R),
      c' T • colProd K (fun _ : Fin (N + 1) => k) T = 0 :=
    Finset.sum_eq_zero fun T hT => by
      have := congrFun hc0 ⟨T, hT⟩
      simp only [Pi.zero_apply] at this
      rw [this, zero_smul]
  rw [hsplit, hgood0, zero_add]
  exact hbadmem

end

end FlagVarieties.PointModel
