import Schubert.FlagVarieties.Normality.Fulton.KazhdanLusztigPatch

/-!
# Fulton's rank conditions define Schubert varieties scheme-theoretically

Namespace `FlagVarieties.PointModel`, over an algebraically closed field `K` of
characteristic `0`, in the ring `𝒪(GL_n)` of the `B`-torsor `π : GL_n → Fl_n`.

* `orbitIdeal_lowerSet_eq_fultonIdeal` (`RankConditions`): the ideal of `π⁻¹ X_w` is generated by
  Fulton's minors (the rank conditions `rank g_{[q, n), [0, k]} ≤ r_w(k, q)`), and
  `isRadical_map_fultonIdeal`: the ideal they generate is radical.
* `map_kazhdanLusztigSubst_fultonIdeal` (`KazhdanLusztigPatch`): **Kazhdan–Lusztig patches**
  `X_w ∩ v̇ U⁻ B / B`: in the coordinates of the chart `v̇ U⁻`, Fulton's minors of the generic chart
  point generate the ideal of the patch, which is therefore radical
  (`isRadical_map_kazhdanLusztigSubst_fultonIdeal`).
* `orbitIdeal_lowerSet_eq`, `orbitIdeal_lowerSet_eq_span` (`Schubert`): the same ideal is generated
  by the flag minors `Δ_T` with `T ≰ w{0..k}` (the vanishing Plücker coordinates).
* `orbitIdeal_grassSet` (`ParabolicChart`): for one Grassmannian condition `v{0..k} ≤ R`, by
  descent along the parabolic charts of `P_k` and the standard-monomial basis in a single height
  (`mem_forbiddenIdeal_of_mem_vanishSpan`, `Grassmannian`).
* `orbitIdeal_le_of_vanishSpan` (`Descent`): the ideal of `π⁻¹ X_S` is generated by its
  semi-invariant part, by descent along the big cells; with the intersection identity,
  `orbitIdeal_inter`: scheme-theoretic intersections of Schubert unions are reduced.
* `Expansion`: the chart-descent toolkit (expansion along block-triangular matrices, regular and
  good functions, partitions of unity).
-/
