import Schubert.FlagVarieties.Normality.Fulton.Descent
import Schubert.FlagVarieties.Normality.Fulton.Grassmannian
import Mathlib.Data.Matrix.ColumnRowPartitioned

/-!
# The parabolic charts and the ideal of a Grassmannian condition

Fix a height `k` and a row set `S` with `k + 1` elements, with flag minor `p_S = Δ_S`. Where
`p_S(g) ≠ 0`, `g = L(g) b(g)` (`parChart_mul_parBlock`), where

* `b(g)` is block-upper-triangular for the blocks `{0..k}`, `{k+1..}` (it lies in the parabolic
  subgroup `P_k`), with entries polynomial in `g` and `Y(g)`;
* `L(g) = [Y(g) | E]`: `Y(g) = g' a⁻¹`, with `g'` the first `k + 1` columns of `g` and `a` their
  rows `S`; the last columns `E` are constant unit vectors at the rows outside `S`.

By Cramer's rule the entries of `Y(g)` are ratios `Δ_{S[l ← r]} / Δ_S` of flag minors of height `k`
(`parabolicChartMatrix_mul_det`), so a polynomial in the entries of `L(g)` homogenizes into the
single-height part of the flag-minor algebra (`exists_homogenize_parChart`).

**`orbitIdeal_grassSet`**: over an algebraically closed field of characteristic `0`, the ideal of
`π⁻¹ X_{G(k,R)}` in `𝒪(GL_n)` is generated by the flag minors `Δ_T`, `T ≰ R`. The proof is chart
descent (`isGoodOn_of_chart`) along these charts, with the single-height statement
`mem_forbiddenIdeal_of_mem_vanishSpan`.
-/

open Schubert Demazure.FlagModule Demazure.SchubertUnions FinPermutation

namespace FlagVarieties.PointModel

noncomputable section

set_option backward.isDefEq.respectTransparency false

variable {K : Type*} [Field K] {n : ℕ}

/-! ### Index bookkeeping -/

/-- The high indices `{c | k < c}`. -/
abbrev HighIndex (k : Fin n) := {c : Fin n // ¬ c ≤ k}

/-- `Fin (k + 1) ≃ {c | c ≤ k}`. -/
def lowEquiv (k : Fin n) : Fin (k.val + 1) ≃ {c : Fin n // c ≤ k} where
  toFun l := ⟨prefixIndex k l, by
    change (prefixIndex k l).val ≤ k.val
    have := l.isLt
    simp only [prefixIndex]
    omega⟩
  invFun c := ⟨c.1.val, by have : c.1.val ≤ k.val := c.2; omega⟩
  left_inv _ := Fin.ext rfl
  right_inv _ := Subtype.ext (Fin.ext rfl)

/-- `Fin (k + 1) ⊕ {c | k < c} ≃ Fin n`. -/
def blockEquiv (k : Fin n) : Fin (k.val + 1) ⊕ HighIndex k ≃ Fin n :=
  (Equiv.sumCongr (lowEquiv k) (Equiv.refl _)).trans (Equiv.sumCompl fun c : Fin n => c ≤ k)

@[simp]
theorem blockEquiv_inl (k : Fin n) (l : Fin (k.val + 1)) :
    blockEquiv k (Sum.inl l) = prefixIndex k l := rfl

@[simp]
theorem blockEquiv_inr (k : Fin n) (c : HighIndex k) : blockEquiv k (Sum.inr c) = c.1 := rfl

theorem blockEquiv_symm_of_not_le (k : Fin n) {i : Fin n} (hi : ¬ i ≤ k) :
    (blockEquiv k).symm i = Sum.inr ⟨i, hi⟩ :=
  (blockEquiv k).symm_apply_eq.mpr rfl

theorem blockEquiv_symm_of_le (k : Fin n) {i : Fin n} (hi : i ≤ k) :
    ∃ l, (blockEquiv k).symm i = Sum.inl l :=
  ⟨⟨i.val, by have : i.val ≤ k.val := hi; omega⟩, (blockEquiv k).symm_apply_eq.mpr (Fin.ext rfl)⟩

/-- The rows outside `S`. -/
abbrev ComplRows {k : Fin n} (S : FlagMinorRowSet k) := {r : Fin n // r ∉ S.val}

theorem card_highIndex (k : Fin n) : Fintype.card (HighIndex k) = n - (k.val + 1) := by
  rw [Fintype.card_subtype_compl, Fintype.card_fin, ← Fintype.card_congr (lowEquiv k),
    Fintype.card_fin]

theorem card_complRows {k : Fin n} (S : FlagMinorRowSet k) :
    Fintype.card (ComplRows S) = n - (k.val + 1) := by
  rw [Fintype.card_subtype_compl, Fintype.card_fin, Fintype.card_coe,
    (Finset.mem_powersetCard.mp S.property).2]

/-- A bijection `τ` from the high columns onto the rows outside `S`. -/
def highEquiv {k : Fin n} (S : FlagMinorRowSet k) : HighIndex k ≃ ComplRows S :=
  Fintype.equivOfCardEq (by rw [card_highIndex, card_complRows])

/-! ### The factorization `g = L(g) b(g)` -/

variable {k : Fin n}

/-- `a = g_{S, 0..k}`. -/
def parabolicPivotBlock (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K) :
    Matrix (Fin (k.val + 1)) (Fin (k.val + 1)) K :=
  g.submatrix S.rows (prefixIndex k)

theorem evalAt_rowMinor_rows (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K) :
    evalAt g (rowMinor K k S.rows) = (parabolicPivotBlock S g).det :=
  evalAt_rowMinor g k S.rows

/-- `Y = g_{·, 0..k} a⁻¹`. -/
def parabolicChartMatrix (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K) :
    Matrix (Fin n) (Fin (k.val + 1)) K :=
  g.submatrix id (prefixIndex k) * (parabolicPivotBlock S g)⁻¹

/-- The constant block `E`: its column `c` is the unit vector at the row `τ c ∉ S`. -/
def parabolicUnitBlock (K : Type*) [Field K] (S : FlagMinorRowSet k) :
    Matrix (Fin n) (HighIndex k) K :=
  fun r c => if r = (highEquiv S c).1 then 1 else 0

/-- `g_{·, high} - Y g_{S, high}`. -/
def parabolicRest (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K) :
    Matrix (Fin n) (HighIndex k) K :=
  g.submatrix id Subtype.val - parabolicChartMatrix S g * g.submatrix S.rows Subtype.val

/-- The rows `τ c` of `parabolicRest`. -/
def parabolicRestBlock (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K) :
    Matrix (HighIndex k) (HighIndex k) K :=
  fun c j => parabolicRest S g (highEquiv S c).1 j

/-- **The chart representative** `L(g) = [Y | E]`. -/
def parChart (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K) : Matrix (Fin n) (Fin n) K :=
  (Matrix.fromCols (parabolicChartMatrix S g) (parabolicUnitBlock K S)).submatrix id
      (blockEquiv k).symm

/-- **The parabolic factor** `b(g)`. -/
def parBlock (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K) : Matrix (Fin n) (Fin n) K :=
  (Matrix.fromBlocks (parabolicPivotBlock S g) (g.submatrix S.rows Subtype.val) 0
      (parabolicRestBlock S g)).submatrix
    (blockEquiv k).symm (blockEquiv k).symm

theorem parabolicChartMatrix_mul_parabolicPivotBlock (S : FlagMinorRowSet k)
    (g : Matrix (Fin n) (Fin n) K)
    (hg : (parabolicPivotBlock S g).det ≠ 0) : parabolicChartMatrix S g * parabolicPivotBlock S g =
        g.submatrix id (prefixIndex k) := by
  rw [parabolicChartMatrix, Matrix.mul_assoc, Matrix.nonsing_inv_mul _ (isUnit_iff_ne_zero.mpr hg),
    Matrix.mul_one]

theorem parabolicChartMatrix_rows (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K)
    (hg : (parabolicPivotBlock S g).det ≠ 0) (l m : Fin (k.val + 1)) :
    parabolicChartMatrix S g (S.rows l) m = if l = m then 1 else 0 := by
  have h : (parabolicChartMatrix S g).submatrix S.rows id = 1 := by
    have : (parabolicChartMatrix S g).submatrix S.rows id = parabolicPivotBlock S g *
        (parabolicPivotBlock S g)⁻¹ := by
      ext a b
      simp [parabolicChartMatrix, parabolicPivotBlock, Matrix.mul_apply]
    rw [this, Matrix.mul_nonsing_inv _ (isUnit_iff_ne_zero.mpr hg)]
  have := congrFun (congrFun h l) m
  simpa [Matrix.one_apply] using this

theorem parabolicUnitBlock_mul_parabolicRestBlock (S : FlagMinorRowSet k)
    (g : Matrix (Fin n) (Fin n) K)
    (hg : (parabolicPivotBlock S g).det ≠ 0) : parabolicUnitBlock K S * parabolicRestBlock S g =
        parabolicRest S g := by
  classical
  ext r j
  rw [Matrix.mul_apply]
  by_cases hr : r ∈ S.val
  · have h0 : ∀ c, parabolicUnitBlock K S r c = 0 := fun c =>
      ite_eq_right (fun h => (highEquiv S c).2 (by rw [← h]; exact hr))
    rw [Finset.sum_eq_zero fun c _ => by rw [h0 c, zero_mul]]
    obtain ⟨l, rfl⟩ : ∃ l, S.rows l = r := by
      have : r ∈ Set.range S.rows := by
        rw [FlagMinorRowSet.rows, Finset.range_orderEmbOfFin]
        exact hr
      exact this
    simp [parabolicRest, Matrix.mul_apply, parabolicChartMatrix_rows S g hg]
  · rw [Finset.sum_eq_single ((highEquiv S).symm ⟨r, hr⟩)]
    · simp [parabolicUnitBlock, parabolicRestBlock]
    · intro c _ hc
      have hne : r ≠ (highEquiv S c).1 := by
        intro h
        apply hc
        rw [Equiv.eq_symm_apply]
        exact Subtype.ext h.symm
      rw [parabolicUnitBlock, ite_eq_right hne, zero_mul]
    · intro h
      exact absurd (Finset.mem_univ _) h

theorem fromCols_submatrix {α : Type*} (g : Matrix (Fin n) (Fin n) α) :
    Matrix.fromCols (g.submatrix id (prefixIndex k)) (g.submatrix id Subtype.val) =
      g.submatrix id (blockEquiv k) := by
  ext r (l | c) <;> rfl

/-- **`g = L(g) b(g)`** where `p_S(g) ≠ 0`. -/
theorem parChart_mul_parBlock (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K)
    (hg : (parabolicPivotBlock S g).det ≠ 0) : parChart S g * parBlock S g = g := by
  rw [parChart, parBlock, Matrix.submatrix_mul_equiv, Matrix.fromCols_mul_fromBlocks,
    Matrix.mul_zero, add_zero, parabolicChartMatrix_mul_parabolicPivotBlock S g hg,
        parabolicUnitBlock_mul_parabolicRestBlock S g hg, parabolicRest,
    add_sub_cancel, fromCols_submatrix, Matrix.submatrix_submatrix]
  simp

theorem parBlock_blockTriangular (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K) :
    (parBlock S g).BlockTriangular (prefixBlock k) := by
  intro i j hij
  unfold prefixBlock at hij
  by_cases hi : i ≤ k
  · simp [hi] at hij
  · by_cases hj : j ≤ k
    · obtain ⟨l, hl⟩ := blockEquiv_symm_of_le k hj
      simp [parBlock, blockEquiv_symm_of_not_le k hi, hl]
    · simp [hi, hj] at hij

/-! ### Cramer's rule and homogenization -/

/-- **Cramer's rule**: `Y_rl · Δ_S = Δ_{S[l ← r]}`. -/
theorem parabolicChartMatrix_mul_det (S : FlagMinorRowSet k) (g : Matrix (Fin n) (Fin n) K)
    (hg : (parabolicPivotBlock S g).det ≠ 0) (r : Fin n) (l : Fin (k.val + 1)) :
    parabolicChartMatrix S g r l * (parabolicPivotBlock S g).det = evalAt g
        (rowMinor K k (Function.update (⇑S.rows) l r)) := by
  rw [evalAt_rowMinor]
  have hupd : g.submatrix (Function.update (⇑S.rows) l r) (prefixIndex k) =
      (parabolicPivotBlock S g).updateRow l (fun j => g r (prefixIndex k j)) := by
    ext a b
    by_cases hab : a = l
    · subst hab
      simp [parabolicPivotBlock]
    · simp [parabolicPivotBlock, hab]
  rw [hupd, ← Matrix.cramer_transpose_apply, Matrix.cramer_eq_adjugate_mulVec,
    ← Matrix.adjugate_transpose]
  simp only [parabolicChartMatrix, Matrix.mul_apply, Matrix.mulVec, dotProduct,
      Matrix.transpose_apply,
    Matrix.inv_def, Matrix.smul_apply, smul_eq_mul, Matrix.submatrix_apply, id, Finset.sum_mul]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [Ring.inverse_eq_inv]
  field_simp

/-- Exponent and numerator of the entry `(r, c)` of `L(g)`: `(1, Δ_{S[l ← r]})` in a low column
`c = l`, and `(0, E_rc)` in a high column. -/
def parNum (K : Type*) [Field K] (S : FlagMinorRowSet k) (r c : Fin n) :
    ℕ × MatrixEntryPolynomial K n :=
  Sum.elim (fun l => (1, rowMinor K k (Function.update (⇑S.rows) l r)))
    (fun h => (0, MvPolynomial.C (parabolicUnitBlock K S r h))) ((blockEquiv k).symm c)

theorem parNum_mem (S : FlagMinorRowSet k) (r c : Fin n) :
    (parNum K S r c).2 ∈ minorSpan K ((parNum K S r c).1 • Pi.single k 1) := by
  rcases h : (blockEquiv k).symm c with l | hc
  · simp only [parNum, h, Sum.elim_inl, one_smul]
    exact rowMinor_mem_minorSpan k _
  · simp only [parNum, h, Sum.elim_inr, zero_smul]
    rw [← mul_one (MvPolynomial.C _), ← MvPolynomial.smul_eq_C_mul]
    exact Submodule.smul_mem _ _ one_mem_minorSpan

theorem parNum_spec (S : FlagMinorRowSet k) (r c : Fin n) (g : Matrix (Fin n) (Fin n) K)
    (hg : (parabolicPivotBlock S g).det ≠ 0) :
    evalAt g (parNum K S r c).2 = (parabolicPivotBlock S g).det ^ (parNum K S r c).1 *
        parChart S g r c := by
  rcases h : (blockEquiv k).symm c with l | hc
  · simp only [parNum, h, Sum.elim_inl, pow_one, parChart, Matrix.submatrix_apply, id,
      Matrix.fromCols_apply_inl]
    rw [← parabolicChartMatrix_mul_det S g hg, mul_comm]
  · simp only [parNum, h, Sum.elim_inr, pow_zero, one_mul, parChart, Matrix.submatrix_apply, id,
      Matrix.fromCols_apply_inr]
    simp [evalAt]

/-- **Homogenization on the parabolic chart**: `p_S^N · P(L(g))` is a polynomial `Q` in the flag
minors of height `k`, of degree `N`. -/
theorem exists_homogenize_parChart (S : FlagMinorRowSet k) (P : MatrixEntryPolynomial K n) :
    ∃ (N : ℕ) (Q : MatrixEntryPolynomial K n), Q ∈ minorSpan K (N • Pi.single k 1) ∧
      ∀ g : Matrix (Fin n) (Fin n) K, (parabolicPivotBlock S g).det ≠ 0 →
        evalAt g Q = (parabolicPivotBlock S g).det ^ N * evalAt (parChart S g) P := by
  induction P using MvPolynomial.induction_on with
  | C a =>
    refine ⟨0, MvPolynomial.C a, ?_, fun g _ => by simp [evalAt]⟩
    rw [zero_smul, ← mul_one (MvPolynomial.C a), ← MvPolynomial.smul_eq_C_mul]
    exact Submodule.smul_mem _ a one_mem_minorSpan
  | add p q hp hq =>
    obtain ⟨N₁, Q₁, hQ₁, h₁⟩ := hp
    obtain ⟨N₂, Q₂, hQ₂, h₂⟩ := hq
    refine ⟨N₁ + N₂, Q₁ * rowMinor K k S.rows ^ N₂ + Q₂ * rowMinor K k S.rows ^ N₁, ?_,
      fun g hg => ?_⟩
    · rw [add_smul]
      refine Submodule.add_mem _
        (mul_mem_minorSpan hQ₁ (pow_mem_minorSpan (rowMinor_mem_minorSpan k _) N₂)) ?_
      have := mul_mem_minorSpan hQ₂ (pow_mem_minorSpan (rowMinor_mem_minorSpan k S.rows) N₁)
      rwa [add_comm (N₂ • _)] at this
    · rw [map_add, map_mul, map_mul, map_pow, map_pow, h₁ g hg, h₂ g hg, map_add,
        evalAt_rowMinor_rows]
      ring
  | mul_X p rc hp =>
    obtain ⟨N, Q, hQ, hQe⟩ := hp
    refine ⟨N + (parNum K S rc.1 rc.2).1, Q * (parNum K S rc.1 rc.2).2, ?_, fun g hg => ?_⟩
    · rw [add_smul]
      exact mul_mem_minorSpan hQ (parNum_mem S rc.1 rc.2)
    · rw [map_mul, hQe g hg, parNum_spec S rc.1 rc.2 g hg, map_mul, evalAt_X]
      ring

/-! ### Regularity and goodness -/

theorem isRegularOn_parabolicChartMatrix (S : FlagMinorRowSet k) (r : Fin n) (l : Fin (k.val + 1)) :
    IsRegularOn (rowMinor K k S.rows) fun g =>
        parabolicChartMatrix S (g : Matrix (Fin n) (Fin n) K) r l :=
  ⟨1, rowMinor K k (Function.update (⇑S.rows) l r), fun g hg => by
    rw [evalAt_rowMinor_rows] at hg
    rw [← parabolicChartMatrix_mul_det S _ hg, evalAt_rowMinor_rows, pow_one, mul_comm]⟩

theorem isRegularOn_parBlock (S : FlagMinorRowSet k) (i j : Fin n) :
    IsRegularOn (rowMinor K k S.rows) fun g => parBlock S (g : Matrix (Fin n) (Fin n) K) i j := by
  rcases hi : (blockEquiv k).symm i with li | ci <;>
    rcases hj : (blockEquiv k).symm j with lj | cj
  · exact (isRegularOn_entry (S.rows li) (prefixIndex k lj)).congr fun g _ => by
      simp [parBlock, hi, hj, parabolicPivotBlock]
  · exact (isRegularOn_entry (S.rows li) cj.1).congr fun g _ => by
      simp [parBlock, hi, hj]
  · exact (isRegularOn_const 0).congr fun g _ => by
      simp [parBlock, hi, hj]
  · have hsum : IsRegularOn (rowMinor K k S.rows) fun g : GL (Fin n) K =>
        ∑ m, parabolicChartMatrix S (g : Matrix (Fin n) (Fin n) K) (highEquiv S ci).1 m *
          (g : Matrix (Fin n) (Fin n) K) (S.rows m) cj.1 :=
      IsRegularOn.sum Finset.univ
        (fun m (g : GL (Fin n) K) => parabolicChartMatrix S (g : Matrix (Fin n) (Fin n) K)
                                       (highEquiv S ci).1 m *
          (g : Matrix (Fin n) (Fin n) K) (S.rows m) cj.1)
        fun m _ => (isRegularOn_parabolicChartMatrix S _ m).mul (isRegularOn_entry _ _)
    exact ((isRegularOn_entry (highEquiv S ci).1 cj.1).sub hsum).congr fun g _ => by
      simp [parBlock, hi, hj, parabolicRestBlock, parabolicRest, Matrix.mul_apply]

/-- Where `p_S ≠ 0`, `L(g) ∈ π⁻¹ X_{G(k,R)}` together with `g`. -/
theorem exists_parChart_mem {R S : FlagMinorRowSet k} {g : GL (Fin n) K}
    (hg : g ∈ orbitSet K (grassSet k R))
        (hd : (parabolicPivotBlock S (g : Matrix (Fin n) (Fin n) K)).det ≠ 0) :
    ∃ g' ∈ orbitSet K (grassSet k R),
      (g' : Matrix (Fin n) (Fin n) K) = parChart S (g : Matrix (Fin n) (Fin n) K) := by
  have hLb := parChart_mul_parBlock S (g : Matrix (Fin n) (Fin n) K) hd
  have hgdet : (g : Matrix (Fin n) (Fin n) K).det ≠ 0 :=
    ((Matrix.isUnit_iff_isUnit_det _).mp g.isUnit).ne_zero
  have hbdet : IsUnit (parBlock S (g : Matrix (Fin n) (Fin n) K)).det := by
    refine isUnit_iff_ne_zero.mpr fun h => hgdet ?_
    rw [← hLb, Matrix.det_mul, h, mul_zero]
  have := Matrix.invertibleOfIsUnitDet _ hbdet
  have hinv := Matrix.blockTriangular_inv_of_blockTriangular
    (parBlock_blockTriangular S (g : Matrix (Fin n) (Fin n) K))
  have hinvu := Matrix.isUnit_nonsing_inv_det _ hbdet
  refine ⟨g * unitOfDet _ hinvu, orbitSet_grassSet_mul hg _ (by rw [coe_unitOfDet]; exact hinv),
    ?_⟩
  rw [Units.val_mul, coe_unitOfDet]
  calc (g : Matrix (Fin n) (Fin n) K) * (parBlock S (g : Matrix (Fin n) (Fin n) K))⁻¹ =
      parChart S (g : Matrix (Fin n) (Fin n) K) * parBlock S (g : Matrix (Fin n) (Fin n) K) *
        (parBlock S (g : Matrix (Fin n) (Fin n) K))⁻¹ := by rw [hLb]
    _ = parChart S (g : Matrix (Fin n) (Fin n) K) := by
      rw [Matrix.mul_assoc, Matrix.mul_nonsing_inv _ hbdet, Matrix.mul_one]

/-- A polynomial vanishing on `π⁻¹ X_{G(k,R)}`, read in the parabolic chart of `S`, is good for the
forbidden ideal. -/
theorem isGoodOn_parChart [CharZero K] (R S : FlagMinorRowSet k) (P : MatrixEntryPolynomial K n)
    (hP : ∀ g ∈ orbitSet K (grassSet k R), evalAt (g : Matrix (Fin n) (Fin n) K) P = 0) :
    IsGoodOn (rowMinor K k S.rows) (forbiddenIdeal K k R)
      fun g => evalAt (parChart S (g : Matrix (Fin n) (Fin n) K)) P := by
  obtain ⟨N, Q, hQ, hQe⟩ := exists_homogenize_parChart S P
  have hmem : Q * rowMinor K k S.rows ∈ minorSpan K ((N + 1) • Pi.single k 1) := by
    rw [succ_nsmul]
    exact mul_mem_minorSpan hQ (rowMinor_mem_minorSpan k _)
  refine ⟨N + 1, Q * rowMinor K k S.rows,
    mem_forbiddenIdeal_of_mem_vanishSpan k R N ⟨hmem, fun g hg => ?_⟩, fun g hg => ?_⟩
  · by_cases hd : (parabolicPivotBlock S (g : Matrix (Fin n) (Fin n) K)).det = 0
    · rw [map_mul, evalAt_rowMinor_rows, hd, mul_zero]
    · obtain ⟨g', hg', hg'L⟩ := exists_parChart_mem hg hd
      have h0 := hP g' hg'
      rw [hg'L] at h0
      rw [map_mul, hQe _ hd, h0, mul_zero, zero_mul]
  · rw [evalAt_rowMinor_rows] at hg
    rw [map_mul, hQe _ hg, evalAt_rowMinor_rows, pow_succ]
    ring

/-- Every `g ∈ GL_n(K)` has a nonzero flag minor of height `k`. -/
theorem exists_rowMinor_ne_zero (k : Fin n) (g : GL (Fin n) K) :
    ∃ S : FlagMinorRowSet k, evalAt (g : Matrix (Fin n) (Fin n) K) (rowMinor K k S.rows) ≠ 0 := by
  obtain ⟨v, hv⟩ := exists_chartMinor_ne_zero g
  refine ⟨flagPrefixRows v k, fun h => hv k ?_⟩
  rw [evalAt_chartMinor_eq, h, mul_zero]

/-- **The ideal of a Grassmannian condition**: `I(π⁻¹ X_{G(k,R)}) = (Δ_T : T ≰ R)` in `𝒪(GL_n)`. -/
theorem orbitIdeal_grassSet [IsAlgClosed K] [CharZero K] (k : Fin n) (R : FlagMinorRowSet k) :
    orbitIdeal K (grassSet k R) =
      (forbiddenIdeal K k R).map (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n)) := by
  apply le_antisymm
  · intro t ht
    obtain ⟨r, e, hre⟩ := exists_mul_det_pow t
    have hr : ∀ g ∈ orbitSet K (grassSet k R), evalAt (g : Matrix (Fin n) (Fin n) K) r = 0 :=
      fun g hg => evalAt_eq_zero_of_mul_det_pow hre (ht g hg)
    refine mem_of_mul_det_pow hre (algebraMap_mem_of_isGoodOn
      (fun S : FlagMinorRowSet k => rowMinor K k S.rows) (exists_rowMinor_ne_zero k) fun S => ?_)
    exact isGoodOn_of_chart (prefixBlock k) (fun g hg p hp => orbitSet_grassSet_mul hg p hp) hr _ _
      (fun g => parChart S (g : Matrix (Fin n) (Fin n) K))
      (fun g => parBlock S (g : Matrix (Fin n) (Fin n) K))
      (fun g hg => ⟨(parChart_mul_parBlock S _ (by rwa [evalAt_rowMinor_rows] at hg)).symm,
        parBlock_blockTriangular S _⟩)
      (isRegularOn_parBlock S) (fun P hP => isGoodOn_parChart R S P hP)
  · rw [Ideal.map_le_iff_le_comap]
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨T, hT, rfl⟩
    exact algebraMap_mem_orbitIdeal fun g hg => evalAt_rowMinor_eq_zero_of_mem_orbitSet hT hg

end

end FlagVarieties.PointModel
