import Schubert.FlagVarieties.Normality.Fulton.ParabolicChart

/-!
# Schubert varieties are cut out scheme-theoretically by flag minors

`schubertIdeal K w ⊆ K[x_ij]` is generated by the flag minors `Δ_T` of every height `k` with
`T ≰ w{0..k}`: the Plücker coordinates vanishing on `X_w`.

**`orbitIdeal_lowerSet_eq`**: over an algebraically closed field of characteristic `0`, the ideal of
`π⁻¹ X_w` in `𝒪(GL_n)` is generated by these minors. As `π : GL_n → Fl_n` is a `B`-torsor, this
says that the closed subscheme of `Fl_n` cut out by these Plücker coordinates is `X_w` with its
reduced structure.

Proof: `↓w = ⋂_k grassSet k (w{0..k})` (tableau criterion, `lowerSet_eq_inf`). By the intersection
identity the semi-invariant part of the ideal of the intersection is the sum of the semi-invariant
parts (`mem_iSup_vanishSpan_of_mem_inf`); descent along the big cells
(`orbitIdeal_le_of_vanishSpan`) reduces the claim to semi-invariants, and each Grassmannian
condition is `orbitIdeal_grassSet`.
-/

open Schubert Demazure.FlagModule Demazure.SchubertUnions FinPermutation

namespace FlagVarieties.PointModel

noncomputable section

set_option backward.isDefEq.respectTransparency false

variable {K : Type*} [Field K] {n : ℕ}

/-- The ideal generated by the flag minors `Δ_T`, `T ≰ w{0..k}`, of all heights `k`. -/
def schubertIdeal (K : Type*) [Field K] (w : Equiv.Perm (Fin n)) :
    Ideal (MatrixEntryPolynomial K n) :=
  ⨆ k, forbiddenIdeal K k (flagPrefixRows w k)

theorem rowMinor_mem_schubertIdeal {w : Equiv.Perm (Fin n)} {k : Fin n} {T : FlagMinorRowSet k}
    (hT : ¬ galeLE T (flagPrefixRows w k)) : rowMinor K k T.rows ∈ schubertIdeal K w :=
  Ideal.mem_iSup_of_mem k (rowMinor_mem_forbiddenIdeal hT)

theorem bruhatLower_finset_inf {ι : Type*} (s : Finset ι) (F : ι → Finset (Equiv.Perm (Fin n)))
    (hF : ∀ i, BruhatLower (F i)) : BruhatLower (s.inf F) := by
  intro w hw v hvw
  rw [Finset.mem_inf] at hw ⊢
  exact fun i hi => hF i w (hw i hi) v hvw

/-- **The intersection identity for finite intersections**. -/
theorem mem_iSup_vanishSpan_of_mem_inf [Infinite K] (hSMT : StandardMonomialTheory K)
    (m : ColumnShape n)
    {ι : Type*} [DecidableEq ι] (s : Finset ι) (F : ι → Finset (Equiv.Perm (Fin n)))
    (hF : ∀ i, BruhatLower (F i)) {p : MatrixEntryPolynomial K n}
        (hp : p ∈ vanishSpan K m (s.inf F)) :
    p ∈ ⨆ i, vanishSpan K m (F i) := by
  induction s using Finset.induction_on generalizing p with
  | empty =>
    rw [Finset.inf_empty, Finset.top_eq_univ, vanishSpan_univ] at hp
    rw [(Submodule.mem_bot K).mp hp]
    exact Submodule.zero_mem _
  | insert a s ha ih =>
    rw [Finset.inf_insert, Finset.inf_eq_inter,
      vanishSpan_inter hSMT m (hF a) (bruhatLower_finset_inf s F hF)] at hp
    obtain ⟨x, hx, y, hy, rfl⟩ := Submodule.mem_sup.mp hp
    exact Submodule.add_mem _ (Submodule.mem_iSup_of_mem a hx) (ih hy)

/-- **Schubert varieties are defined scheme-theoretically by the vanishing Plücker coordinates**:
`I(π⁻¹ X_w) = (Δ_T : T ≰ w{0..k})` in `𝒪(GL_n)`. -/
theorem orbitIdeal_lowerSet_eq [IsAlgClosed K] [CharZero K] (w : Equiv.Perm (Fin n)) :
    orbitIdeal K (lowerSet w) =
      (schubertIdeal K w).map (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n)) := by
  classical
  apply le_antisymm
  · refine orbitIdeal_le_of_vanishSpan _ _ fun m p hp => ?_
    rw [lowerSet_eq_inf] at hp
    have hp' := mem_iSup_vanishSpan_of_mem_inf (standardMonomialTheory_of_charZero K) m Finset.univ
      (fun k => grassSet k (flagPrefixRows w k)) (fun k => bruhatLower_grassSet k _) hp
    refine Submodule.iSup_induction _
      (motive := fun x => algebraMap (MatrixEntryPolynomial K n) (GLCoord K n) x ∈
        (schubertIdeal K w).map (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n))) hp' ?_ ?_ ?_
    · intro k q hq
      have hq' := algebraMap_mem_orbitIdeal (K := K) hq.2
      rw [orbitIdeal_grassSet] at hq'
      exact Ideal.map_mono (le_iSup (fun k => forbiddenIdeal K k (flagPrefixRows w k)) k) hq'
    · rw [map_zero]
      exact Submodule.zero_mem _
    · intro x y hx hy
      rw [map_add]
      exact Submodule.add_mem _ hx hy
  · rw [Ideal.map_le_iff_le_comap]
    refine iSup_le fun k => Ideal.span_le.mpr ?_
    rintro _ ⟨T, hT, rfl⟩
    exact algebraMap_mem_orbitIdeal fun g hg =>
      evalAt_rowMinor_eq_zero_of_mem_orbitSet hT (orbitSet_mono (lowerSet_subset_grassSet w k) hg)

/-- The same statement as an ideal of `𝒪(GL_n)` spanned by the forbidden minors. -/
theorem orbitIdeal_lowerSet_eq_span [IsAlgClosed K] [CharZero K] (w : Equiv.Perm (Fin n)) :
    orbitIdeal K (lowerSet w) = Ideal.span {t | ∃ (k : Fin n) (T : FlagMinorRowSet k),
      ¬ galeLE T (flagPrefixRows w k) ∧
        t = algebraMap (MatrixEntryPolynomial K n) (GLCoord K n) (rowMinor K k T.rows)} := by
  rw [orbitIdeal_lowerSet_eq]
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    refine iSup_le fun k => Ideal.span_le.mpr ?_
    rintro _ ⟨T, hT, rfl⟩
    exact Ideal.subset_span ⟨k, T, hT, rfl⟩
  · refine Ideal.span_le.mpr ?_
    rintro _ ⟨k, T, hT, rfl⟩
    exact Ideal.mem_map_of_mem _ (rowMinor_mem_schubertIdeal hT)

end

end FlagVarieties.PointModel
