import RSCounterexample.Demazure.Filtrations.RelativeSchubertCharacters

/-!
# Characters of section modules over unions of Schubert varieties

For an antidominant weight `η = k·(1,…,1) − λ` and a finite set `S` of permutations, let `I` be
the Bruhat ideal generated by `S`, so that `X_S = X_I`. Then

  `ch H⁰(X_S, 𝓛(η)) = x^{-k·1} Σ_{τ ∈ I ∩ W^λ} 𝒜_{τλ}`       (`schubertSectionModule_hasCharacter`).

This is the character-level content of van der Kallen's Proposition 2.3.11: the character of a
section module over a union of Schubert varieties is a sum of characters of minimal relative
Schubert modules.
-/

open Schubert

namespace Demazure

open FlagModule BModules FinPermutation

namespace SchubertUnions

variable {n d : ℕ}

instance (dom : Composition n) : DecidablePred (IsMinCosetRep dom) := fun σ => by
  unfold IsMinCosetRep; infer_instance

/-- The generating function of a Bruhat ideal splits by right keys. -/
theorem chainCharacter_eq_sum_exact (h : Fin d → Fin n) (I : Finset (FinPermutation n))
    (hI : BruhatLower I) : chainCharacter h I = ∑ τ ∈ I, exactCharacter h τ := by
  classical
  have hmaps : ∀ T ∈ chainSet h I, rightKeyOf h T ∈ I := by
    intro T hT
    obtain ⟨w, hw, hc⟩ := mem_chainSet.mp hT
    exact hI w hw _ ((hasFlagDefiningChain_iff_rightKeyOf_le ⟨w, hc⟩ w).mp hc)
  rw [chainCharacter, ← Finset.sum_fiberwise_of_maps_to hmaps]
  refine Finset.sum_congr rfl fun τ hτ => ?_
  rw [exactCharacter]
  refine Finset.sum_congr ?_ fun _ _ => rfl
  ext T
  rw [Finset.mem_filter]
  constructor
  · rintro ⟨hT, rfl⟩
    exact (mem_exactChainSet_iff (let ⟨w, _, hc⟩ := mem_chainSet.mp hT; ⟨w, hc⟩)).mpr rfl
  · intro hT
    have hT' : T ∈ chainSet h {τ} := by
      rw [exactChainSet] at hT
      exact (Finset.mem_sdiff.mp hT).1
    obtain ⟨w, hw, hc⟩ := mem_chainSet.mp hT'
    refine ⟨?_, (mem_exactChainSet_iff ⟨w, hc⟩).mp hT⟩
    rw [Finset.mem_singleton] at hw
    subst hw
    exact mem_chainSet.mpr ⟨w, hτ, hc⟩

end SchubertUnions

namespace Filtrations

open SchubertUnions

noncomputable section

variable {n : ℕ}

/-- The Bruhat ideal `{τ | ∃ w ∈ S, τ ≤ w}` generated by `S`. -/
def lowerClosure (S : Finset (FinPermutation n)) : Finset (FinPermutation n) := by
  classical exact Finset.univ.filter fun τ => ∃ w ∈ S, τ ≤ᴮ w

theorem mem_lowerClosure {S : Finset (FinPermutation n)} {τ : FinPermutation n} :
    τ ∈ lowerClosure S ↔ ∃ w ∈ S, τ ≤ᴮ w := by
  classical
  unfold lowerClosure
  simp

theorem lowerClosure_bruhatLower (S : Finset (FinPermutation n)) :
    BruhatLower (lowerClosure S) := by
  intro w hw v hv
  obtain ⟨x, hx, hwx⟩ := mem_lowerClosure.mp hw
  exact mem_lowerClosure.mpr ⟨x, hx, strongBruhat_trans hv hwx⟩

theorem demazureUnion_lowerClosure (m : ColumnShape n) (S : Finset (FinPermutation n)) :
    demazureUnion m (lowerClosure S) = demazureUnion m S :=
  le_antisymm (demazureUnion_mono m fun _ hw => mem_lowerClosure.mp hw)
    (demazureUnion_mono m fun w hw => ⟨w, mem_lowerClosure.mpr ⟨w, hw, strongBruhat_refl w⟩,
      strongBruhat_refl w⟩)

theorem demazureUnionModule_hasTorusCharacter_congr (m : ColumnShape n)
    {S S' : Finset (FinPermutation n)} (h : demazureUnion m S = demazureUnion m S')
    {p : Polynomial n} (hp : HasTorusCharacter (demazureUnionModule m S).torus p) :
    HasTorusCharacter (demazureUnionModule m S').torus p :=
  HasTorusCharacter.of_equiv hp (LinearEquiv.ofEq _ _ h) fun _ _ => rfl

/-- The character of `Σ_{w ∈ S} D_w(λ)`: `Σ_{τ ∈ I ∩ W^λ} 𝒜_{τλ}` for the ideal `I` generated
by `S`. -/
theorem demazureUnionModule_hasTorusCharacter_atoms (dom : Composition n) (hdom : Antitone dom)
    (S : Finset (FinPermutation n)) :
    HasTorusCharacter (demazureUnionModule (columnsOfWeight dom) S).torus
      (∑ τ ∈ (lowerClosure S).filter (IsMinCosetRep dom), atom (permAct τ dom)) := by
  classical
  obtain ⟨d, h, hm⟩ := exists_columnMultiplicity (columnsOfWeight dom)
  have hshape : shapeWeight (columnMultiplicity h) = dom := by
    rw [hm, shapeWeight_columnsOfWeight dom hdom]
  have hc := demazureUnion_hasTorusCharacter h (lowerClosure S) (lowerClosure_bruhatLower S)
  rw [chainCharacter_eq_sum_exact h _ (lowerClosure_bruhatLower S)] at hc
  have hsum : ∑ τ ∈ lowerClosure S, exactCharacter h τ =
      ∑ τ ∈ (lowerClosure S).filter (IsMinCosetRep dom), atom (permAct τ dom) := by
    rw [Finset.sum_filter]
    refine Finset.sum_congr rfl fun τ _ => ?_
    rw [exactCharacter_eq]
    by_cases hW : IsMinCosetRep dom τ
    · simp only [hW, ite_true, extremalWeight_eq_permAct, hshape]
    · have hW' : ¬ IsMinCosetRep (shapeWeight (columnMultiplicity h)) τ := hshape ▸ hW
      simp only [hW, hW', ite_false]
  rw [hsum, hm] at hc
  exact demazureUnionModule_hasTorusCharacter_congr _ (demazureUnion_lowerClosure _ S) hc

/-- **Characters of section modules over unions of Schubert varieties.**
`ch H⁰(X_S, 𝓛(k·1 − λ)) = x^{-k·1} Σ_{τ ∈ I ∩ W^λ} 𝒜_{τλ}`. -/
theorem sectionModuleOf_hasCharacter_atoms (k : ℕ) (dom : Composition n) (hdom : Antitone dom)
    (S : Finset (FinPermutation n)) :
    (sectionModuleOf k dom S).HasCharacter
      (AddMonoidAlgebra.single (-BModule.constWeight (k : ℤ)) 1 *
        ∑ τ ∈ (lowerClosure S).filter (IsMinCosetRep dom), toLaurent (atom (permAct τ dom))) := by
  rw [← map_sum]
  exact sectionModuleOf_hasCharacter k dom S
      (demazureUnionModule_hasTorusCharacter_atoms dom hdom S)

theorem weightComplement_antitone {η : Weight n} (hη : Monotone η) :
    Antitone (weightComplement η) := by
  intro i j hij
  have h1 := weightComplement_cast η i
  have h2 := weightComplement_cast η j
  have := hη hij
  omega

/-- The character of `H⁰(X_S, 𝓛(η))` for antidominant `η`. -/
theorem schubertSectionModule_hasCharacter (η : Weight n) (hη : Monotone η)
    (S : Finset (FinPermutation n)) :
    (schubertSectionModule η S).HasCharacter
      (AddMonoidAlgebra.single (-BModule.constWeight (weightShift η : ℤ)) 1 *
        ∑ τ ∈ (lowerClosure S).filter (IsMinCosetRep (weightComplement η)),
          toLaurent (atom (permAct τ (weightComplement η)))) :=
  sectionModuleOf_hasCharacter_atoms _ _ (weightComplement_antitone hη) S

end

end Filtrations

end Demazure
