import RSCounterexample.GLRep.HighestWeight.Basic
import RSCounterexample.GLRep.Weyl.GroupCharacter
import Mathlib.Algebra.Lie.Quotient

/-!
# Submodules and quotients of integral `gl_n`-modules

Let `M` be an integral `gl_n(K)`-module, `K` a field of characteristic zero: finite-dimensional
and spanned by its integral weight spaces. The projections of `M` onto its weight spaces are
polynomials in the diagonal matrix units (`GLRep.IsIntegralGLModule.exists_proj`), Lagrange
interpolation in each coordinate. Hence every Lie submodule `N` of `M` is spanned by its
intersections with the weight spaces, and `N` and `M ⧸ N` are integral
(`GLRep.IsIntegralGLModule.lieSubmodule`, `GLRep.IsIntegralGLModule.quotient`). The weight spaces
of `M ⧸ N` are the images of those of `M` (`GLRep.IsIntegralGLModule.map_mk'_glWeightSpace`).

## Main results

* `GLRep.IsIntegralGLModule.exists_proj`: the weight projections.
* `GLRep.IsIntegralGLModule.lieSubmodule`, `GLRep.IsIntegralGLModule.quotient`.
* `GLRep.mem_glWeightSpace_lieSubmodule_iff`.
* `GLRep.IsIntegralGLModule.map_mk'_glWeightSpace`.
* `GLRep.IsIntegralGLModule.exists_isGlHighestWeightVector`.
-/

namespace GLRep

open Module LieModule Finset Polynomial

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

variable {K : Type*} [Field K] [CharZero K] {n : ℕ}
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule (Matrix (Fin n) (Fin n) K) M]
  [LieModule K (Matrix (Fin n) (Fin n) K) M]

omit [CharZero K] in
/-- A diagonalizable operator acts on an eigenvector through polynomials by evaluation. -/
theorem aeval_apply_of_eq_smul {D : Module.End K M} {c : K} {w : M} (hw : D w = c • w)
    (p : K[X]) : aeval D p w = p.eval c • w := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => rw [map_add, LinearMap.add_apply, hp, hq, eval_add, add_smul]
  | monomial k a =>
    rw [aeval_monomial, eval_monomial, Module.End.mul_apply, Module.algebraMap_end_apply]
    have hpow : ∀ j : ℕ, (D ^ j) w = c ^ j • w := by
      intro j
      induction j with
      | zero => simp
      | succ j ih => rw [pow_succ', Module.End.mul_apply, ih, map_smul, hw, smul_smul, ← pow_succ]
    rw [hpow, smul_smul]

/-- **The weight projections of an integral module** are elements of the associative algebra
generated by the action. -/
theorem IsIntegralGLModule.exists_proj (hM : IsIntegralGLModule K n M) :
    ∃ (S : Finset (Fin n → ℤ)) (P : (Fin n → ℤ) → Module.End K M),
      (∀ μ, P μ ∈ Algebra.adjoin K (Set.range (toEnd K (Matrix (Fin n) (Fin n) K) M))) ∧
      (∀ μ x, P μ x ∈ glWeightSpace K M μ) ∧ ∀ x, x = ∑ μ ∈ S, P μ x := by
  classical
  have := hM.finiteDimensional
  set S := (finite_glWeightSpace_ne_bot K M (n := n)).toFinset
  have hS : ∀ ν, ν ∉ S → glWeightSpace K M ν = ⊥ := fun ν hν => by
    by_contra h
    exact hν ((Set.Finite.mem_toFinset _).mpr h)
  let T : Fin n → Module.End K M := fun i => toEnd K (Matrix (Fin n) (Fin n) K) M (matUnit i i)
  -- the Lagrange polynomial of `c` among the `i`-th coordinates of the weights
  let lag : Fin n → K → K[X] := fun i c =>
    ∏ c' ∈ ((S.image fun ν => (ν i : K)).erase c), (c - c')⁻¹ • (X - C c')
  have hlag : ∀ i c d, d ∈ S.image (fun ν => (ν i : K)) →
      (lag i c).eval d = if d = c then 1 else 0 := by
    intro i c d hd
    simp only [lag, eval_prod, eval_smul, eval_sub, eval_X, eval_C, smul_eq_mul]
    split_ifs with hdc
    · subst hdc
      exact Finset.prod_eq_one fun c' hc' => inv_mul_cancel₀
        (sub_ne_zero.mpr (Finset.ne_of_mem_erase hc').symm)
    · exact Finset.prod_eq_zero (Finset.mem_erase.mpr ⟨hdc, hd⟩) (by rw [sub_self, mul_zero])
  let P : (Fin n → ℤ) → Module.End K M := fun μ =>
    (List.ofFn fun i => aeval (T i) (lag i (μ i : K))).prod
  have hPmem : ∀ μ, P μ ∈ Algebra.adjoin K (Set.range (toEnd K (Matrix (Fin n) (Fin n) K) M)) :=
    fun μ => Subalgebra.list_prod_mem _ fun x hx => by
      obtain ⟨i, rfl⟩ := List.mem_ofFn.mp hx
      exact Algebra.adjoin_mono (Set.singleton_subset_iff.mpr (Set.mem_range_self _))
        (Polynomial.aeval_mem_adjoin_singleton K _)
  -- the action of `P μ` on the weight space of `ν`
  have hP : ∀ μ ν w, w ∈ glWeightSpace K M ν → ν ∈ S →
      P μ w = (if ν = μ then 1 else 0 : K) • w := by
    intro μ ν w hw hν
    have hfac : ∀ i, aeval (T i) (lag i (μ i : K)) w =
        (if (ν i : K) = μ i then 1 else 0 : K) • w := by
      intro i
      rw [aeval_apply_of_eq_smul ((mem_glWeightSpace.mp hw) i),
        hlag i _ _ (Finset.mem_image_of_mem _ hν)]
    have hprod : ∀ (L : List (Fin n)), (L.map fun i => aeval (T i) (lag i (μ i : K))).prod w =
        (L.map fun i => (if (ν i : K) = μ i then 1 else 0 : K)).prod • w := by
      intro L
      induction L with
      | nil => simp
      | cons i L ih =>
        rw [List.map_cons, List.prod_cons, Module.End.mul_apply, ih, map_smul, hfac,
          List.map_cons, List.prod_cons, smul_smul, mul_comm]
    simp only [P]
    rw [List.ofFn_eq_map, hprod (List.finRange n)]
    congr 1
    by_cases hνμ : ν = μ
    · subst hνμ
      simp
    · obtain ⟨i, hi⟩ := Function.ne_iff.mp hνμ
      have hi' : ¬((ν i : K) = μ i) := fun h' => hi (Int.cast_injective h')
      simp only [hνμ, ↓reduceIte]
      exact List.prod_eq_zero (List.mem_map.mpr ⟨i, List.mem_finRange i, by simp [hi']⟩)
  refine ⟨S, P, hPmem, fun μ x => ?_, fun x => ?_⟩
  · have hx : x ∈ ⨆ ν, glWeightSpace K M ν := hM.iSup_eq_top ▸ Submodule.mem_top
    induction hx using Submodule.iSup_induction' with
    | mem ν w hw =>
      by_cases hν : ν ∈ S
      · rw [hP μ ν w hw hν]
        by_cases hνμ : ν = μ
        · subst hνμ
          simp only [↓reduceIte, one_smul]
          exact hw
        · simp only [hνμ, ↓reduceIte, zero_smul]
          exact zero_mem _
      · rw [hS ν hν, Submodule.mem_bot] at hw
        rw [hw, map_zero]
        exact zero_mem _
    | zero => rw [map_zero]; exact zero_mem _
    | add w w' _ _ hw hw' => rw [map_add]; exact add_mem hw hw'
  · have hx : x ∈ ⨆ ν, glWeightSpace K M ν := hM.iSup_eq_top ▸ Submodule.mem_top
    induction hx using Submodule.iSup_induction' with
    | mem ν w hw =>
      by_cases hν : ν ∈ S
      · rw [Finset.sum_congr rfl fun μ _ => hP μ ν w hw hν]
        simp [hν]
      · rw [hS ν hν, Submodule.mem_bot] at hw
        simp [hw]
    | zero => simp
    | add w w' _ _ hw hw' =>
      simp only [map_add, Finset.sum_add_distrib]
      rw [← hw, ← hw']

omit [CharZero K] in
/-- A Lie submodule is stable under the associative algebra generated by the action. -/
theorem apply_mem_lieSubmodule_of_mem_adjoin (N : LieSubmodule K (Matrix (Fin n) (Fin n) K) M)
    {f : Module.End K M}
    (hf : f ∈ Algebra.adjoin K (Set.range (toEnd K (Matrix (Fin n) (Fin n) K) M))) {x : M}
    (hx : x ∈ N) : f x ∈ N := by
  induction hf using Algebra.adjoin_induction generalizing x with
  | mem g hg =>
    obtain ⟨X, rfl⟩ := hg
    exact N.lie_mem hx
  | algebraMap c => rw [Module.algebraMap_end_apply]; exact N.smul_mem c hx
  | add f g _ _ hf hg => rw [LinearMap.add_apply]; exact add_mem (hf hx) (hg hx)
  | mul f g _ _ hf hg => rw [Module.End.mul_apply]; exact hf (hg hx)

omit [CharZero K] in
/-- The weight spaces of a Lie submodule are its intersections with those of the module. -/
theorem mem_glWeightSpace_lieSubmodule_iff {N : LieSubmodule K (Matrix (Fin n) (Fin n) K) M}
    {μ : Fin n → ℤ} {x : N} : x ∈ glWeightSpace K N μ ↔ (x : M) ∈ glWeightSpace K M μ := by
  simp only [mem_glWeightSpace]
  refine forall_congr' fun i => ?_
  rw [← Subtype.coe_inj, LieSubmodule.coe_bracket, LieSubmodule.coe_smul]

/-- **A Lie submodule of an integral module is integral.** -/
theorem IsIntegralGLModule.lieSubmodule (hM : IsIntegralGLModule K n M)
    (N : LieSubmodule K (Matrix (Fin n) (Fin n) K) M) : IsIntegralGLModule K n N := by
  have := hM.finiteDimensional
  refine ⟨inferInstance, top_le_iff.mp fun y _ => ?_⟩
  obtain ⟨S, P, hPmem, hPw, hsum⟩ := hM.exists_proj
  have hy : (y : M) = ∑ μ ∈ S, P μ y := hsum y
  have hcomp : ∀ μ, (⟨P μ y, apply_mem_lieSubmodule_of_mem_adjoin N (hPmem μ) y.2⟩ : N) ∈
      glWeightSpace K N μ := fun μ => mem_glWeightSpace_lieSubmodule_iff.mpr (hPw μ y)
  have hy' : y = ∑ μ ∈ S, (⟨P μ y, apply_mem_lieSubmodule_of_mem_adjoin N (hPmem μ) y.2⟩ : N) :=
    Subtype.ext (by rw [AddSubmonoidClass.coe_finsetSum]; exact hy)
  rw [hy']
  exact Submodule.sum_mem _ fun μ _ => Submodule.mem_iSup_of_mem μ (hcomp μ)

omit [CharZero K] in
/-- Lie module maps preserve weight spaces. -/
theorem LieModuleHom.map_mem_glWeightSpace {M' : Type*} [AddCommGroup M'] [Module K M']
    [LieRingModule (Matrix (Fin n) (Fin n) K) M'] [LieModule K (Matrix (Fin n) (Fin n) K) M']
    (f : M →ₗ⁅K, Matrix (Fin n) (Fin n) K⁆ M') {μ : Fin n → ℤ} {x : M}
    (hx : x ∈ glWeightSpace K M μ) : f x ∈ glWeightSpace K M' μ := by
  refine mem_glWeightSpace.mpr fun i => ?_
  rw [← LieModuleHom.map_lie, (mem_glWeightSpace.mp hx) i, map_smul]

/-- **The quotient of an integral module is integral**, and its weight spaces are the images of
the weight spaces of the module. -/
theorem IsIntegralGLModule.map_mk'_glWeightSpace (hM : IsIntegralGLModule K n M)
    (N : LieSubmodule K (Matrix (Fin n) (Fin n) K) M) (μ : Fin n → ℤ) :
    (glWeightSpace K M μ).map (LieSubmodule.Quotient.mk' N : M →ₗ[K] M ⧸ N) =
      glWeightSpace K (M ⧸ N) μ := by
  refine eq_of_le_of_iSup_eq_top
    (A := fun μ => (glWeightSpace K M μ).map (LieSubmodule.Quotient.mk' N : M →ₗ[K] M ⧸ N))
    (fun μ => ?_) ?_ (iSupIndep_glWeightSpace K (M ⧸ N)) μ
  · rintro _ ⟨x, hx, rfl⟩
    exact LieModuleHom.map_mem_glWeightSpace _ hx
  · rw [← Submodule.map_iSup, hM.iSup_eq_top, Submodule.map_top, LinearMap.range_eq_top]
    exact LieSubmodule.Quotient.surjective_mk' N

theorem IsIntegralGLModule.quotient (hM : IsIntegralGLModule K n M)
    (N : LieSubmodule K (Matrix (Fin n) (Fin n) K) M) : IsIntegralGLModule K n (M ⧸ N) := by
  have := hM.finiteDimensional
  refine ⟨inferInstance, ?_⟩
  simp_rw [← hM.map_mk'_glWeightSpace N]
  rw [← Submodule.map_iSup, hM.iSup_eq_top, Submodule.map_top, LinearMap.range_eq_top]
  exact LieSubmodule.Quotient.surjective_mk' N

/-- A nonzero integral module has a highest weight vector of integral weight. -/
theorem IsIntegralGLModule.exists_isGlHighestWeightVector (hM : IsIntegralGLModule K n M)
    [Nontrivial M] : ∃ (ν : Fin n → ℤ) (v : M), v ∈ glWeightSpace K M ν ∧
      TauCeti.IsGlHighestWeightVector (fun i => (ν i : K)) v := by
  have := hM.finiteDimensional
  obtain ⟨μ, hμ⟩ : ∃ μ : Fin n → ℤ, glWeightSpace K M μ ≠ ⊥ := by
    by_contra hall
    push Not at hall
    have htop := hM.iSup_eq_top
    simp only [hall, iSup_bot] at htop
    exact bot_ne_top htop
  exact GLRep.exists_isGlHighestWeightVector hμ

end

end GLRep
