import Schubert.FlagVarieties.Schubert.Basic

/-!
# Opposite Schubert varieties and Richardson varieties

Over a commutative ring `R`, in the style of `FlagVarieties.schubertVariety`:

* `FlagVarieties.oppBorelIdeal R n`: the ideal of the opposite Borel subgroup `B⁻ ⊆ GL_n` of lower
  triangular matrices, generated by the entries `x_ij` with `i < j`; `OppBorelCoord R n = 𝒪(B⁻)`
  and the scheme `OppBorelScheme R n = Spec 𝒪(B⁻)` with its closed immersion `oppBorelInclusion`.
* `FlagVarieties.oppSchubertOrbitMap R n w : B⁻ ⟶ Fl_n`, `b ↦ b · ẇE•`.
* **`FlagVarieties.oppositeSchubertVariety R n w`**: the opposite Schubert variety `X^w`, the
  scheme-theoretic image of `oppSchubertOrbitMap`, i.e. the closure of `B⁻ ẇ B / B`.
* **`FlagVarieties.richardsonVariety R n w v`**: the Richardson variety `X_w ∩ X^v`, the
  scheme-theoretic intersection (the supremum of the two ideal sheaves).

The point-level results (nonemptiness iff `v ≤ w`, torus-fixed points) are in
`Richardson/Points.lean`.
-/

noncomputable section

namespace FlagVarieties

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits
open Foundations Foundations.QuotientCharts

universe u

variable (R : Type u) [CommRing R] (n : ℕ)

/-! ### The opposite Borel subgroup scheme -/

/-- The ideal of the opposite Borel subgroup `B⁻ ⊆ GL_n` of lower triangular matrices: it is
generated by the entries of the generic matrix above the diagonal. -/
def oppBorelIdeal : Ideal (GLCoord R n) :=
  Ideal.span (Set.range fun p : {p : Fin n × Fin n // p.1 < p.2} => genericMatrix R n p.1.1 p.1.2)

/-- The coordinate ring `𝒪(B⁻) = 𝒪(GL_n) ⧸ oppBorelIdeal`. -/
abbrev OppBorelCoord : Type u :=
  GLCoord R n ⧸ oppBorelIdeal R n

/-- The opposite Borel subgroup scheme `B⁻ = Spec 𝒪(B⁻)`. -/
abbrev OppBorelScheme : Scheme.{u} :=
  Spec (CommRingCat.of (OppBorelCoord R n))

/-- The generic lower triangular matrix over `𝒪(B⁻)`. -/
def oppBorelMatrix : Matrix (Fin n) (Fin n) (OppBorelCoord R n) :=
  (genericMatrix R n).map (Ideal.Quotient.mk (oppBorelIdeal R n))

theorem oppBorelMatrix_blockTriangular :
    (oppBorelMatrix R n).BlockTriangular OrderDual.toDual := by
  intro i j hij
  simp only [oppBorelMatrix, Matrix.map_apply]
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span ⟨⟨(i, j), hij⟩, rfl⟩

/-- The closed immersion `B⁻ ⟶ GL_n`. -/
def oppBorelInclusion : OppBorelScheme R n ⟶ GLScheme R n :=
  Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk (oppBorelIdeal R n))) ≫
    (TauCeti.GeneralLinear.groupSchemeSpecIso R n).inv

/-! ### Opposite Schubert varieties -/

/-- The orbit morphism `B⁻ ⟶ Fl_n`, `b ↦ b · ẇE•`. -/
def oppSchubertOrbitMap (w : Equiv.Perm (Fin n)) : OppBorelScheme R n ⟶ FlagScheme R n :=
  oppBorelInclusion R n ≫ FlagScheme.orbitMapAt (permFlag R n w) (permFlag_toSpec R n w)

/-- **The opposite Schubert variety `X^w`**.

It is the scheme-theoretic image of the orbit morphism `B⁻ ⟶ Fl_n`, `b ↦ b · ẇE•`: the closure of
the `B⁻`-orbit `B⁻ ẇ B / B`, with its reduced structure when `R` is reduced. As an ideal sheaf on
`Fl_n`; the closed subscheme is `(oppositeSchubertVariety R n w).subscheme`. -/
def oppositeSchubertVariety (w : Equiv.Perm (Fin n)) : (FlagScheme R n).IdealSheafData :=
  (oppSchubertOrbitMap R n w).ker

/-- The scheme-theoretic union `X^S = ⋃_{w ∈ S} X^w` of opposite Schubert varieties. -/
def oppositeSchubertUnion (S : Finset (Equiv.Perm (Fin n))) : (FlagScheme R n).IdealSheafData :=
  ⨅ w ∈ S, oppositeSchubertVariety R n w

/-! ### Richardson varieties -/

/-- **The Richardson variety `X_w^v = X_w ∩ X^v`**.

It is the scheme-theoretic intersection of the Schubert variety `X_w` and the opposite Schubert
variety `X^v`: the closed subscheme cut out by the sum (supremum) of the two ideal sheaves. -/
def richardsonVariety (w v : Equiv.Perm (Fin n)) : (FlagScheme R n).IdealSheafData :=
  schubertVariety R n w ⊔ oppositeSchubertVariety R n v

theorem schubertVariety_le_richardsonVariety (w v : Equiv.Perm (Fin n)) :
    schubertVariety R n w ≤ richardsonVariety R n w v :=
  le_sup_left

theorem oppositeSchubertVariety_le_richardsonVariety (w v : Equiv.Perm (Fin n)) :
    oppositeSchubertVariety R n v ≤ richardsonVariety R n w v :=
  le_sup_right

end FlagVarieties
