import RSCounterexample.Demazure.Representation.TypeA
import Mathlib.Algebra.Lie.UniversalEnveloping
import Mathlib.LinearAlgebra.Quotient.Basic

/-!
# The Joseph–Polo presentation

`Enveloping n` is `U(𝔫⁺)` for the strictly upper triangular matrices and `rootOperator r` the image
of a positive root. The Joseph–Polo left ideal of `u` is generated by the powers
`rootOperator r ^ josephPoloExponent u r`; its quotient `PresentationQuotient u` is cyclic with
generator `presentationGenerator u`. Imposing only the exponent-one relations gives
`LinearPresentationQuotient u`, which surjects onto it (`linearToJosephPolo_surjective`).
-/

namespace Demazure.FlagModule

noncomputable section

/-- The actual enveloping algebra of strictly upper-triangular complex matrices. -/
abbrev Enveloping (n : ℕ) := UniversalEnvelopingAlgebra ℂ (upperNilpotent n)

/-- The image in `U(𝔫⁺)` of the root vector of a positive root. -/
def rootOperator {n : ℕ} (r : PositiveRoot n) : Enveloping n :=
  UniversalEnvelopingAlgebra.ι ℂ (rootVector r)

/-- `Nat.sub` implements the nonnegative part in the JP exponent. -/
def josephPoloExponent {n : ℕ} (u : Fin n → ℕ) (r : PositiveRoot n) : ℕ :=
  u r.val.2 - u r.val.1 + 1

/-- This is a LEFT ideal (a submodule for the left regular action), not a
commutative or two-sided ideal. Its generators contain no character data. -/
def josephPoloLeftIdeal {n : ℕ} (u : Fin n → ℕ) : Submodule (Enveloping n) (Enveloping n) :=
  Submodule.span (Enveloping n) (Set.range fun r : PositiveRoot n =>
    rootOperator r ^ josephPoloExponent u r)

/-- The cyclic module in the actual Joseph–Polo presentation. -/
abbrev PresentationQuotient {n : ℕ} (u : Fin n → ℕ) :=
  Enveloping n ⧸ josephPoloLeftIdeal u

/-- The generator of the presentation quotient: the class of `1`. -/
def presentationGenerator {n : ℕ} (u : Fin n → ℕ) : PresentationQuotient u :=
  Submodule.Quotient.mk 1

/-- Every quotient vector is obtained by applying the actual enveloping
algebra to its distinguished cyclic vector. -/
theorem presentation_is_cyclic {n : ℕ} (u : Fin n → ℕ)
    (v : PresentationQuotient u) : ∃ a : Enveloping n, a • presentationGenerator u = v := by
  obtain ⟨a, rfl⟩ := Submodule.Quotient.mk_surjective (josephPoloLeftIdeal u) v
  refine ⟨a, ?_⟩
  change a • (Submodule.Quotient.mk 1 : PresentationQuotient u) = Submodule.Quotient.mk a
  rw [← Submodule.Quotient.mk_smul]
  simp

theorem josephPolo_relation_zero {n : ℕ} (u : Fin n → ℕ) (r : PositiveRoot n) :
    (Submodule.Quotient.mk (rootOperator r ^ josephPoloExponent u r) : PresentationQuotient u) =
        0 := by
  rw [Submodule.Quotient.mk_eq_zero]
  exact Submodule.subset_span ⟨r, rfl⟩

theorem josephPolo_relation_kills_generator {n : ℕ} (u : Fin n → ℕ) (r : PositiveRoot n) :
    (rootOperator r ^ josephPoloExponent u r) • presentationGenerator u = 0 := by
  change (rootOperator r ^ josephPoloExponent u r) •
      (Submodule.Quotient.mk 1 : PresentationQuotient u) = 0
  rw [← Submodule.Quotient.mk_smul]
  simpa using josephPolo_relation_zero u r

/-- The linear-killing condition gives precisely exponent one. -/
theorem josephPoloExponent_eq_one {n : ℕ} (u : Fin n → ℕ) (r : PositiveRoot n)
    (h : u r.val.2 ≤ u r.val.1) : josephPoloExponent u r = 1 := by
  simp [josephPoloExponent, Nat.sub_eq_zero_of_le h]

theorem killing_root_kills_generator {n : ℕ} (u : Fin n → ℕ) (r : PositiveRoot n)
    (h : u r.val.2 ≤ u r.val.1) :
    rootOperator r • presentationGenerator u = 0 := by
  simpa [josephPoloExponent_eq_one u r h] using josephPolo_relation_kills_generator u r

/-- First impose only the exponent-one (linear-killing) root relations. -/
def linearLeftIdeal {n : ℕ} (u : Fin n → ℕ) :
    Submodule (Enveloping n) (Enveloping n) :=
  Submodule.span (Enveloping n) {a | ∃ r : PositiveRoot n,
    u r.val.2 ≤ u r.val.1 ∧ a = rootOperator r}

theorem linearLeftIdeal_le_josephPolo {n : ℕ} (u : Fin n → ℕ) :
    linearLeftIdeal u ≤ josephPoloLeftIdeal u := by
  apply Submodule.span_le.mpr
  rintro a ⟨r, hr, rfl⟩
  have hm : rootOperator r ^ josephPoloExponent u r ∈ josephPoloLeftIdeal u :=
    Submodule.subset_span ⟨r, rfl⟩
  simpa [josephPoloExponent_eq_one u r hr] using hm

/-- The quotient of `U(𝔫⁺)` by the left ideal generated by the root operators killed linearly by
`u`. -/
abbrev LinearPresentationQuotient {n : ℕ} (u : Fin n → ℕ) :=
  Enveloping n ⧸ linearLeftIdeal u

/-- The actual quotient-to-quotient map of the presentation argument. -/
def linearToJosephPolo {n : ℕ} (u : Fin n → ℕ) :
    LinearPresentationQuotient u →ₗ[Enveloping n] PresentationQuotient u :=
  (linearLeftIdeal u).mapQ (josephPoloLeftIdeal u) LinearMap.id (by
    simpa using linearLeftIdeal_le_josephPolo u)

@[simp] theorem linearToJosephPolo_mk {n : ℕ} (u : Fin n → ℕ) (a : Enveloping n) :
    linearToJosephPolo u (Submodule.Quotient.mk a) = Submodule.Quotient.mk a := rfl

theorem linearToJosephPolo_surjective {n : ℕ} (u : Fin n → ℕ) :
    Function.Surjective (linearToJosephPolo u) := by
  intro v
  obtain ⟨a, rfl⟩ := Submodule.Quotient.mk_surjective (josephPoloLeftIdeal u) v
  exact ⟨Submodule.Quotient.mk a, rfl⟩

end
end Demazure.FlagModule
