import RSCounterexample.GLRep.Polynomial.Functions
import RSCounterexample.GLRep.Polynomial.Representation
import RSCounterexample.GLRep.Torus.Weights
import RSCounterexample.GLRep.Torus.Character
import RSCounterexample.GLRep.Torus.Levi
import RSCounterexample.GLRep.Lie.Differential
import RSCounterexample.GLRep.Lie.Module
import RSCounterexample.GLRep.Lie.Integration
import RSCounterexample.GLRep.Weyl.Freudenthal
import RSCounterexample.GLRep.Weyl.WeylCharacter
import RSCounterexample.GLRep.Weyl.GroupCharacter
import RSCounterexample.GLRep.HighestWeight.Classification
import RSCounterexample.GLRep.HighestWeight.CompleteReducibility
import RSCounterexample.GLRep.HighestWeight.WeylModule
import RSCounterexample.GLRep.Multiplicity.GL
import RSCounterexample.GLRep.Levi.Multiplicity
import RSCounterexample.GLRep.Rational.Twist
import RSCounterexample.GLRep.Rational.Torus
import RSCounterexample.GLRep.Rational.GL
import RSCounterexample.GLRep.Rational.Levi

/-!
# Representations of `GL_n` and of Levi groups in characteristic zero

This library develops the representation theory of `GL_n(K)` and of the Levi groups
`L = ∏_p GL_{d_p}(K)` over a field `K` of characteristic zero, not necessarily algebraically
closed, from the definition of a polynomial representation to the expansion of characters in Schur
polynomials. It depends only on Mathlib and Tau Ceti. This file imports all of it and indexes the
main results; `RSCounterexample/GLRep/Audit.lean` prints the axioms they depend on.

## Polynomial representations

A representation is **polynomial** when it is finite-dimensional and its matrix coefficients are
polynomials in the matrix entries (`GLRep.HasCoeffsIn`, `GLRep.IsPolynomialRep`,
`GLRep.IsPolynomialLeviRep`); this does not depend on a basis (`GLRep.hasCoeffsIn_iff_toMatrix`).
The class is closed under subrepresentations, quotients, products, tensor products and restriction
(`GLRep.HasCoeffsIn.of_injective`, `GLRep.HasCoeffsIn.of_surjective`, `GLRep.HasCoeffsIn.prod`,
`GLRep.HasCoeffsIn.tprod`, `GLRep.HasCoeffsIn.piTensor`, `GLRep.HasCoeffsIn.comp`). Identities
between polynomial functions on `GL_n(K)` are identities of polynomials
(`GLRep.isZariskiDense_glCoord`).

## Weights and characters

* A polynomial representation of the split torus is the direct sum of its weight spaces, with
  weights in `ℕⁿ` (`GLRep.HasCoeffsIn.isInternal_torusWeightSpace`,
  `GLRep.HasCoeffsIn.torusWeightSpace_eq_bot`).
* The **character** `GLRep.character ρ = ∑_μ dim W_μ · x^μ` gives the traces on the torus and is
  determined by them (`GLRep.trace_diagGL_eq_eval_character`,
  `GLRep.eq_character_of_forall_trace_eq`); it is symmetric
  (`GLRep.IsPolynomialRep.character_isSymmetric`). For Levi groups: `GLRep.leviCharacter`,
  `GLRep.trace_leviTorus_eq_eval_leviCharacter`, `GLRep.leviCharacter_extTensor`.

## The Lie algebra

* The **differential** `dρ : gl_n(K) → End W` is defined over the dual numbers
  (`GLRep.IsPolynomialRep.lie`, `GLRep.IsPolynomialRep.extend_one_add_smul`).
* `ρ` and `dρ` generate the same algebra of operators (`GLRep.IsPolynomialRep.adjoin_range_eq`),
  so subrepresentations are `gl_n`-submodules and intertwining maps are `gl_n`-module maps
  (`GLRep.IsPolynomialRep.subrepOrderIso`, `GLRep.IsPolynomialRep.intertwiningEquivLieHom`).

## The Weyl character formula

* **Freudenthal's formula** and the root-string recursion, by traces on weight spaces
  (`GLRep.freudenthal`, `GLRep.stringTrace_sub_root`).
* **The Weyl character formula** `a_δ · ch M = a_{λ+δ}` for a `gl_n(K)`-module generated by a
  highest weight vector with symmetric character
  (`GLRep.alternant_mul_glCharacter_of_isGlHighestWeightVector`), and for polynomial
  representations `ch ρ = s_λ` (`GLRep.IsPolynomialRep.character_eq_diagramSchurPoly`).

## Highest weights, irreducibles and complete reducibility

* Every irreducible polynomial representation has a highest weight vector of a polynomial
  dominant weight (`GLRep.IsPolynomialRep.exists_highestWeight`), and irreducible polynomial
  representations with the same character are equivalent
  (`GLRep.IsPolynomialRep.nonempty_equiv_of_character_eq`).
* The irreducible polynomial representation `V(λ)` (`GLRep.irrep`), a Weyl module: it is
  irreducible (`GLRep.isIrreducible_irrep`) with character `s_λ` (`GLRep.character_irrep`), every
  irreducible polynomial representation is equivalent to exactly one `V(λ)`
  (`GLRep.IsPolynomialRep.exists_nonempty_equiv_irrep`, `GLRep.irrep_eq_of_nonempty_equiv`), and
  Schur's lemma holds (`GLRep.finrank_intertwiningMap_irrep_self`,
  `GLRep.finrank_intertwiningMap_irrep_of_ne`).
* **Complete reducibility**: integral `gl_n(K)`-modules and polynomial representations are
  semisimple (`GLRep.IsIntegralGLModule.complementedLattice`,
  `GLRep.IsPolynomialRep.isSemisimpleRepresentation`).

## Multiplicities

* `ch ρ = ∑_λ dim Hom(V(λ), ρ) · s_λ` for a polynomial representation `ρ` of `GL_n(K)`
  (`GLRep.multiplicity`, `GLRep.IsPolynomialRep.exists_character_eq_sum`).
* For the Levi group, with `⊠_p V(λ_p)` (`GLRep.leviIrrep`) of character `∏_p s_{λ_p}(x_{p,·})`
  (`GLRep.leviSchur`, `GLRep.leviCharacter_leviIrrep`):
  `ch ρ = ∑_λ dim Hom_L(⊠_p V(λ_p), ρ) · ∏_p s_{λ_p}(x_{p,·})`
  (`GLRep.leviMultiplicity`, `GLRep.IsPolynomialLeviRep.exists_leviCharacter_eq_sum`).

## Rational representations

* Twists by characters and by powers of the determinant (`GLRep.scaledRep`, `GLRep.detPow`,
  `GLRep.detZPow`, `GLRep.nonempty_equiv_scaledRep_irrep`).
* Laurent characters of rational representations of a torus (`GLRep.laurentCharacter`,
  `GLRep.IsRationalTorusRep.trace_eq_laurentEval`,
  `GLRep.IsRationalTorusRep.eq_laurentCharacter_of_forall`).
* Rational representations of `GL_n(K)` (`GLRep.IsRationalRep`) are semisimple
  (`GLRep.IsRationalRep.isSemisimpleRepresentation`). The irreducible ones are the `V(λ)`,
  `λ ∈ ℤⁿ` dominant (`GLRep.ratIrrep`, `GLRep.IsRationalRep.exists_nonempty_equiv_ratIrrep`,
  `GLRep.eq_of_nonempty_equiv_ratIrrep`), with characters the rational Schur polynomials
  (`GLRep.ratSchur`, `GLRep.ratCharacter_ratIrrep`), and
  `ch ρ = ∑_λ dim Hom(V(λ), ρ) · s_λ` (`GLRep.IsRationalRep.exists_ratCharacter_eq_sum`).
* Rational representations of Levi groups (`GLRep.IsRationalLeviRep`, `GLRep.ratLeviIrrep`,
  `GLRep.ratLeviSchur`, `GLRep.ratLeviCharacter_ratLeviIrrep`,
  `GLRep.IsRationalLeviRep.exists_ratLeviCharacter_eq_sum`).
-/
