import Schubert.GLRep.Borel.Generation
import Schubert.GLRep.Lie.Integration

/-!
# `B`-stability through the differential (restrictions of `GL_n`-representations)

Let `ρ` be a polynomial representation of `GL_n(K)`, `K` infinite of characteristic zero, with
differential `dρ` (`GLRep.IsPolynomialRep.lie`). A subspace `U` is stable under the Borel
subgroup `B` exactly when it is stable under the diagonal torus and under `dρ(E_ab)` for
`a < b` (`GLRep.IsPolynomialRep.forall_borel_mem_iff`): `B` is generated by the torus and the
upper transvections (`GLRep.borel_induction`), and `ρ(1 + tE_ab) = exp(t dρ(E_ab))`
(`GLRep.IsPolynomialRep.rho_lineGL_eq_exp`) whose coefficients are recovered from its values
(`GLRep.mem_of_forall_sum_pow_smul_mem`).

The same holds for rational representations, through a polynomial twist
(`GLRep.IsRationalRep.forall_borel_mem_iff`), and for linear maps between polynomial
representations (`GLRep.IsPolynomialRep.forall_borel_intertwining_iff`). This covers the
restrictions to `B` of rational representations of `GL_n`, among them `V(λ)`, its Demazure
modules and their duals.
-/

namespace GLRep

open Module Polynomial TauCeti

noncomputable section

variable {K : Type*} [Field K] {n : ℕ}
variable {W : Type*} [AddCommGroup W] [Module K W] {ρ : Representation K (GL (Fin n) K) W}

/-- **Coefficient extraction**: if `Σ_k t^k v_k ∈ U` for every `t` in an infinite field, every
`v_k` lies in `U`. -/
theorem mem_of_forall_sum_pow_smul_mem [Infinite K] (U : Submodule K W) {N : ℕ} (v : ℕ → W)
    (h : ∀ t : K, ∑ k ∈ Finset.range N, t ^ k • v k ∈ U) {k : ℕ} (hk : k < N) : v k ∈ U := by
  rw [← Submodule.Quotient.mk_eq_zero]
  refine (Module.forall_dual_apply_eq_zero_iff K _).mp fun f => ?_
  let q : K[X] := ∑ j ∈ Finset.range N, monomial j (f (U.mkQ (v j)))
  have hq : q = 0 := by
    refine Polynomial.eq_zero_of_infinite_isRoot q (Set.infinite_univ.mono fun t _ => ?_)
    have h0 : f (U.mkQ (∑ j ∈ Finset.range N, t ^ j • v j)) = 0 := by
      rw [Submodule.mkQ_apply, (Submodule.Quotient.mk_eq_zero U).mpr (h t), map_zero]
    rw [map_sum, map_sum] at h0
    simp only [map_smul, smul_eq_mul] at h0
    simp only [Set.mem_ofPred_eq, IsRoot, q, eval_finsetSum, eval_monomial]
    rw [← h0]
    exact Finset.sum_congr rfl fun j _ => mul_comm _ _
  have h1 := congrArg (coeff · k) hq
  simp only [q, finsetSum_coeff, coeff_monomial, Finset.sum_ite_eq', Finset.mem_range, hk,
    ite_true, coeff_zero] at h1
  exact h1

namespace IsPolynomialRep

variable (h : IsPolynomialRep ρ) [Infinite K] [CharZero K]

omit [Infinite K] [CharZero K] in
theorem single_mul_single_self {a b : Fin n} (hab : a ≠ b) :
    Matrix.single a b (1 : K) * Matrix.single a b 1 = 0 :=
  GLRep.single_mul_single_of_ne hab

/-- The transvection `1 + tE_ab` acts by `Σ_k t^k/k! dρ(E_ab)^k`. -/
theorem rho_transvectionGL_eq {a b : Fin n} (hab : a ≠ b) (t : K) :
    ρ (transvectionGL hab t) = ∑ k ∈ Finset.range (h.curveDegree (Matrix.single a b 1) + 2),
      (t ^ k * (k.factorial : K)⁻¹) • h.lie (Matrix.single a b 1) ^ k :=
  h.rho_lineGL_eq_exp (single_mul_single_self hab) t (by omega)

/-- A subspace stable under the transvections `1 + tE_ab` is stable under `dρ(E_ab)`. -/
theorem lie_mem_of_forall_transvectionGL {a b : Fin n} (hab : a ≠ b) (U : Submodule K W)
    (hU : ∀ t, ∀ u ∈ U, ρ (transvectionGL hab t) u ∈ U) :
    ∀ u ∈ U, h.lie (Matrix.single a b 1) u ∈ U := by
  intro u hu
  have key := mem_of_forall_sum_pow_smul_mem U
    (N := h.curveDegree (Matrix.single a b 1) + 2)
    (fun k => ((k.factorial : K)⁻¹) • (h.lie (Matrix.single a b 1) ^ k) u)
    (fun t => by
      have := hU t u hu
      rw [h.rho_transvectionGL_eq hab t, LinearMap.sum_apply] at this
      convert this using 2 with k
      rw [LinearMap.smul_apply, smul_smul])
    (k := 1) (by omega)
  simpa using key

/-- A subspace stable under `dρ(E_ab)` is stable under the transvections `1 + tE_ab`. -/
theorem transvectionGL_mem_of_lie {a b : Fin n} (hab : a ≠ b) (U : Submodule K W)
    (hU : ∀ u ∈ U, h.lie (Matrix.single a b 1) u ∈ U) (t : K) :
    ∀ u ∈ U, ρ (transvectionGL hab t) u ∈ U := by
  intro u hu
  have hpow : ∀ k, ∀ u ∈ U, (h.lie (Matrix.single a b 1) ^ k) u ∈ U := by
    intro k
    induction k with
    | zero => intro u hu; simpa using hu
    | succ k ih =>
      intro u hu
      rw [pow_succ, Module.End.mul_apply]
      exact ih _ (hU u hu)
  rw [h.rho_transvectionGL_eq hab t, LinearMap.sum_apply]
  exact Submodule.sum_mem _ fun k _ => Submodule.smul_mem _ _ (hpow k u hu)

/-- **The differential criterion for subspaces**: `U` is `B`-stable iff it is stable under the
diagonal torus and under `dρ(E_ab)` for `a < b`. -/
theorem forall_borel_mem_iff (U : Submodule K W) :
    (∀ g ∈ borel K n, ∀ u ∈ U, ρ g u ∈ U) ↔
      (∀ t, ∀ u ∈ U, ρ (diagGL t) u ∈ U) ∧
        ∀ a b : Fin n, a < b → ∀ u ∈ U, h.lie (Matrix.single a b 1) u ∈ U := by
  constructor
  · intro hB
    refine ⟨fun t => hB _ (borelTorus K n t).2, fun a b hab => ?_⟩
    exact h.lie_mem_of_forall_transvectionGL hab.ne U fun t =>
      hB _ (transvectionGL_mem_borel hab t)
  · rintro ⟨hT, hL⟩ g hg
    refine borel_induction (P := fun g => ∀ u ∈ U, ρ g u ∈ U) ?_ ?_ hT hg
    · intro g g' hg hg' u hu
      rw [map_mul, Module.End.mul_apply]
      exact hg _ (hg' u hu)
    · intro a b hab t
      exact h.transvectionGL_mem_of_lie hab.ne U (hL a b hab) t

variable {V : Type*} [AddCommGroup V] [Module K V] {σ : Representation K (GL (Fin n) K) V}

/-- **The differential criterion for maps**: a linear map between polynomial representations
commutes with `B` iff it commutes with the diagonal torus and with `dρ(E_ab)`, `a < b`. -/
theorem forall_borel_intertwining_iff (hσ : IsPolynomialRep σ) (f : W →ₗ[K] V) :
    (∀ g ∈ borel K n, ∀ w, f (ρ g w) = σ g (f w)) ↔
      (∀ t w, f (ρ (diagGL t) w) = σ (diagGL t) (f w)) ∧
        ∀ a b : Fin n, a < b → ∀ w,
          f (h.lie (Matrix.single a b 1) w) = hσ.lie (Matrix.single a b 1) (f w) := by
  have hgraph : ∀ (T : Module.End K W) (T' : Module.End K V), (∀ w, f (T w) = T' (f w)) ↔
      ∀ u ∈ f.graph, T.prodMap T' u ∈ f.graph := fun T T' =>
    (prodMap_mem_graph_iff f T T').symm
  have key := IsPolynomialRep.forall_borel_mem_iff (h.prod hσ) f.graph
  constructor
  · intro hB
    obtain ⟨hT, hL⟩ := key.mp fun g hg => (hgraph (ρ g) (σ g)).mp (hB g hg)
    refine ⟨fun t => (hgraph _ _).mpr (hT t), fun a b hab => (hgraph _ _).mpr ?_⟩
    have := hL a b hab
    rwa [lie_prod h hσ] at this
  · rintro ⟨hT, hL⟩ g hg
    refine (hgraph (ρ g) (σ g)).mpr (key.mpr ⟨fun t => (hgraph _ _).mp (hT t),
      fun a b hab => ?_⟩ g hg)
    rw [lie_prod h hσ]
    exact (hgraph _ _).mp (hL a b hab)

end IsPolynomialRep

/-- **The differential criterion for rational representations**: through the polynomial twist
`ρ ⊗ det^k`, a subspace is `B`-stable iff it is stable under the torus and under `dρ(E_ab)`,
`a < b`. -/
theorem IsRationalRep.forall_borel_mem_iff [Infinite K] [CharZero K] (hρ : IsRationalRep ρ)
    (U : Submodule K W) :
    (∀ g ∈ borel K n, ∀ u ∈ U, ρ g u ∈ U) ↔
      (∀ t, ∀ u ∈ U, ρ (diagGL t) u ∈ U) ∧
        ∀ a b : Fin n, a < b → ∀ u ∈ U, hρ.choose_spec.lie (Matrix.single a b 1) u ∈ U := by
  have htw : ∀ g, (∀ u ∈ U, ρ g u ∈ U) ↔
      ∀ u ∈ U, scaledRep ρ (detPow K n hρ.choose) g u ∈ U := by
    intro g
    refine forall₂_congr fun u _ => ?_
    rw [scaledRep_apply]
    exact (Submodule.smul_mem_iff U (Units.ne_zero _)).symm
  rw [show (∀ g ∈ borel K n, ∀ u ∈ U, ρ g u ∈ U) ↔
      ∀ g ∈ borel K n, ∀ u ∈ U, scaledRep ρ (detPow K n hρ.choose) g u ∈ U from
    forall₂_congr fun g _ => htw g, hρ.choose_spec.forall_borel_mem_iff U]
  exact and_congr_left' (forall_congr' fun t => (htw (diagGL t)).symm)

end

end GLRep
