import Schubert.GLRep.Borel.Vanishing

/-!
# Generators of the Borel subgroup

`B` is generated by the diagonal torus and the upper transvections `1 + t E_ab`, `a < b`
(`GLRep.borel_induction`): an element of `B` is a diagonal matrix times a unipotent one, and a
unipotent upper triangular matrix `u ≠ 1` becomes simpler after multiplication by a transvection
clearing the entry `(i, j)` where `j` is the first column with a nonzero entry above the diagonal
(column `i` of `u` is then `e_i`, so nothing else changes).
-/

namespace GLRep

open Matrix TauCeti

noncomputable section

variable {K : Type*} [Field K] {n : ℕ}

/-- The positions above the diagonal where `M` is nonzero. -/
def upperSupport (M : Matrix (Fin n) (Fin n) K) : Finset (Fin n × Fin n) := by
  classical exact Finset.univ.filter fun p => p.1 < p.2 ∧ M p.1 p.2 ≠ 0

theorem mem_upperSupport {M : Matrix (Fin n) (Fin n) K} {p : Fin n × Fin n} :
    p ∈ upperSupport M ↔ p.1 < p.2 ∧ M p.1 p.2 ≠ 0 := by
  classical
  simp [upperSupport]

/-- A unipotent upper triangular matrix with no entries above the diagonal is `1`. -/
theorem eq_one_of_upperSupport_eq_empty {u : GL (Fin n) K} (hu : u ∈ borel K n)
    (hdiag : ∀ i, (u : Matrix (Fin n) (Fin n) K) i i = 1)
    (h : upperSupport (u : Matrix (Fin n) (Fin n) K) = ∅) : u = 1 := by
  refine Units.ext (Matrix.ext fun a b => ?_)
  rw [Units.val_one]
  rcases lt_trichotomy a b with hab | rfl | hab
  · rw [Matrix.one_apply_ne hab.ne]
    by_contra hne
    have : (a, b) ∈ upperSupport (u : Matrix (Fin n) (Fin n) K) := mem_upperSupport.mpr ⟨hab, hne⟩
    rw [h] at this
    exact Finset.notMem_empty _ this
  · rw [Matrix.one_apply_eq, hdiag]
  · rw [Matrix.one_apply_ne hab.ne']
    exact hu hab

theorem mul_transvection_apply (M : Matrix (Fin n) (Fin n) K) (i j : Fin n) (c : K)
    (a b : Fin n) :
    (M * transvection i j c) a b = M a b + if b = j then M a i * c else 0 := by
  rw [transvection, Matrix.mul_add, Matrix.mul_one, Matrix.add_apply]
  congr 1
  split_ifs with hb
  · subst hb
    simp
  · simp [hb]

/-- **The unipotent elements of `B` are products of upper transvections.** -/
theorem unipotent_induction {P : GL (Fin n) K → Prop} (hmul : ∀ g h, P g → P h → P (g * h))
    (htv : ∀ {a b : Fin n} (hab : a < b) (t : K), P (transvectionGL hab.ne t)) (hone : P 1) :
    ∀ (N : ℕ) (u : GL (Fin n) K), u ∈ borel K n → (∀ i, (u : Matrix (Fin n) (Fin n) K) i i = 1) →
      (upperSupport (u : Matrix (Fin n) (Fin n) K)).card = N → P u := by
  intro N
  induction N with
  | zero =>
    intro u hu hdiag hN
    rw [eq_one_of_upperSupport_eq_empty hu hdiag (Finset.card_eq_zero.mp hN)]
    exact hone
  | succ N ih =>
    intro u hu hdiag hN
    -- the first column with a nonzero entry above the diagonal
    have hne : (upperSupport (u : Matrix (Fin n) (Fin n) K)).Nonempty :=
      Finset.card_pos.mp (by omega)
    let cols : Finset (Fin n) := (upperSupport (u : Matrix (Fin n) (Fin n) K)).image Prod.snd
    have hcols : cols.Nonempty := hne.image _
    obtain ⟨⟨i, j⟩, hij, hjmin⟩ := Finset.mem_image.mp (cols.min'_mem hcols)
    have hjmin' : j = cols.min' hcols := hjmin
    obtain ⟨hlt', hMij⟩ := mem_upperSupport.mp hij
    have hlt : i < j := hlt'
    -- column `i` of `u` is `e_i`
    have hcol : ∀ a, (u : Matrix (Fin n) (Fin n) K) a i = if a = i then 1 else 0 := by
      intro a
      split_ifs with ha
      · rw [ha]
        exact hdiag i
      · rcases lt_or_gt_of_ne ha with h | h
        · by_contra hM
          have hmem : i ∈ cols :=
            Finset.mem_image.mpr ⟨(a, i), mem_upperSupport.mpr ⟨h, hM⟩, rfl⟩
          have := cols.min'_le i hmem
          rw [← hjmin'] at this
          exact absurd hlt (not_lt.mpr this)
        · exact hu h
    set c := (u : Matrix (Fin n) (Fin n) K) i j with hc
    let u' : GL (Fin n) K := u * transvectionGL hlt.ne (-c)
    have hM' : ∀ a b, (u' : Matrix (Fin n) (Fin n) K) a b =
        if a = i ∧ b = j then 0 else (u : Matrix (Fin n) (Fin n) K) a b := by
      intro a b
      change ((u : Matrix (Fin n) (Fin n) K) * (transvectionGL hlt.ne (-c) : GL (Fin n) K)) a b = _
      rw [coe_transvectionGL, mul_transvection_apply, hcol]
      by_cases hb : b = j
      · by_cases ha : a = i
        · subst ha
          subst hb
          simp [hc]
        · simp [ha]
      · simp [hb]
    have hu' : u' ∈ borel K n := mul_mem hu (transvectionGL_mem_borel hlt _)
    have hdiag' : ∀ k, (u' : Matrix (Fin n) (Fin n) K) k k = 1 := by
      intro k
      rw [hM', ite_eq_right_iff.mpr fun h => absurd (h.1.symm.trans h.2) hlt.ne, hdiag]
    have hsupp : upperSupport (u' : Matrix (Fin n) (Fin n) K) =
        (upperSupport (u : Matrix (Fin n) (Fin n) K)).erase (i, j) := by
      ext ⟨a, b⟩
      rw [Finset.mem_erase, mem_upperSupport, mem_upperSupport, hM']
      by_cases h : a = i ∧ b = j
      · obtain ⟨rfl, rfl⟩ := h
        simp
      · rw [ite_eq_right_iff.mpr fun h' => absurd h' h]
        simp only [ne_eq, Prod.mk.injEq]
        tauto
    have hcard : (upperSupport (u' : Matrix (Fin n) (Fin n) K)).card = N := by
      rw [hsupp, Finset.card_erase_of_mem hij]
      omega
    have hu'P := ih u' hu' hdiag' hcard
    have : u = u' * transvectionGL hlt.ne c := by
      refine Units.ext ?_
      rw [Units.val_mul, Units.val_mul, mul_assoc, coe_transvectionGL, coe_transvectionGL,
        transvection_mul_transvection_same (h := hlt.ne), neg_add_cancel, transvection_zero,
        mul_one]
    rw [this]
    exact hmul _ _ hu'P (htv hlt c)

/-- **`B` is generated by the diagonal torus and the upper transvections.** -/
theorem borel_induction {P : GL (Fin n) K → Prop} (hmul : ∀ g h, P g → P h → P (g * h))
    (htv : ∀ {a b : Fin n} (hab : a < b) (t : K), P (transvectionGL hab.ne t))
    (hdiag : ∀ t, P (diagGL t)) {g : GL (Fin n) K} (hg : g ∈ borel K n) : P g := by
  have hone : P 1 := by simpa using hdiag 1
  let b : borel K n := ⟨g, hg⟩
  let d := borelDiag K n b
  let u : borel K n := (borelTorus K n d)⁻¹ * b
  have hud : borelDiag K n u = 1 := by
    simp only [u, map_mul, map_inv, borelDiag_borelTorus, inv_mul_cancel, d]
  have hdiagu : ∀ i, ((u : GL (Fin n) K) : Matrix (Fin n) (Fin n) K) i i = 1 := by
    intro i
    rw [← borelDiag_apply_val, hud, Pi.one_apply, Units.val_one]
  have hPu : P u := unipotent_induction hmul htv hone _ u u.2 hdiagu rfl
  have hg' : g = diagGL d * (u : GL (Fin n) K) := by
    change (b : GL (Fin n) K) = ((borelTorus K n d : borel K n) : GL (Fin n) K) * _
    rw [← Subgroup.coe_mul, mul_inv_cancel_left]
  rw [hg']
  exact hmul _ _ (hdiag d) hPu

end

end GLRep
