import Schubert.GLRep.Lie.Exponential
import Schubert.GLRep.Torus.Character
import Mathlib.LinearAlgebra.Matrix.Transvection
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.RingTheory.Adjoin.Basic
import Mathlib.RingTheory.Adjoin.Polynomial.Basic

/-!
# Integration: the group and its Lie algebra act through the same operators

Let `ρ` be a polynomial representation of `GL_n(K)`, `K` a field of characteristic zero, with
differential `dρ`. This file proves that `ρ` and `dρ` generate the same algebra of operators:
`Algebra.adjoin K (range ρ) = Algebra.adjoin K (range dρ)`
(`GLRep.IsPolynomialRep.adjoin_range_eq`). Both inclusions are explicit.

* `dρ(X)` is the linear coefficient of the polynomial `t ↦ ρ(1 + tX)`, so it lies in the span of
  the values `ρ(1 + tX)` at the infinitely many `t` where `1 + tX` is invertible
  (`GLRep.IsPolynomialRep.lie_mem_span_range`).
* Conversely, transvections act by exponentials of `dρ(E_ab)`
  (`GLRep.IsPolynomialRep.rho_lineGL_eq_exp`). An invertible diagonal matrix acts on each weight
  space by a scalar, and the projections to the weight spaces are Lagrange polynomials in the
  commuting operators `dρ(E_ii)`. Every invertible matrix is a product of transvections and a
  diagonal matrix (`GLRep.gl_induction`).

Consequently, subrepresentations are the subspaces stable under `dρ`
(`GLRep.IsPolynomialRep.forall_rho_mem_iff`), and intertwining maps between polynomial
representations are the maps intertwining the differentials
(`GLRep.IsPolynomialRep.isIntertwining_iff_lie`).

## Main results

* `GLRep.IsPolynomialRep.lie_apply_of_mem_weightSpace`: `dρ(E_ii)` acts on the weight space of
  `μ` by `μ_i`.
* `GLRep.IsPolynomialRep.map_lie_apply`: intertwining maps intertwine the differentials.
* `GLRep.IsPolynomialRep.lie_prod`: the differential of a product.
* `GLRep.IsPolynomialRep.adjoin_range_eq`.
* `GLRep.IsPolynomialRep.forall_rho_mem_iff`, `GLRep.IsPolynomialRep.isIntertwining_iff_lie`.
-/

namespace GLRep

open Module Polynomial TauCeti

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

variable {K : Type*} [Field K] {n : ℕ}

/-! ### Generating `GL_n(K)` -/

section Generation

theorem single_mul_single_of_ne {a b : Fin n} (hab : a ≠ b) :
    (Matrix.single a b (1 : K)) * Matrix.single a b 1 = 0 := by
  rw [Matrix.single_mul_single_of_ne (h := Ne.symm hab)]

/-- The transvection `1 + t E_ab`, `a ≠ b`, as an element of `GL_n(K)`. -/
def transvectionGL {a b : Fin n} (hab : a ≠ b) (t : K) : GL (Fin n) K :=
  lineGL (Matrix.single a b 1) t (det_one_add_smul_of_sq_eq_zero (single_mul_single_of_ne hab) t)

/-- **`GL_n(K)` is generated by transvections and invertible diagonal matrices**: a property of
invertible matrices that holds for transvections and invertible diagonal matrices and is closed
under products holds for every invertible matrix. -/
theorem gl_induction {P : GL (Fin n) K → Prop} (hmul : ∀ g h, P g → P h → P (g * h))
    (htv : ∀ {a b : Fin n} (hab : a ≠ b) (t : K), P (transvectionGL hab t))
    (hdiag : ∀ t, P (diagGL t)) (g : GL (Fin n) K) : P g := by
  classical
  obtain ⟨L, L', D, hg⟩ :=
    Matrix.Pivot.exists_list_transvec_mul_diagonal_mul_list_transvec (g : Matrix (Fin n) (Fin n) K)
  have hdet : ∀ L : List (Matrix.TransvectionStruct (Fin n) K),
      (L.map Matrix.TransvectionStruct.toMatrix).prod.det = 1 :=
    Matrix.TransvectionStruct.det_toMatrix_prod
  have hD : ∀ i, D i ≠ 0 := by
    intro i hi
    have h : IsUnit (g : Matrix (Fin n) (Fin n) K).det :=
      (Matrix.isUnit_iff_isUnit_det _).mp g.isUnit
    rw [hg, Matrix.det_mul, Matrix.det_mul, hdet, hdet, one_mul, mul_one,
      Matrix.det_diagonal] at h
    exact h.ne_zero (Finset.prod_eq_zero (Finset.mem_univ i) hi)
  let tv : Matrix.TransvectionStruct (Fin n) K → GL (Fin n) K := fun s => transvectionGL s.hij s.c
  have htv_val : ∀ s, (tv s : Matrix (Fin n) (Fin n) K) = s.toMatrix := by
    intro s
    change 1 + s.c • Matrix.single s.i s.j 1 = Matrix.transvection s.i s.j s.c
    rw [Matrix.transvection, Matrix.smul_single, smul_eq_mul, mul_one]
  have hprod : ∀ L : List (Matrix.TransvectionStruct (Fin n) K),
      (((L.map tv).prod : GL (Fin n) K) : Matrix (Fin n) (Fin n) K) =
        (L.map Matrix.TransvectionStruct.toMatrix).prod := by
    intro L
    induction L with
    | nil => simp
    | cons s L ih =>
      rw [List.map_cons, List.prod_cons, Units.val_mul, ih, htv_val, List.map_cons, List.prod_cons]
  have hPL : ∀ L : List (Matrix.TransvectionStruct (Fin n) K), L ≠ [] → P (L.map tv).prod := by
    intro L
    induction L with
    | nil => exact fun h => absurd rfl h
    | cons s L ih =>
      intro _
      rw [List.map_cons, List.prod_cons]
      rcases eq_or_ne L [] with rfl | hL
      · simpa using htv s.hij s.c
      · exact hmul _ _ (htv s.hij s.c) (ih hL)
  let t : Fin n → Kˣ := fun i => Units.mk0 (D i) (hD i)
  have hg' : g = (L.map tv).prod * diagGL t * (L'.map tv).prod := by
    apply Units.ext
    rw [Units.val_mul, Units.val_mul, hprod, hprod, hg, diagGL_coe]
    rfl
  -- an empty product is the identity, the diagonal matrix with entries `1`
  have hone : P 1 := by simpa using hdiag 1
  have hPL' : ∀ L : List (Matrix.TransvectionStruct (Fin n) K), P (L.map tv).prod := fun L => by
    rcases eq_or_ne L [] with rfl | hL
    · simpa using hone
    · exact hPL L hL
  rw [hg']
  exact hmul _ _ (hmul _ _ (hPL' L) (hdiag t)) (hPL' L')

end Generation

variable {W : Type*} [AddCommGroup W] [Module K W] {ρ : Representation K (GL (Fin n) K) W}
variable {V : Type*} [AddCommGroup V] [Module K V] {σ : Representation K (GL (Fin n) K) V}

namespace IsPolynomialRep

variable [Infinite K]

/-! ### Computing differentials -/

/-- **Intertwining maps intertwine the differentials.** -/
theorem map_lie_apply (hρ : IsPolynomialRep ρ) (hσ : IsPolynomialRep σ)
    (φ : ρ.IntertwiningMap σ) (X : Matrix (Fin n) (Fin n) K) (w : W) :
    φ (hρ.lie X w) = hσ.lie X (φ w) := by
  have hN : 1 < max (hρ.curveDegree X) (hσ.curveDegree X) + 2 := by omega
  rw [hσ.lie_apply_eq_of_forall X (φ w) hN (fun k => φ (hρ.curveCoeff X k w)) fun t ht => by
      rw [← φ.isIntertwining, hρ.rho_lineGL_eq_sum X t ht (N := max (hρ.curveDegree X)
        (hσ.curveDegree X) + 2) (by omega)]
      simp [map_sum],
    hρ.curveCoeff_one]

/-- **The differential of a product** is the product of the differentials. -/
theorem lie_prod (hρ : IsPolynomialRep ρ) (hσ : IsPolynomialRep σ)
    (X : Matrix (Fin n) (Fin n) K) :
    IsPolynomialRep.lie (hρ.prod hσ) X = (hρ.lie X).prodMap (hσ.lie X) := by
  refine LinearMap.ext fun ⟨w, v⟩ => ?_
  have hN : 1 < max (hρ.curveDegree X) (hσ.curveDegree X) + 2 := by omega
  rw [IsPolynomialRep.lie_apply_eq_of_forall (hρ.prod hσ) X (w, v) hN
    (fun k => (hρ.curveCoeff X k w, hσ.curveCoeff X k v)) fun t ht => by
      change (ρ (lineGL X t ht) w, σ (lineGL X t ht) v) = _
      rw [hρ.rho_lineGL_eq_sum X t ht (N := max (hρ.curveDegree X) (hσ.curveDegree X) + 2)
        (by omega), hσ.rho_lineGL_eq_sum X t ht
        (N := max (hρ.curveDegree X) (hσ.curveDegree X) + 2) (by omega)]
      ext <;> simp [Prod.fst_sum, Prod.snd_sum]]
  simp [hρ.curveCoeff_one, hσ.curveCoeff_one]

/-- On the weight space of `μ`, `dρ(E_ii)` acts by `μ_i`. -/
theorem lie_apply_of_mem_weightSpace (h : IsPolynomialRep ρ) {μ : Fin n → ℤ} {w : W}
    (hw : w ∈ weightSpace ρ μ) (i : Fin n) :
    h.lie (Matrix.single i i 1) w = (μ i : K) • w := by
  classical
  by_cases hneg : ∃ j, μ j < 0
  · rw [weightSpace, h.comp_diagGL.torusWeightSpace_eq_bot hneg, Submodule.mem_bot] at hw
    simp [hw]
  push Not at hneg
  set m := (μ i).toNat with hm_def
  have hm : (μ i : K) = m := by
    rw [hm_def, ← Int.cast_natCast, Int.toNat_of_nonneg (hneg i)]
  have hN : 1 < m + 2 := by omega
  rw [h.lie_apply_eq_of_forall (Matrix.single i i 1) w hN (fun k => (m.choose k : K) • w)
    fun t ht => ?_]
  · simp [hm]
  -- `1 + t E_ii` is the diagonal matrix `diag(1, …, 1 + t, …, 1)`
  have hdiag : (1 : Matrix (Fin n) (Fin n) K) + t • Matrix.single i i 1 =
      Matrix.diagonal (Function.update 1 i (1 + t)) := by
    refine Matrix.ext fun a b => ?_
    by_cases hab : a = b
    · subst hab
      by_cases hai : a = i
      · subst hai
        simp
      · simp [hai, Ne.symm hai]
    · simp only [Matrix.add_apply, Matrix.diagonal_apply_ne _ hab, Matrix.one_apply_ne hab,
        Matrix.smul_apply, Matrix.single_apply, smul_eq_mul]
      split_ifs with h1
      · exact absurd (h1.1.symm.trans h1.2) hab
      · simp
  have ht' : 1 + t ≠ 0 := by
    have := ht
    rw [hdiag, Matrix.det_diagonal] at this
    intro h0
    apply this
    exact Finset.prod_eq_zero (Finset.mem_univ i) (by simp [h0])
  set u : Kˣ := Units.mk0 (1 + t) ht'
  have hGL : lineGL (Matrix.single i i 1) t ht = diagGL (Function.update 1 i u) := by
    apply Units.ext
    rw [coe_lineGL, hdiag, diagGL_coe]
    congr 1
    funext j
    by_cases hj : j = i
    · subst hj
      simp [u]
    · simp [Function.update_of_ne hj]
  have hchar : weightCharHom K μ (Function.update 1 i u) = (1 + t) ^ m := by
    rw [weightCharHom_apply, weightChar_apply, torusCharacter_def, Units.coe_prod,
      Finset.prod_eq_single i]
    · rw [Function.update_self, Units.val_zpow_eq_zpow_val, ← Int.toNat_of_nonneg (hneg i),
        zpow_natCast]
      rfl
    · intro j _ hj
      rw [Function.update_of_ne hj, Pi.one_apply, one_zpow, Units.val_one]
    · simp
  rw [hGL]
  change (ρ.comp diagGL) _ w = _
  rw [apply_of_mem_torusWeightSpace hw, hchar, add_comm, add_pow, Finset.sum_smul,
    Finset.sum_range_succ _ (m + 1), Nat.choose_succ_self, Nat.cast_zero, zero_smul, smul_zero,
    add_zero]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [one_pow, mul_one, smul_smul, mul_comm]

/-! ### The two algebras of operators -/

/-- **The differential lies in the span of the group action**: `dρ(X)` is the linear coefficient
of the polynomial `t ↦ ρ(1 + tX)`, which takes values in the span of `ρ(GL_n(K))` at infinitely
many points. -/
theorem lie_mem_span_range (h : IsPolynomialRep ρ) (X : Matrix (Fin n) (Fin n) K) :
    h.lie X ∈ Submodule.span K (Set.range ρ) := by
  by_contra hX
  obtain ⟨f, hf, hfp⟩ := Submodule.exists_dual_map_eq_bot_of_notMem hX inferInstance
  set N := h.curveDegree X + 2
  let q : K[X] := ∑ k ∈ Finset.range N, monomial k (f (h.curveCoeff X k))
  have hq : q = 0 := by
    refine Polynomial.eq_zero_of_infinite_isRoot q
      ((infinite_setOf_det_ne_zero X).mono fun t ht => ?_)
    have hmem : ρ (lineGL X t ht) ∈ Submodule.span K (Set.range ρ) :=
      Submodule.subset_span ⟨_, rfl⟩
    have h0 : f (ρ (lineGL X t ht)) = 0 := by
      have := Submodule.mem_map_of_mem (f := f) hmem
      rw [hfp, Submodule.mem_bot] at this
      exact this
    rw [h.rho_lineGL_eq_sum X t ht (N := N) (by omega), map_sum] at h0
    simp only [map_smul, smul_eq_mul] at h0
    simp only [Set.mem_ofPred_eq, IsRoot, q, eval_finsetSum, eval_monomial]
    rw [← h0]
    exact Finset.sum_congr rfl fun k _ => mul_comm _ _
  have h1 := congrArg (coeff · 1) hq
  simp only [q, finsetSum_coeff, coeff_monomial, Finset.sum_ite_eq', Finset.mem_range,
    show 1 < N by omega, ite_true, coeff_zero] at h1
  rw [h.curveCoeff_one] at h1
  exact hf h1

omit [Infinite K] in
/-- A polynomial in an operator acts on an eigenvector through its value at the eigenvalue. -/
theorem aeval_apply_of_apply_eq_smul {D : Module.End K W} {c : K} {w : W} (hw : D w = c • w)
    (p : K[X]) : aeval D p w = p.eval c • w := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => rw [map_add, LinearMap.add_apply, hp, hq, eval_add, add_smul]
  | monomial k a =>
    rw [aeval_monomial, eval_monomial, Module.End.mul_apply, Module.algebraMap_end_apply]
    have hpow : ∀ j : ℕ, (D ^ j) w = c ^ j • w := by
      intro j
      induction j with
      | zero => simp
      | succ j ih => rw [pow_succ, Module.End.mul_apply, hw, map_smul, ih, smul_smul, ← pow_succ']
    rw [hpow, smul_smul]

/-- **The diagonal torus acts through the differential**: `ρ(diag t)` is a combination of products
of polynomials in the commuting operators `dρ(E_ii)`. -/
theorem rho_diagGL_mem_adjoin [CharZero K] (h : IsPolynomialRep ρ) (s : Fin n → Kˣ) :
    ρ (diagGL s) ∈ Algebra.adjoin K (Set.range h.lie) := by
  classical
  have := h.finiteDimensional
  set S := (finite_torusWeightSpace_ne_bot (ρ.comp diagGL)).toFinset
  -- the Lagrange polynomial of `c` among the `i`-th coordinates of the weights
  let lag : Fin n → K → K[X] := fun i c =>
    ∏ c' ∈ ((S.image fun ν => (ν i : K)).erase c), (c - c')⁻¹ • (Polynomial.X - Polynomial.C c')
  have hlag : ∀ i c d, d ∈ S.image (fun ν => (ν i : K)) →
      (lag i c).eval d = if d = c then 1 else 0 := by
    intro i c d hd
    simp only [lag, eval_prod, eval_smul, eval_sub, eval_X, eval_C, smul_eq_mul]
    split_ifs with hdc
    · subst hdc
      exact Finset.prod_eq_one fun c' hc' => inv_mul_cancel₀
        (sub_ne_zero.mpr (Finset.ne_of_mem_erase hc').symm)
    · exact Finset.prod_eq_zero (Finset.mem_erase.mpr ⟨hdc, hd⟩) (by rw [sub_self, mul_zero])
  -- the projection to the weight space of `μ`
  let proj : (Fin n → ℤ) → Module.End K W := fun μ =>
    (List.ofFn fun i => aeval (h.lie (Matrix.single i i 1)) (lag i (μ i : K))).prod
  have hproj_mem : ∀ μ, proj μ ∈ Algebra.adjoin K (Set.range h.lie) := fun μ =>
    Subalgebra.list_prod_mem _ fun x hx => by
      obtain ⟨i, rfl⟩ := List.mem_ofFn.mp hx
      exact Algebra.adjoin_mono
        (Set.singleton_subset_iff.mpr (Set.mem_range_self (Matrix.single i i 1)))
        (Polynomial.aeval_mem_adjoin_singleton K _)
  have hproj : ∀ μ ν w, w ∈ weightSpace ρ ν → ν ∈ S →
      proj μ w = (if ν = μ then 1 else 0 : K) • w := by
    intro μ ν w hw hν
    have hfac : ∀ i, aeval (h.lie (Matrix.single i i 1)) (lag i (μ i : K)) w =
        (if (ν i : K) = μ i then 1 else 0 : K) • w := by
      intro i
      rw [aeval_apply_of_apply_eq_smul (h.lie_apply_of_mem_weightSpace hw i),
        hlag i _ _ (Finset.mem_image_of_mem _ hν)]
    have hprod : ∀ (L : List (Fin n)), (L.map fun i =>
        aeval (h.lie (Matrix.single i i 1)) (lag i (μ i : K))).prod w =
        (L.map fun i => (if (ν i : K) = μ i then 1 else 0 : K)).prod • w := by
      intro L
      induction L with
      | nil => simp
      | cons i L ih =>
        rw [List.map_cons, List.prod_cons, Module.End.mul_apply, ih, map_smul, hfac,
          List.map_cons, List.prod_cons, smul_smul, mul_comm]
    have hlist := hprod (List.finRange n)
    simp only [proj]
    rw [List.ofFn_eq_map, hlist]
    congr 1
    by_cases hνμ : ν = μ
    · subst hνμ
      simp
    · obtain ⟨i, hi⟩ := Function.ne_iff.mp hνμ
      have hi' : ¬((ν i : K) = μ i) := fun h' => hi (Int.cast_injective h')
      simp only [hνμ, ↓reduceIte]
      exact List.prod_eq_zero (List.mem_map.mpr ⟨i, List.mem_finRange i, by simp [hi']⟩)
  -- `ρ(diag s)` is the combination of the projections with the character values
  have hdiag : ρ (diagGL s) = ∑ μ ∈ S, weightCharHom K μ s • proj μ := by
    have hall : ∀ w ∈ (⨆ ν, weightSpace ρ ν), ρ (diagGL s) w =
        (∑ μ ∈ S, weightCharHom K μ s • proj μ) w := by
      intro w hw
      induction hw using Submodule.iSup_induction' with
      | mem ν w hw =>
        by_cases hν : ν ∈ S
        · change (ρ.comp diagGL) s w = _
          rw [apply_of_mem_torusWeightSpace hw, LinearMap.sum_apply]
          simp only [LinearMap.smul_apply, hproj _ ν w hw hν, ite_smul, one_smul, zero_smul,
            smul_ite, smul_zero]
          rw [Finset.sum_ite_eq S ν]
          simp [hν]
        · have hw0 : w = 0 := by
            have hbot : weightSpace ρ ν = ⊥ := by
              by_contra hne
              exact hν ((Set.Finite.mem_toFinset _).mpr hne)
            rw [hbot, Submodule.mem_bot] at hw
            exact hw
          simp [hw0]
      | zero => simp
      | add x y _ _ hx hy => rw [map_add, map_add, hx, hy]
    ext w
    exact hall w (by rw [h.comp_diagGL.iSup_torusWeightSpace_eq_top]; exact Submodule.mem_top)
  rw [hdiag]
  exact Subalgebra.sum_mem _ fun μ _ => Subalgebra.smul_mem _ (hproj_mem μ) _

/-- Transvections act through the differential. -/
theorem rho_transvectionGL_mem_adjoin [CharZero K] (h : IsPolynomialRep ρ) {a b : Fin n}
    (hab : a ≠ b) (t : K) :
    ρ (transvectionGL hab t) ∈ Algebra.adjoin K (Set.range h.lie) := by
  rw [transvectionGL, h.rho_lineGL_eq_exp (single_mul_single_of_ne hab) t
    (Nat.lt_succ_self (h.curveDegree (Matrix.single a b 1)))]
  exact Subalgebra.sum_mem _ fun k _ => Subalgebra.smul_mem _
    (Subalgebra.pow_mem _ (Algebra.subset_adjoin (Set.mem_range_self _)) _) _

/-- **The group and the Lie algebra generate the same algebra of operators.** -/
theorem adjoin_range_eq [CharZero K] (h : IsPolynomialRep ρ) :
    Algebra.adjoin K (Set.range ρ) = Algebra.adjoin K (Set.range h.lie) := by
  apply le_antisymm
  · rw [Algebra.adjoin_le_iff]
    rintro _ ⟨g, rfl⟩
    exact gl_induction (P := fun g => ρ g ∈ Algebra.adjoin K (Set.range h.lie))
      (fun g g₁ hg hg₁ => by rw [map_mul]; exact Subalgebra.mul_mem _ hg hg₁)
      (fun hab t => h.rho_transvectionGL_mem_adjoin hab t) (fun s => h.rho_diagGL_mem_adjoin s) g
  · rw [Algebra.adjoin_le_iff]
    rintro _ ⟨X, rfl⟩
    exact Algebra.span_le_adjoin K _ (h.lie_mem_span_range X)

/-! ### Subrepresentations and intertwining maps -/

omit [Infinite K] in
/-- A pair of endomorphisms preserves the graph of a linear map exactly when the map intertwines
them. -/
theorem prodMap_mem_graph_iff (f : W →ₗ[K] V) (T : Module.End K W) (T' : Module.End K V) :
    (∀ u ∈ f.graph, T.prodMap T' u ∈ f.graph) ↔ ∀ w, f (T w) = T' (f w) := by
  constructor
  · intro hT w
    have := hT (w, f w) ((LinearMap.mem_graph_iff f _).mpr rfl)
    exact ((LinearMap.mem_graph_iff f _).mp this).symm
  · intro hT u hu
    rw [LinearMap.mem_graph_iff] at hu ⊢
    rw [LinearMap.prodMap_apply, hu, hT]

/-- **Subrepresentations are the `dρ`-stable subspaces.** -/
theorem forall_rho_mem_iff [CharZero K] (h : IsPolynomialRep ρ) (U : Submodule K W) :
    (∀ g, ∀ u ∈ U, ρ g u ∈ U) ↔ ∀ X, ∀ u ∈ U, h.lie X u ∈ U := by
  let stab : Subalgebra K (Module.End K W) :=
    { carrier := {T | ∀ u ∈ U, T u ∈ U}
      mul_mem' := fun hS hT u hu => hS _ (hT u hu)
      add_mem' := fun hS hT u hu => U.add_mem (hS u hu) (hT u hu)
      algebraMap_mem' := fun c u hu => by
        simpa [Module.algebraMap_end_apply] using U.smul_mem c hu }
  have key : ∀ S : Set (Module.End K W),
      Algebra.adjoin K S ≤ stab ↔ ∀ T ∈ S, ∀ u ∈ U, T u ∈ U := fun S => by
    rw [Algebra.adjoin_le_iff]
    rfl
  constructor
  · intro hG X
    have := (key (Set.range ρ)).mpr (by rintro _ ⟨g, rfl⟩; exact hG g)
    rw [h.adjoin_range_eq] at this
    exact this (Algebra.subset_adjoin (Set.mem_range_self X))
  · intro hL g
    have := (key (Set.range h.lie)).mpr (by rintro _ ⟨X, rfl⟩; exact hL X)
    rw [← h.adjoin_range_eq] at this
    exact this (Algebra.subset_adjoin (Set.mem_range_self g))

/-- **Intertwining maps between polynomial representations are the maps intertwining the
differentials.** -/
theorem isIntertwining_iff_lie [CharZero K] (hρ : IsPolynomialRep ρ) (hσ : IsPolynomialRep σ)
    (f : W →ₗ[K] V) :
    (∀ g w, f (ρ g w) = σ g (f w)) ↔ ∀ X w, f (hρ.lie X w) = hσ.lie X (f w) := by
  have h1 : (∀ g w, f (ρ g w) = σ g (f w)) ↔ ∀ g, ∀ u ∈ f.graph, ρ.prod σ g u ∈ f.graph :=
    forall_congr' fun g => (prodMap_mem_graph_iff f (ρ g) (σ g)).symm
  have h2 : (∀ X w, f (hρ.lie X w) = hσ.lie X (f w)) ↔
      ∀ X, ∀ u ∈ f.graph, IsPolynomialRep.lie (hρ.prod hσ) X u ∈ f.graph := by
    refine forall_congr' fun X => ?_
    rw [lie_prod hρ hσ]
    exact (prodMap_mem_graph_iff f (hρ.lie X) (hσ.lie X)).symm
  rw [h1, h2]
  exact forall_rho_mem_iff (hρ.prod hσ) f.graph

end IsPolynomialRep

end

end GLRep
