import Schubert.GLRep.Weyl.WeylCharacter
import Schubert.GLRep.Lie.Module

/-!
# Group characters and Lie characters

Let `ρ` be a polynomial representation of `GL_n(K)`, `K` a field of characteristic zero. The
weight spaces of the diagonal torus are the weight spaces of the differential
(`GLRep.IsPolynomialRep.map_weightSpace`), so the character of `ρ` is the character of its Lie
module (`GLRep.IsPolynomialRep.glCharacter_eq`). In particular the character of the Lie module is
symmetric, and the Weyl character formula applies: **a polynomial representation whose Lie module
is generated by a highest weight vector of weight `λ` has character `s_λ`**
(`GLRep.IsPolynomialRep.character_eq_diagramSchurPoly`).

## Main results

* `GLRep.eq_of_le_of_iSup_eq_top`: a spanning family of submodules contained in an independent
  family is that family.
* `GLRep.LaurentPoly.coeff_ofPoly`, `GLRep.LaurentPoly.ofPoly_rename`.
* `GLRep.IsPolynomialRep.map_weightSpace`, `GLRep.IsPolynomialRep.glCharacter_eq`,
  `GLRep.IsPolynomialRep.isSymm_glCharacter`.
* `GLRep.IsPolynomialRep.character_eq_diagramSchurPoly`.
-/

namespace GLRep

open Module LieModule LaurentPoly

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

/-- **Filling.** If a family of submodules spans and each member lies in the corresponding member
of an independent family, then the two families agree. -/
theorem eq_of_le_of_iSup_eq_top {R M ι : Type*} [Ring R] [AddCommGroup M] [Module R M]
    {A B : ι → Submodule R M} (hle : ∀ i, A i ≤ B i) (hA : ⨆ i, A i = ⊤) (hB : iSupIndep B)
    (i : ι) : A i = B i := by
  refine le_antisymm (hle i) fun w hw => ?_
  have hw' : w ∈ A i ⊔ ⨆ (j) (_ : j ≠ i), A j := by
    rw [← iSup_split_single, hA]
    exact Submodule.mem_top
  obtain ⟨a, ha, b, hb, rfl⟩ := Submodule.mem_sup.mp hw'
  have hb' : b ∈ ⨆ (j) (_ : j ≠ i), B j := iSup₂_mono (fun j _ => hle j) hb
  have hbi : b ∈ B i := by
    have := sub_mem hw (hle i ha)
    rwa [add_sub_cancel_left] at this
  rw [Submodule.disjoint_def.mp (hB i) b hbi hb', add_zero]
  exact ha

namespace LaurentPoly

variable {R : Type*} [CommRing R] {n : ℕ}

theorem coeff_ofPoly (p : MvPolynomial (Fin n) R) (α : Fin n →₀ ℕ) :
    (ofPoly R n p).coeff (expToWeight α) = p.coeff α :=
  Finsupp.mapDomain_apply_of_injective expToWeight_injective p.coeff α

theorem coeff_ofPoly_of_notMem_range (p : MvPolynomial (Fin n) R) {μ : Fin n → ℤ}
    (hμ : μ ∉ Set.range (expToWeight (n := n))) : (ofPoly R n p).coeff μ = 0 :=
  Finsupp.mapDomain_of_notMem_range p.coeff μ hμ

/-- Renaming the variables of a polynomial by `σ` permutes its exponents by `σ`. -/
theorem ofPoly_rename (σ : Equiv.Perm (Fin n)) (p : MvPolynomial (Fin n) R) :
    ofPoly R n (MvPolynomial.rename σ p) = permute σ (ofPoly R n p) := by
  have h : (ofPoly R n).comp (MvPolynomial.rename σ).toRingHom =
      (permute σ).toRingHom.comp (ofPoly R n) := by
    refine MvPolynomial.ringHom_ext (fun r => ?_) fun i => ?_
    · simp only [RingHom.coe_comp, Function.comp_apply, AlgHom.toRingHom_eq_coe,
        RingHom.coe_coe, MvPolynomial.rename_C, RingEquiv.toRingHom_eq_coe]
      rw [← MvPolynomial.monomial_zero', ofPoly_monomial, permute_single, map_zero]
      rfl
    · simp only [RingHom.coe_comp, Function.comp_apply, AlgHom.toRingHom_eq_coe,
        RingHom.coe_coe, MvPolynomial.rename_X, RingEquiv.toRingHom_eq_coe, ofPoly_X,
        permute_single]
      congr 1
      funext j
      simp only [Function.comp_apply, Pi.single_apply, Equiv.symm_apply_eq]
  exact congrArg (fun f : MvPolynomial (Fin n) R →+* LaurentPoly R n => f p) h

end LaurentPoly

variable {K : Type*} [Field K] [CharZero K] {n : ℕ}
variable {W : Type*} [AddCommGroup W] [Module K W] {ρ : Representation K (GL (Fin n) K) W}

namespace IsPolynomialRep

variable (h : IsPolynomialRep ρ)

/-- **The weight spaces of the torus are the weight spaces of the differential.** -/
theorem map_weightSpace (μ : Fin n → ℤ) :
    (weightSpace ρ μ).map h.toLieRep.toLinearMap = glWeightSpace K h.LieRep μ := by
  refine eq_of_le_of_iSup_eq_top (A := fun μ => (weightSpace ρ μ).map h.toLieRep.toLinearMap)
    (fun μ => ?_) ?_ (iSupIndep_glWeightSpace K h.LieRep) μ
  · rintro _ ⟨w, hw, rfl⟩
    refine mem_glWeightSpace.mpr fun i => ?_
    rw [LinearEquiv.coe_coe, lie_toLieRep, h.lie_apply_of_mem_weightSpace hw i, map_smul]
  · rw [← Submodule.map_iSup, h.comp_diagGL.iSup_torusWeightSpace_eq_top, Submodule.map_top,
      LinearEquiv.range]

theorem finrank_glWeightSpace (μ : Fin n → ℤ) :
    finrank K (glWeightSpace K h.LieRep μ) = finrank K (weightSpace ρ μ) := by
  rw [← h.map_weightSpace μ]
  exact (Submodule.equivMapOfInjective _ h.toLieRep.injective _).finrank_eq.symm

/-- **The character of a polynomial representation is the character of its Lie module.** -/
theorem glCharacter_eq :
    glCharacter K h.LieRep = ofPoly K n (MvPolynomial.map (Int.castRingHom K) (character ρ)) := by
  ext μ
  rw [coeff_glCharacter, h.finrank_glWeightSpace]
  by_cases hμ : μ ∈ Set.range (expToWeight (n := n))
  · obtain ⟨α, rfl⟩ := hμ
    rw [coeff_ofPoly, MvPolynomial.coeff_map, coeff_character h, eq_intCast, Int.cast_natCast]
    rfl
  · rw [coeff_ofPoly_of_notMem_range _ hμ]
    have hneg : ∃ i, μ i < 0 := by
      by_contra hneg
      push Not at hneg
      exact hμ ⟨Finsupp.equivFunOnFinite.symm fun i => (μ i).toNat, funext fun i => by
        simp [expToWeight, Int.toNat_of_nonneg (hneg i)]⟩
    rw [weightSpace, h.comp_diagGL.torusWeightSpace_eq_bot hneg, finrank_bot, Nat.cast_zero]

/-- **The character of the Lie module of a polynomial representation is symmetric.** -/
theorem isSymm_glCharacter : IsSymm (glCharacter K h.LieRep : LaurentPoly K n) := fun σ => by
  rw [h.glCharacter_eq, ← ofPoly_rename, ← MvPolynomial.map_rename, h.character_isSymmetric σ]

/-- **The character of a highest weight representation.** If the Lie module of a polynomial
representation `ρ` of `GL_n(K)` is generated by a highest weight vector of weight `λ`, the row
lengths of a Young diagram with at most `n` rows, then the character of `ρ` is the Schur
polynomial `s_λ`. -/
theorem character_eq_diagramSchurPoly {μ : YoungDiagram} (hμ : μ.colLen 0 ≤ n) {v : h.LieRep}
    (hv : TauCeti.IsGlHighestWeightVector (fun i : Fin n => (μ.rowLen i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) :
    character ρ = TauCeti.diagramSchurPoly n ℤ μ := by
  have hv' : TauCeti.IsGlHighestWeightVector
      (fun i : Fin n => (((μ.rowLen i : ℤ)) : K)) v := by
    simpa only [Int.cast_natCast] using hv
  have hwcf := alternant_mul_glCharacter_of_isGlHighestWeightVector hv' hgen
    h.isSymm_glCharacter
  rw [h.glCharacter_eq] at hwcf
  have hs := LaurentPoly.eq_diagramSchurPoly_of_alternant_mul_eq _ μ hμ hwcf
  apply MvPolynomial.map_injective (Int.castRingHom K) (RingHom.injective_int _)
  rw [hs, TauCeti.map_diagramSchurPoly]

end IsPolynomialRep

end

end GLRep
