import Schubert.GLRep.Weyl.Freudenthal
import TauCeti.Algebra.Lie.GeneralLinear.Casimir
import TauCeti.Algebra.Lie.GeneralLinear.Uniqueness
import TauCeti.RingTheory.MvPolynomial.Symmetric.Schur.Bialternant

/-!
# The Weyl character formula for `gl_n`

Let `M` be a finite-dimensional `gl_n(K)`-module, `K` a field of characteristic zero, generated by
a highest weight vector of an integral weight `λ`. If the character of `M` is symmetric, then `λ`
is dominant and

`a_δ · ch M = a_{λ+δ}`

(`GLRep.alternant_mul_glCharacter_of_isGlHighestWeightVector`). By Jacobi's bialternant formula,
`ch M` is then the Schur polynomial `s_λ` when `λ` is a partition.

The proof assembles the earlier steps:

* Freudenthal's formula and the root-string recursion, as identities of Laurent polynomials
  (`GLRep.freudenthal_laurent`, `GLRep.stringRecursion_laurent`);
* the Laplacian eigen-equation `D(a_δ ch M) = |λ + δ|² a_δ ch M`
  (`GLRep.LaurentPoly.laplace_alternant_staircase_mul`);
* strict convexity and antisymmetry (`GLRep.LaurentPoly.alternant_staircase_mul_eq`).

For a module generated by a highest weight vector `v`, the weights are dominated by `λ`: the sum
of the weight spaces of weights dominated by `λ` contains `v` and is stable under the lowering
operators, hence it is everything (Tau Ceti). The weight space of `λ` is the line through `v`
(Tau Ceti), and the Casimir element acts by a scalar computed on `v` (Tau Ceti).

## Main definitions

* `GLRep.stringPoly`: the Laurent polynomial `∑_μ t_{ab}(μ) x^μ`.
* `GLRep.dominatedPart`: the sum of the weight spaces of weights dominated by `λ`.

## Main results

* `GLRep.freudenthal_laurent`, `GLRep.stringRecursion_laurent`.
* `GLRep.alternant_mul_glCharacter`: the formula for a finite-dimensional module whose weights are
  dominated by `λ`, with `dim M_λ = 1`, on which the Casimir element acts by the scalar of `λ`.
* `GLRep.glWeightSpace_eq_bot_of_not_dominated`,
  `GLRep.finrank_glWeightSpace_of_isGlHighestWeightVector`: the weights of a highest weight
  module.
* `GLRep.alternant_mul_glCharacter_of_isGlHighestWeightVector`: the Weyl character formula.
* `GLRep.LaurentPoly.eq_diagramSchurPoly_of_alternant_mul_eq`: a polynomial `χ` with
  `a_δ χ = a_{λ+δ}` is the Schur polynomial `s_λ`.
-/

namespace GLRep

open Module LieModule Finset LaurentPoly

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

variable {K : Type*} [Field K] [CharZero K] {n : ℕ}
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule (Matrix (Fin n) (Fin n) K) M]
  [LieModule K (Matrix (Fin n) (Fin n) K) M]

/-! ### Coefficient lemmas -/

omit [CharZero K] in
theorem LaurentPoly.coeff_euler (k : Fin n) (f : LaurentPoly K n) (μ : Fin n → ℤ) :
    (euler k f).coeff μ = (μ k : K) * f.coeff μ := by
  induction f using AddMonoidAlgebra.induction_linear with
  | zero => simp
  | add f g hf hg => simp only [map_add, AddMonoidAlgebra.coeff_add, Finsupp.add_apply, hf, hg,
      mul_add]
  | single ν c =>
    rw [euler_single, AddMonoidAlgebra.coeff_single, AddMonoidAlgebra.coeff_single,
      Finsupp.single_apply, Finsupp.single_apply]
    split_ifs with h
    · rw [h]
    · rw [mul_zero]

omit [CharZero K] in
theorem LaurentPoly.coeff_var_mul (f : LaurentPoly K n) (i : Fin n) (μ : Fin n → ℤ) :
    (var i * f).coeff μ = f.coeff (μ - Pi.single i 1) := by
  rw [var, coeff_single_mul, one_mul]

omit [CharZero K] in
theorem LaurentPoly.coeff_mul_var (f : LaurentPoly K n) (i : Fin n) (μ : Fin n → ℤ) :
    (f * var i).coeff μ = f.coeff (μ - Pi.single i 1) := by
  rw [mul_comm, coeff_var_mul]

/-! ### Freudenthal's formula as an identity of Laurent polynomials -/

variable (K M) in
/-- The Laurent polynomial `U_{ab} = ∑_μ t_{ab}(μ) x^μ`, where `t_{ab}(μ)` is the trace of
`E_ba E_ab` on the weight space of `μ`. -/
def stringPoly (a b : Fin n) : LaurentPoly K n := LaurentPoly.ofFun (stringTrace K M a b)

theorem finite_support_stringTrace [FiniteDimensional K M] (a b : Fin n) :
    (Function.support (stringTrace K M a b)).Finite := by
  refine (finite_glWeightSpace_ne_bot K M).subset fun μ hμ => ?_
  intro hbot
  apply hμ
  have : Subsingleton (glWeightSpace K M μ) := Submodule.subsingleton_iff_eq_bot.mpr hbot
  rw [stringTrace, show (weightShift K M b a (add_root_add_root μ a b).symm).comp
      (weightShift K M a b (μ := μ) rfl) = 0 from LinearMap.ext fun _ => Subsingleton.elim _ _,
    map_zero]

theorem coeff_stringPoly [FiniteDimensional K M] (a b : Fin n) (μ : Fin n → ℤ) :
    (stringPoly K M a b).coeff μ = stringTrace K M a b μ :=
  LaurentPoly.coeff_ofFun (finite_support_stringTrace a b) μ

/-- **Freudenthal's formula** as an identity of Laurent polynomials:
`c ch M = D ch M + ∑_{a<b} (θ_a − θ_b) ch M + 2 ∑_{a<b} U_{ab}`. -/
theorem freudenthal_laurent [FiniteDimensional K M] (c : K)
    (hΩ : ∀ m : M, ∑ i, ∑ j, ⁅(matUnit i j : Matrix (Fin n) (Fin n) K),
      ⁅(matUnit j i : Matrix (Fin n) (Fin n) K), m⁆⁆ = c • m) :
    c • glCharacter K M = laplace (glCharacter K M) +
      ∑ p ∈ posPairs n, (euler p.1 (glCharacter K M) - euler p.2 (glCharacter K M)) +
        2 * ∑ p ∈ posPairs n, stringPoly K M p.1 p.2 := by
  ext μ
  rw [two_mul]
  simp only [AddMonoidAlgebra.coeff_add, AddMonoidAlgebra.coeff_smul, AddMonoidAlgebra.coeff_sum,
    AddMonoidAlgebra.coeff_sub, Finsupp.add_apply, Finsupp.smul_apply, Finsupp.coe_finsetSum,
    Finset.sum_apply, Finsupp.sub_apply, smul_eq_mul, coeff_laplace, coeff_euler,
    coeff_glCharacter, coeff_stringPoly]
  rw [freudenthal c hΩ μ]
  simp only [sub_mul]
  ring

/-- **The root-string recursion** as an identity of Laurent polynomials:
`U_{ab} (x_a − x_b) = x_b (θ_a − θ_b) ch M`. -/
theorem stringRecursion_laurent [FiniteDimensional K M] (a b : Fin n) :
    stringPoly K M a b * (var a - var b) =
      var b * (euler a (glCharacter K M) - euler b (glCharacter K M)) := by
  ext μ
  rw [mul_sub]
  simp only [AddMonoidAlgebra.coeff_sub, Finsupp.sub_apply, coeff_mul_var, coeff_var_mul,
    coeff_euler, coeff_stringPoly, coeff_glCharacter]
  have hμ : μ - Pi.single a 1 = (μ - Pi.single b 1) + root b a := by
    rw [root]
    abel
  rw [hμ, stringTrace_sub_root]
  ring

/-! ### The formula for modules with the right Casimir scalar -/

omit [CharZero K] in
/-- The eigenvalue arithmetic: with `c = ∑_i λ_i (λ_i + n − 1 − 2i)` and `d = ∑_i λ_i`,
`c + (n − 1) d + |δ|² = |λ + δ|²`. -/
theorem casimir_add_eq_normSq (lam : Fin n → ℤ) :
    (∑ i : Fin n, (lam i : K) * ((lam i : K) + n - 1 - 2 * ((i : ℕ) : K))) +
        ((n - 1 : ℕ) : K) * (∑ i, (lam i : K)) + (normSq (staircase n) : K) =
      (normSq (lam + staircase n) : K) := by
  simp only [normSq, Int.cast_sum, Int.cast_mul, Pi.add_apply, Int.cast_add, staircase,
    Int.cast_sub, Int.cast_natCast, Int.cast_one, mul_sum, ← sum_add_distrib]
  refine sum_congr rfl fun i _ => ?_
  rw [Nat.cast_sub (by have := i.pos; omega), Nat.cast_one]
  ring

/-- **The Weyl character formula** for a finite-dimensional `gl_n`-module with symmetric
character whose weights are dominated by a weakly decreasing `λ`, with `dim M_λ = 1`, and on which
the Casimir element acts by `∑_i λ_i (λ_i + n − 1 − 2i)`. -/
theorem alternant_mul_glCharacter [FiniteDimensional K M] (lam : Fin n → ℤ) (hlam : Antitone lam)
    (hsymm : IsSymm (glCharacter K M : LaurentPoly K n))
    (hsupp : ∀ μ, glWeightSpace K M μ ≠ ⊥ → Dominated μ lam)
    (hlam1 : finrank K (glWeightSpace K M lam) = 1)
    (hΩ : ∀ m : M, ∑ i, ∑ j, ⁅(matUnit i j : Matrix (Fin n) (Fin n) K),
      ⁅(matUnit j i : Matrix (Fin n) (Fin n) K), m⁆⁆ =
        (∑ i : Fin n, (lam i : K) * ((lam i : K) + n - 1 - 2 * ((i : ℕ) : K))) • m) :
    alternant (staircase n) * glCharacter K M = alternant (lam + staircase n) := by
  have hsupp' : ∀ μ, (glCharacter K M).coeff μ ≠ 0 → Dominated μ lam := by
    intro μ hμ
    refine hsupp μ fun hbot => hμ ?_
    rw [coeff_glCharacter, hbot, finrank_bot, Nat.cast_zero]
  have hE : ∑ k : Fin n, euler k (glCharacter K M) = (∑ i, (lam i : K)) • glCharacter K M := by
    ext μ
    simp only [AddMonoidAlgebra.coeff_sum, AddMonoidAlgebra.coeff_smul, Finsupp.coe_finsetSum,
      Finset.sum_apply, Finsupp.smul_apply, smul_eq_mul, coeff_euler, ← sum_mul]
    by_cases hμ : (glCharacter K M).coeff μ = 0
    · rw [hμ, mul_zero, mul_zero]
    · have h := (hsupp' μ hμ).2
      rw [← Int.cast_sum, ← Int.cast_sum, h]
  have heig := laplace_alternant_staircase_mul (glCharacter K M)
    (fun p => stringPoly K M p.1 p.2) _ _ (freudenthal_laurent _ hΩ)
    (fun p _ => stringRecursion_laurent p.1 p.2) hE
  rw [casimir_add_eq_normSq] at heig
  refine alternant_staircase_mul_eq _ hsymm lam hlam hsupp' ?_ heig
  rw [coeff_glCharacter, hlam1, Nat.cast_one]

/-! ### Highest weight modules -/

/-- Lowering by a negative root keeps a weight dominated by `λ` dominated by `λ`. -/
theorem Dominated.add_root {μ lam : Fin n → ℤ} (h : Dominated μ lam) {a b : Fin n}
    (hba : b < a) : Dominated (μ + root a b) lam := by
  refine Dominated.trans ?_ h
  have := dominated_add_root (μ + root a b) hba
  rwa [show μ + root a b + (Pi.single b 1 - Pi.single a 1) = μ by rw [root]; abel] at this

variable (K M) in
/-- The sum of the weight spaces of the weights dominated by `λ`. -/
def dominatedPart (lam : Fin n → ℤ) : Submodule K M :=
  ⨆ (μ : Fin n → ℤ) (_ : Dominated μ lam), glWeightSpace K M μ

omit [CharZero K] in
theorem glWeightSpace_le_dominatedPart {μ lam : Fin n → ℤ} (h : Dominated μ lam) :
    glWeightSpace K M μ ≤ dominatedPart K M lam :=
  le_iSup₂_of_le μ h le_rfl

omit [CharZero K] in
/-- The lowering operators preserve `dominatedPart K M λ`. -/
theorem lie_mem_dominatedPart {lam : Fin n → ℤ} {a b : Fin n} (hba : b < a) {m : M}
    (hm : m ∈ dominatedPart K M lam) :
    ⁅(matUnit a b : Matrix (Fin n) (Fin n) K), m⁆ ∈ dominatedPart K M lam := by
  have hle : (dominatedPart K M lam).map (toEnd K (Matrix (Fin n) (Fin n) K) M (matUnit a b)) ≤
      dominatedPart K M lam := by
    rw [dominatedPart, Submodule.map_iSup]
    refine iSup_le fun μ => ?_
    rw [Submodule.map_iSup]
    refine iSup_le fun hμ => ?_
    rintro _ ⟨w, hw, rfl⟩
    exact glWeightSpace_le_dominatedPart (hμ.add_root hba) (lie_mem_glWeightSpace hw a b)
  exact hle ⟨m, hm, rfl⟩

omit [CharZero K] in
/-- A submodule stable under the lowering matrix units is stable under all strictly lower
triangular matrices. -/
theorem lie_mem_of_mem_strictLowerTriangular {N : Submodule K M}
    (h : ∀ a b : Fin n, b < a → ∀ m ∈ N, ⁅(matUnit a b : Matrix (Fin n) (Fin n) K), m⁆ ∈ N)
    {x : Matrix (Fin n) (Fin n) K} (hx : x ∈ TauCeti.strictLowerTriangular K (Fin n)) {m : M}
    (hm : m ∈ N) : ⁅x, m⁆ ∈ N := by
  have hsum : ⁅x, m⁆ = ∑ i : Fin n, ∑ j : Fin n,
      ⁅(Matrix.single i j (x i j) : Matrix (Fin n) (Fin n) K), m⁆ := by
    conv_lhs => rw [Matrix.matrix_eq_sum_single x]
    rw [sum_lie]
    exact Finset.sum_congr rfl fun i _ => by rw [sum_lie]
  rw [hsum]
  refine Submodule.sum_mem _ fun i _ => Submodule.sum_mem _ fun j _ => ?_
  rcases lt_or_ge j i with hji | hji
  · have hsmul : Matrix.single i j (x i j) = x i j • (matUnit i j : Matrix (Fin n) (Fin n) K) := by
      rw [Matrix.smul_single, smul_eq_mul, mul_one]
    rw [hsmul, smul_lie]
    exact Submodule.smul_mem _ _ (h i j hji m hm)
  · rw [TauCeti.mem_strictLowerTriangular_iff.mp hx i j hji, Matrix.single_zero, zero_lie]
    exact Submodule.zero_mem _

variable {lam : Fin n → ℤ} {v : M}

omit [CharZero K] in
theorem mem_glWeightSpace_of_isGlHighestWeightVector
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v) :
    v ∈ glWeightSpace K M lam :=
  mem_glWeightSpace.mpr hv.lie_single_self_eq_smul

omit [CharZero K] in
/-- A module generated by a highest weight vector of weight `λ` is spanned by the weight spaces
of the weights dominated by `λ`. -/
theorem dominatedPart_eq_top
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) :
    dominatedPart K M lam = ⊤ := by
  have h := TauCeti.lieSpan_toSubmodule_le_of_isGlHighestWeightVector hv
    (glWeightSpace_le_dominatedPart (dominated_refl lam)
      (mem_glWeightSpace_of_isGlHighestWeightVector hv))
    fun x hx m hm => lie_mem_of_mem_strictLowerTriangular
      (fun a b hba m hm => lie_mem_dominatedPart hba hm) hx hm
  rw [hgen, LieSubmodule.top_toSubmodule] at h
  exact top_le_iff.mp h

/-- **The weights of a highest weight module are dominated by the highest weight.** -/
theorem glWeightSpace_eq_bot_of_not_dominated
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤)
    {μ : Fin n → ℤ} (hμ : ¬Dominated μ lam) : glWeightSpace K M μ = ⊥ := by
  have hdisj := iSupIndep_glWeightSpace K M μ
  have hle : dominatedPart K M lam ≤ ⨆ (ν : Fin n → ℤ) (_ : ν ≠ μ), glWeightSpace K M ν :=
    biSup_mono fun ν hν h => hμ (h ▸ hν)
  rw [dominatedPart_eq_top hv hgen, top_le_iff] at hle
  rw [hle] at hdisj
  exact disjoint_top.mp hdisj

/-- **The highest weight space is the line through the highest weight vector.** -/
theorem glWeightSpace_eq_span_singleton
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) :
    glWeightSpace K M lam = K ∙ v := by
  apply le_antisymm
  · intro w hw
    obtain ⟨c, hc⟩ := TauCeti.exists_eq_smul_of_isGlHighestWeightVector_of_mem_lieSpan hv
      (by rw [hgen]; exact LieSubmodule.mem_top w) (mem_glWeightSpace.mp hw)
    exact Submodule.mem_span_singleton.mpr ⟨c, hc.symm⟩
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    exact mem_glWeightSpace_of_isGlHighestWeightVector hv

theorem finrank_glWeightSpace_of_isGlHighestWeightVector
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) :
    finrank K (glWeightSpace K M lam) = 1 := by
  rw [glWeightSpace_eq_span_singleton hv hgen, finrank_span_singleton hv.ne_zero]

omit [CharZero K] in
/-- The Casimir element acts on a highest weight module by `∑_i λ_i (λ_i + n − 1 − 2i)`. -/
theorem casimir_apply_of_isGlHighestWeightVector
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) (m : M) :
    ∑ i, ∑ j, ⁅(matUnit i j : Matrix (Fin n) (Fin n) K),
      ⁅(matUnit j i : Matrix (Fin n) (Fin n) K), m⁆⁆ =
        (∑ i : Fin n, (lam i : K) * ((lam i : K) + n - 1 - 2 * ((i : ℕ) : K))) • m := by
  rw [← TauCeti.representation_glCasimir_apply K (Fin n),
    TauCeti.glCasimir_smul_of_isGlHighestWeightVector_of_lieSpan_eq_top K hv hgen]

omit [CharZero K] in
/-- If a symmetric Laurent polynomial has coefficient `1` at `λ` and all its exponents are
dominated by `λ`, then `λ` is weakly decreasing. -/
theorem LaurentPoly.antitone_of_isSymm {χ : LaurentPoly K n} (hsymm : IsSymm χ)
    (hsupp : ∀ μ, χ.coeff μ ≠ 0 → Dominated μ lam) (hlam : χ.coeff lam ≠ 0) : Antitone lam := by
  obtain ⟨τ, hτ⟩ : ∃ τ : Equiv.Perm (Fin n), Antitone (lam ∘ τ) :=
    ⟨Tuple.sort (fun i => -lam i), fun i j hij => by
      have := Tuple.monotone_sort (fun i => -lam i) hij
      simp only [Function.comp_apply] at this ⊢
      linarith⟩
  have h1 : Dominated (lam ∘ τ) lam := by
    refine hsupp _ ?_
    rw [← coeff_permute, hsymm]
    exact hlam
  have h2 : Dominated lam (lam ∘ τ) := by
    have := dominated_comp_perm hτ τ.symm
    rwa [Function.comp_assoc, Equiv.self_comp_symm, Function.comp_id] at this
  rw [Dominated.antisymm h2 h1]
  exact hτ

/-- A highest weight of a finite-dimensional highest weight module with symmetric character is
dominant. -/
theorem antitone_of_isGlHighestWeightVector
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) [FiniteDimensional K M]
    (hsymm : IsSymm (glCharacter K M : LaurentPoly K n)) : Antitone lam := by
  refine LaurentPoly.antitone_of_isSymm hsymm (fun μ hμ => ?_) ?_
  · by_contra h
    apply hμ
    rw [coeff_glCharacter, glWeightSpace_eq_bot_of_not_dominated hv hgen h, finrank_bot,
      Nat.cast_zero]
  · rw [coeff_glCharacter, finrank_glWeightSpace_of_isGlHighestWeightVector hv hgen,
      Nat.cast_one]
    exact one_ne_zero

/-- **The Weyl character formula for `gl_n`.** Let `M` be a finite-dimensional `gl_n`-module
generated by a highest weight vector of an integral weight `λ`, whose character is symmetric. Then
`a_δ · ch M = a_{λ+δ}`. -/
theorem alternant_mul_glCharacter_of_isGlHighestWeightVector [FiniteDimensional K M]
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤)
    (hsymm : IsSymm (glCharacter K M : LaurentPoly K n)) :
    alternant (staircase n) * glCharacter K M = alternant (lam + staircase n) :=
  alternant_mul_glCharacter lam (antitone_of_isGlHighestWeightVector hv hgen hsymm) hsymm
    (fun μ hμ => by
      by_contra h
      exact hμ (glWeightSpace_eq_bot_of_not_dominated hv hgen h))
    (finrank_glWeightSpace_of_isGlHighestWeightVector hv hgen)
    (casimir_apply_of_isGlHighestWeightVector hv hgen)

/-! ### Schur polynomials -/

omit [CharZero K] in
/-- **Schur polynomials from the Weyl character formula.** A polynomial `χ` with
`a_δ χ = a_{λ+δ}`, for the row lengths `λ` of a Young diagram with at most `n` rows, is the Schur
polynomial `s_λ`. -/
theorem LaurentPoly.eq_diagramSchurPoly_of_alternant_mul_eq
    (χ : MvPolynomial (Fin n) K) (μ : YoungDiagram) (hμ : μ.colLen 0 ≤ n)
    (h : alternant (staircase n) * ofPoly K n χ =
      alternant ((fun i : Fin n => (μ.rowLen i : ℤ)) + staircase n)) :
    χ = TauCeti.diagramSchurPoly n K μ := by
  have hδ : ofPoly K n (TauCeti.alternant (Fin n) K fun j => n - 1 - j) =
      alternant (staircase n) := by
    rw [ofPoly_alternant]
    congr 1
    funext j
    simp only [staircase]
    have := j.isLt
    omega
  have hβ : ofPoly K n (TauCeti.alternant (Fin n) K fun j => μ.betaNumber n j) =
      alternant ((fun i : Fin n => (μ.rowLen i : ℤ)) + staircase n) := by
    rw [ofPoly_alternant]
    congr 1
    funext j
    simp only [Pi.add_apply, staircase, YoungDiagram.betaNumber_def]
    have := j.isLt
    omega
  have hinj : Function.Injective fun j : Fin n => n - 1 - (j : ℕ) := fun i j hij => by
    have := i.isLt
    have := j.isLt
    simp only at hij
    exact Fin.ext (by omega)
  apply mul_right_cancel₀ (TauCeti.alternant_ne_zero_of_injective (R := K) hinj)
  apply ofPoly_injective
  rw [TauCeti.diagramSchurPoly_mul_alternant n μ hμ, map_mul, hδ, hβ, mul_comm, h]

end

end GLRep
