import Schubert.RS.Representation.FlagSeeds
import Mathlib.LinearAlgebra.Isomorphisms

namespace Schubert.RS.Representation
noncomputable section
open scoped BigOperators

instance polynomialEnvelopingModule (n : ℕ) : Module (Enveloping n) (MatrixPolynomial n) :=
  Module.compHom (MatrixPolynomial n) (polynomialEnveloping n).toRingHom

instance polynomialEnvelopingTower (n : ℕ) : IsScalarTower ℂ (Enveloping n) (MatrixPolynomial n) where
  smul_assoc c a p := by
    change polynomialEnveloping n (c • a) p = c • polynomialEnveloping n a p
    rw [map_smul]
    rfl

def polynomialTorus (n : ℕ) : DiagonalTorus n →* Module.End ℂ (MatrixPolynomial n) where
  toFun t := (rowAction (Matrix.diagonal fun i => (t i : ℂ))).toLinearMap
  map_one' := by
    apply LinearMap.ext
    intro p
    change rowAction (Matrix.diagonal fun _ => (1 : ℂ)) p = p
    rw [Matrix.diagonal_one, rowAction_one]
    rfl
  map_mul' s t := by
    apply LinearMap.ext
    intro p
    change rowAction (Matrix.diagonal fun i => ((s*t) i : ℂ)) p =
      rowAction (Matrix.diagonal fun i => (s i : ℂ)) (rowAction (Matrix.diagonal fun i => (t i : ℂ)) p)
    rw [show Matrix.diagonal (fun i => ((s*t) i : ℂ)) =
      Matrix.diagonal (fun i => (s i : ℂ)) * Matrix.diagonal (fun i => (t i : ℂ)) by
        simp [Matrix.diagonal_mul_diagonal]]
    exact AlgHom.congr_fun (rowAction_mul _ _) p

theorem polynomialTorus_X {n : ℕ} (t : DiagonalTorus n) (r c : Fin n) :
    polynomialTorus n t (MvPolynomial.X (r,c)) = (t r : ℂ) • MvPolynomial.X (r,c) := by
  change rowAction (Matrix.diagonal fun i => (t i : ℂ)) (MvPolynomial.X (r,c)) = _
  simp [rowAction_X, Matrix.diagonal_apply]

/-- The natural cyclic orbit map in the concrete polynomial representation. -/
def upperOrbitMap {n : ℕ} (p : MatrixPolynomial n) : Enveloping n →ₗ[ℂ] MatrixPolynomial n where
  toFun a := polynomialEnveloping n a p
  map_add' a b := by rw [map_add]; rfl
  map_smul' c a := by rw [map_smul]; rfl

def upperCyclic {n : ℕ} (p : MatrixPolynomial n) : Submodule ℂ (MatrixPolynomial n) :=
  LinearMap.range (upperOrbitMap p)

theorem upperCyclic_seed {n : ℕ} (p : MatrixPolynomial n) : p ∈ upperCyclic p := by
  refine ⟨1, ?_⟩
  change polynomialEnveloping n 1 p = p
  rw [map_one]
  rfl

theorem upperCyclic_stable {n : ℕ} (p : MatrixPolynomial n) (a : Enveloping n)
    {q : MatrixPolynomial n} (hq : q ∈ upperCyclic p) :
    polynomialEnveloping n a q ∈ upperCyclic p := by
  obtain ⟨b, rfl⟩ := hq
  refine ⟨a*b, ?_⟩
  change polynomialEnveloping n (a*b) p = polynomialEnveloping n a (polynomialEnveloping n b p)
  rw [map_mul]
  rfl

/-- A cyclic-span inclusion under the stated seed-membership hypothesis. -/
theorem upperCyclic_le_of_seed_mem {n : ℕ} (p q : MatrixPolynomial n)
    (hp : p ∈ upperCyclic q) : upperCyclic p ≤ upperCyclic q := by
  rintro v ⟨a, rfl⟩
  exact upperCyclic_stable q a hp

/-- The upper-Lie cyclic module generated by the extremal flag polynomial. -/
def flagDemazure {n : ℕ} (m : ColumnShape n) (w : Equiv.Perm (Fin n)) :
    Submodule ℂ (MatrixPolynomial n) := upperCyclic (extremalFlag m w)

def flagCyclicMap {n : ℕ} (m : ColumnShape n) (w : Equiv.Perm (Fin n)) :
    Enveloping n →ₗ[ℂ] flagDemazure m w := (upperOrbitMap (extremalFlag m w)).rangeRestrict

theorem flagCyclicMap_surjective {n : ℕ} (m : ColumnShape n) (w : Equiv.Perm (Fin n)) :
    Function.Surjective (flagCyclicMap m w) := by
  rintro ⟨p, a, ha⟩
  exact ⟨a, Subtype.ext ha⟩

instance flagDemazureModule {n : ℕ} (m : ColumnShape n) (w : Equiv.Perm (Fin n)) :
    Module (Enveloping n) (flagDemazure m w) where
  smul a p := ⟨a • p.val, upperCyclic_stable (extremalFlag m w) a p.property⟩
  one_smul p := Subtype.ext (one_smul _ _)
  mul_smul a b p := Subtype.ext (mul_smul a b p.val)
  smul_add a p q := Subtype.ext (smul_add a p.val q.val)
  smul_zero a := Subtype.ext (smul_zero a)
  add_smul a b p := Subtype.ext (add_smul a b p.val)
  zero_smul p := Subtype.ext (zero_smul _ p.val)

instance flagDemazureTower {n : ℕ} (m : ColumnShape n) (w : Equiv.Perm (Fin n)) :
    IsScalarTower ℂ (Enveloping n) (flagDemazure m w) where
  smul_assoc c a p := Subtype.ext (smul_assoc c a p.val)

/-- The same natural map with its actual U(n_+)-linearity made explicit. -/
def flagCyclicModuleMap {n : ℕ} (m : ColumnShape n) (w : Equiv.Perm (Fin n)) :
    Enveloping n →ₗ[Enveloping n] flagDemazure m w where
  toFun := flagCyclicMap m w
  map_add' := (flagCyclicMap m w).map_add
  map_smul' a b := by
    apply Subtype.ext
    change polynomialEnveloping n (a*b) (extremalFlag m w) =
      polynomialEnveloping n a (polynomialEnveloping n b (extremalFlag m w))
    rw [map_mul]
    rfl

end
end Schubert.RS.Representation
