import RSCounterexample.FlagVarieties.LineBundle.Model
import Mathlib.Algebra.MvPolynomial.Funext

/-!
# The coordinate ring of `B`

* `FlagVarieties.mem_borelCoordIdeal_of_upperPart_eq_zero`: a function on `GLₙ` whose numerator
  becomes zero after killing the variables below the diagonal lies in `borelCoordIdeal`.
* `FlagVarieties.toUpperRing_injective`: `𝒪(B)` embeds into `R[xᵢⱼ][(∏ xᵢᵢ)⁻¹]`; hence
  `𝒪(B)` is a domain when `R` is (`instIsDomainBorelCoord`).
* `FlagVarieties.mem_borelCoordIdeal_of_forall` (density of `B(K)` in `B`): over an infinite field,
  a function vanishing at every invertible upper triangular matrix lies in `borelCoordIdeal`.
-/

noncomputable section

namespace FlagVarieties

open MvPolynomial

universe u

section Ring

variable {R : Type u} [CommRing R] {n : ℕ}

/-- Kill the variables below the diagonal. -/
def upperPart : MvPolynomial (Fin n × Fin n) R →ₐ[R] MvPolynomial (Fin n × Fin n) R :=
  aeval fun ij => if ij.1 ≤ ij.2 then X ij else 0

/-- The ideal of `R[xᵢⱼ]` generated by the variables below the diagonal. -/
def lowerVarIdeal : Ideal (MvPolynomial (Fin n × Fin n) R) :=
  Ideal.span (Set.range fun p : {p : Fin n × Fin n // p.2 < p.1} => X p.1)

theorem sub_upperPart_mem (p : MvPolynomial (Fin n × Fin n) R) :
    p - upperPart p ∈ lowerVarIdeal (R := R) (n := n) := by
  rw [← Ideal.Quotient.eq]
  have h : (Ideal.Quotient.mkₐ R (lowerVarIdeal (R := R) (n := n))).comp upperPart =
      Ideal.Quotient.mkₐ R _ := by
    apply MvPolynomial.algHom_ext
    intro ij
    simp only [upperPart, AlgHom.comp_apply, aeval_X]
    split_ifs with h
    · rfl
    · rw [map_zero, eq_comm, Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem]
      exact Ideal.subset_span ⟨⟨ij, lt_of_not_ge h⟩, rfl⟩
  exact (congrArg (fun φ => φ p) h).symm

theorem map_lowerVarIdeal_le :
    (lowerVarIdeal (R := R) (n := n)).map (algebraMap _ (GLCoord R n)) ≤ borelCoordIdeal R n := by
  rw [lowerVarIdeal, Ideal.map_span, Ideal.span_le]
  rintro _ ⟨_, ⟨q, rfl⟩, rfl⟩
  exact Ideal.subset_span ⟨q,
    (TauCeti.GeneralLinear.localizedGenericMatrix_apply R n q.1.1 q.1.2).trans
      (TauCeti.GeneralLinear.coordinateRingMap_apply R n _)⟩

/-- A function `f = p / det^k` on `GLₙ` with `upperPart p = 0` lies in `borelCoordIdeal`. -/
theorem mem_borelCoordIdeal_of_upperPart_eq_zero (f : GLCoord R n)
    (p : MvPolynomial (Fin n × Fin n) R)
    (k : ℕ)
    (hpk : f * algebraMap _ (GLCoord R n)
        ((Matrix.det (Matrix.mvPolynomialX (Fin n) (Fin n) R)) ^ k) =
      algebraMap _ (GLCoord R n) p)
    (hp : upperPart p = 0) : f ∈ borelCoordIdeal R n := by
  have hlow : p ∈ lowerVarIdeal (R := R) (n := n) := by
    simpa [hp] using sub_upperPart_mem p
  have hmap : algebraMap _ (GLCoord R n) p ∈ borelCoordIdeal R n :=
    map_lowerVarIdeal_le (Ideal.mem_map_of_mem _ hlow)
  have hunit : IsUnit (algebraMap _ (GLCoord R n)
      ((Matrix.det (Matrix.mvPolynomialX (Fin n) (Fin n) R)) ^ k)) := by
    rw [map_pow]
    exact (IsLocalization.Away.algebraMap_isUnit _).pow k
  rw [← hpk] at hmap
  obtain ⟨u, hu⟩ := hunit
  have := (borelCoordIdeal R n).mul_mem_right (↑u⁻¹ : GLCoord R n) hmap
  rwa [← hu, mul_assoc, Units.mul_inv, mul_one] at this

/-- Evaluating `𝒪(GLₙ)` at a matrix, on the image of a polynomial. -/
theorem glPointOfMatrix_algebraMap {A : Type*} [CommRing A] [Algebra R A]
    (g : Matrix (Fin n) (Fin n) A) (hg : IsUnit g.det) (p : MvPolynomial (Fin n × Fin n) R) :
    glPointOfMatrix R g hg (algebraMap _ _ p) =
      aeval (fun ij : Fin n × Fin n => g ij.1 ij.2) p := by
  rw [glPointOfMatrix, IsLocalization.Away.liftAlgHom_apply, IsLocalization.Away.lift_eq]
  rfl

end Ring

section Domain

variable (R : Type u) [CommRing R] (n : ℕ)

/-- `∏ᵢ xᵢᵢ`. -/
abbrev diagProd : MvPolynomial (Fin n × Fin n) R :=
  ∏ i, X (i, i)

theorem diagProd_ne_zero [IsDomain R] : diagProd R n ≠ 0 :=
  Finset.prod_ne_zero_iff.mpr fun _ _ => X_ne_zero _

/-- `R[xᵢⱼ][(∏ xᵢᵢ)⁻¹]`. -/
abbrev UpperRing : Type u :=
  Localization.Away (diagProd R n)

/-- The generic upper triangular matrix over `R[xᵢⱼ][(∏ xᵢᵢ)⁻¹]`. -/
def upperGenericMatrix : Matrix (Fin n) (Fin n) (UpperRing R n) :=
  Matrix.of fun i j =>
    algebraMap (MvPolynomial (Fin n × Fin n) R) (UpperRing R n) (if i ≤ j then X (i, j) else 0)

theorem upperGenericMatrix_blockTriangular : (upperGenericMatrix R n).BlockTriangular id := by
  intro i j h
  have h' : ¬ i ≤ j := not_le.mpr h
  simp [upperGenericMatrix, h']

theorem det_upperGenericMatrix :
    (upperGenericMatrix R n).det = algebraMap _ _ (diagProd R n) := by
  rw [Matrix.det_of_isUpperTriangular (upperGenericMatrix_blockTriangular R n), map_prod]
  simp [upperGenericMatrix]

theorem isUnit_det_upperGenericMatrix : IsUnit (upperGenericMatrix R n).det := by
  rw [det_upperGenericMatrix]
  exact IsLocalization.Away.algebraMap_isUnit _

/-- The embedding `𝒪(B) → R[xᵢⱼ][(∏ xᵢᵢ)⁻¹]`. -/
def toUpperRing : BorelCoord R n →ₐ[R] UpperRing R n :=
  borelPointOfMatrix R (upperGenericMatrix R n) (isUnit_det_upperGenericMatrix R n)
    (upperGenericMatrix_blockTriangular R n)

theorem aeval_upperGenericMatrix (p : MvPolynomial (Fin n × Fin n) R) :
    aeval (fun ij : Fin n × Fin n => upperGenericMatrix R n ij.1 ij.2) p =
      algebraMap _ (UpperRing R n) (upperPart p) := by
  have h : aeval (fun ij : Fin n × Fin n => upperGenericMatrix R n ij.1 ij.2) =
      (IsScalarTower.toAlgHom R (MvPolynomial (Fin n × Fin n) R) (UpperRing R n)).comp
        upperPart := by
    apply MvPolynomial.algHom_ext
    intro ij
    simp only [aeval_X, AlgHom.comp_apply, upperPart, IsScalarTower.coe_toAlgHom',
      upperGenericMatrix, Matrix.of_apply]
  exact DFunLike.congr_fun h p

theorem toUpperRing_injective [IsDomain R] : Function.Injective (toUpperRing R n) := by
  rw [injective_iff_map_eq_zero]
  intro g hg
  obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective g
  obtain ⟨⟨p, ⟨_, k, rfl⟩⟩, hpk⟩ := IsLocalization.surj
    (Submonoid.powers (Matrix.det (Matrix.mvPolynomialX (Fin n) (Fin n) R))) f
  simp only at hpk
  rw [Ideal.Quotient.eq_zero_iff_mem]
  refine mem_borelCoordIdeal_of_upperPart_eq_zero f p k hpk ?_
  have h := congrArg (glPointOfMatrix R (upperGenericMatrix R n)
    (isUnit_det_upperGenericMatrix R n)) hpk
  have hf0 : glPointOfMatrix R (upperGenericMatrix R n) (isUnit_det_upperGenericMatrix R n) f = 0 :=
    hg
  rw [map_mul, hf0, zero_mul, glPointOfMatrix_algebraMap, aeval_upperGenericMatrix] at h
  have hinj : Function.Injective (algebraMap (MvPolynomial (Fin n × Fin n) R) (UpperRing R n)) :=
    IsLocalization.injective (M := Submonoid.powers (diagProd R n)) (UpperRing R n)
      (powers_le_nonZeroDivisors_of_noZeroDivisors (diagProd_ne_zero R n))
  exact hinj (h.symm.trans (map_zero _).symm)

instance instIsDomainBorelCoord [IsDomain R] : IsDomain (BorelCoord R n) :=
  have : IsDomain (UpperRing R n) := IsLocalization.isDomain_localization
    (powers_le_nonZeroDivisors_of_noZeroDivisors (diagProd_ne_zero R n))
  (toUpperRing_injective R n).isDomain _

end Domain

section Density

variable {K : Type u} [Field K] [Infinite K] {n : ℕ}

/-- **Density of `B(K)` in `B`.** -/
theorem mem_borelCoordIdeal_of_forall (f : GLCoord K n)
    (hf : ∀ (b : Matrix (Fin n) (Fin n) K) (hb : IsUnit b.det), b.BlockTriangular id →
      glPointOfMatrix K b hb f = 0) : f ∈ borelCoordIdeal K n := by
  obtain ⟨⟨p, ⟨_, k, rfl⟩⟩, hpk⟩ := IsLocalization.surj
    (Submonoid.powers (Matrix.det (Matrix.mvPolynomialX (Fin n) (Fin n) K))) f
  simp only at hpk
  refine mem_borelCoordIdeal_of_upperPart_eq_zero f p k hpk ?_
  -- `upperPart p * ∏ xᵢᵢ` vanishes everywhere
  have hq : upperPart p * diagProd K n = 0 := by
    apply MvPolynomial.funext
    intro x
    let b : Matrix (Fin n) (Fin n) K := Matrix.of fun i j => if i ≤ j then x (i, j) else 0
    have hup : b.BlockTriangular id := by
      intro i j h
      have h' : ¬ i ≤ j := not_le.mpr h
      simp [b, h']
    have hdet : b.det = ∏ i, x (i, i) := by
      rw [Matrix.det_of_isUpperTriangular hup]
      simp [b]
    have hcomp : (aeval (R := K) x).comp upperPart =
        aeval (fun ij : Fin n × Fin n => b ij.1 ij.2) := by
      apply MvPolynomial.algHom_ext
      intro ij
      simp only [AlgHom.comp_apply, upperPart, aeval_X]
      split_ifs with h <;> simp [b, h]
    have heval : eval x (upperPart p) = aeval (fun ij : Fin n × Fin n => b ij.1 ij.2) p := by
      change aeval (R := K) x (upperPart p) = _
      rw [← hcomp, AlgHom.comp_apply]
    rw [map_zero, eval_mul, heval]
    by_cases h0 : ∏ i, x (i, i) = 0
    · simp [diagProd, h0]
    · have hb : IsUnit b.det := by
        rw [hdet]
        exact isUnit_iff_ne_zero.mpr h0
      have h := congrArg (glPointOfMatrix K b hb) hpk
      rw [map_mul, hf b hb hup, zero_mul, glPointOfMatrix_algebraMap] at h
      rw [← h, zero_mul]
  exact (mul_eq_zero.mp hq).resolve_right (diagProd_ne_zero K n)

/-- `𝒪(B)` embeds into the functions on `B(K)`. -/
theorem borelCoord_eq_zero_of_forall (g : BorelCoord K n)
    (hg : ∀ (b : Matrix (Fin n) (Fin n) K) (hb : IsUnit b.det) (hup : b.BlockTriangular id),
      borelPointOfMatrix K b hb hup g = 0) : g = 0 := by
  obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective g
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact mem_borelCoordIdeal_of_forall f fun b hb hup => hg b hb hup

end Density

end FlagVarieties
