import Schubert.RS.PolynomialSl2
import Schubert.RS.PolynomialDiagonalWeights

namespace Schubert.RS.Representation
noncomputable section
attribute [local instance 100] LieRing.ofAssociativeRing

/-- The actual polynomial representation restricted to the sl2 generated by
one root and its opposite, on any subspace stable under both operators. -/
def polynomialRootModule {n : ℕ} (a b : Fin n) (hab : a≠b)
    (S : Submodule ℂ (MatrixPolynomial n))
    (hE : ∀ p∈S, matrixUnitDerivation a b p∈S)
    (hF : ∀ p∈S, matrixUnitDerivation b a p∈S) :
    LieSubmodule ℂ ((polynomialSl2Triple a b hab).toLieSubalgebra ℂ) (MatrixPolynomial n) where
  toSubmodule := S
  lie_mem := by
    intro z p hp
    change z.val p∈S
    obtain ⟨u,v,w,hz⟩ := (IsSl2Triple.mem_toLieSubalgebra_iff
      (R := ℂ) (t := polynomialSl2Triple a b hab)).mp z.property
    rw [hz,LinearMap.add_apply,LinearMap.add_apply,LinearMap.smul_apply,
      LinearMap.smul_apply,LinearMap.smul_apply]
    apply S.add_mem
    · exact S.add_mem (S.smul_mem u (hE p hp)) (S.smul_mem v (hF p hp))
    · apply S.smul_mem
      change matrixUnitDerivation a b (matrixUnitDerivation b a p)-
        matrixUnitDerivation b a (matrixUnitDerivation a b p)∈S
      exact S.sub_mem (hE _ (hF p hp)) (hF _ (hE p hp))

def homogeneousPolynomialRootModule {n : ℕ} (a b : Fin n) (hab : a≠b) (D : ℕ) :
    LieSubmodule ℂ ((polynomialSl2Triple a b hab).toLieSubalgebra ℂ) (MatrixPolynomial n) :=
  polynomialRootModule a b hab (MvPolynomial.homogeneousSubmodule (Fin n × Fin n) ℂ D)
    (fun p hp => matrixUnit_homogeneous a b p hp)
    (fun p hp => matrixUnit_homogeneous b a p hp)

instance homogeneousPolynomialRootModule_finite {n : ℕ} (a b : Fin n) (hab : a≠b) (D : ℕ) :
    FiniteDimensional ℂ (homogeneousPolynomialRootModule a b hab D) :=
  homogeneousPolynomial_finite n D

theorem polynomialRootCartan_weight {n : ℕ} (a b : Fin n) (p : MatrixPolynomial n)
    (v : Weight n) (hp : ∀ t, polynomialTorus n t p=integerWeightScalar v t • p) :
    polynomialRootCartan a b p=((v a-v b : ℤ):ℂ) • p := by
  change matrixUnitDerivation a a p-matrixUnitDerivation b b p=_
  rw [diagonalDerivation_of_weight a p v hp,diagonalDerivation_of_weight b p v hp,
    ← sub_smul,Int.cast_sub]

end
end Schubert.RS.Representation
