import RSCounterexample.FlagVarieties.Normality.Fulton.Main
import RSCounterexample.FlagVarieties.PointModel.ClosureRelation
import RSCounterexample.FlagVarieties.Schubert.Orbit
import RSCounterexample.FlagVarieties.LineBundle.Density

/-!
# The ring half of the comparison with the scheme-level Schubert varieties

The orbit ideal `FlagVarieties.schubertOrbitIdeal K n w ⊆ 𝒪(GL_n)` is the kernel of the comorphism
of `B × B → GL_n`, `(b, b') ↦ b ẇ b'`. Over a field `K` of characteristic `0` it is the ideal of
`π⁻¹ X_w` used in the ring model (`schubertOrbitIdeal_eq_orbitIdeal_lowerSet`):

    schubertOrbitIdeal K n w = cellIdeal K w = orbitIdeal K (lowerSet w).

* `glEval_eq_glPointOfMatrix`: the evaluation `glEval g` is `glPointOfMatrix`.
* `pairLift_comp_schubertOrbitComorphism`: at the `K`-point `(b, b')` of `B × B`, the comorphism is
  evaluation at `b ẇ b'`.
* `borelPairRing_eq_zero_of_forall`: `𝒪(B) ⊗ 𝒪(B)` embeds into the functions on `B(K) × B(K)`
  (the density of `B(K)` in `B` and a basis of `𝒪(B)` over `K`).
* `orbitIdeal_eq_iInf_schubertOrbitIdeal`: for every finite set `S`, `orbitIdeal K S` is the
  intersection of the orbit ideals of its elements (unions).

**Transfer to the scheme level.** By `preimageIdeal_schubertVariety_eq_schubertOrbitIdeal`,
`preimageIdeal (schubertVariety w) = schubertOrbitIdeal w` over every field. Hence
`preimageIdeal_schubertVariety_eq_fultonIdeal`: the ideal of the scheme-theoretic preimage
`π⁻¹(X_w) ⊆ GL_n` is generated by Fulton's minors (and by the forbidden flag minors).
-/

open Schubert Demazure.FlagModule Demazure.SchubertUnions FinPermutation
open GLRep (glEval)
open scoped TensorProduct

namespace FlagVarieties.PointModel

noncomputable section

set_option backward.isDefEq.respectTransparency false

variable {K : Type*} [Field K] {n : ℕ}

/-! ### Evaluation and points of `GL_n` -/

theorem glEval_genericMatrix (g : GL (Fin n) K) (i j : Fin n) :
    glEval g (FlagVarieties.genericMatrix K n i j) = (g : Matrix (Fin n) (Fin n) K) i j := by
  rw [FlagVarieties.genericMatrix, TauCeti.GeneralLinear.localizedGenericMatrix_apply,
    TauCeti.GeneralLinear.coordinateRingMap_apply, glEval_algebraMap_eq_evalAt, evalAt_X]

/-- **The evaluations of the ring model are the points of `GL_n`.** -/
theorem glEval_eq_glPointOfMatrix (g : GL (Fin n) K) :
    glEval g = FlagVarieties.glPointOfMatrix K (g : Matrix (Fin n) (Fin n) K)
      ((Matrix.isUnit_iff_isUnit_det _).mp g.isUnit) := by
  apply FlagVarieties.genericMatrix_algHom_ext
  rw [FlagVarieties.genericMatrix_map_glPointOfMatrix]
  ext i j
  rw [Matrix.map_apply, glEval_genericMatrix]

theorem permMatrix_eq_permMat (w : Equiv.Perm (Fin n)) :
    FlagVarieties.permMatrix (A := K) n w = permMat K w := by
  ext r c
  rw [FlagVarieties.permMatrix_apply]
  rfl

theorem permMatrix_map {A B : Type*} [CommRing A] [CommRing B] (f : A →+* B)
    (w : Equiv.Perm (Fin n)) :
    (FlagVarieties.permMatrix (A := A) n w).map f = FlagVarieties.permMatrix (A := B) n w := by
  ext r c
  rw [Matrix.map_apply, FlagVarieties.permMatrix_apply, FlagVarieties.permMatrix_apply]
  split_ifs <;> simp

/-- At the `K`-point `(b₁, b₂)` of `B × B`, the comorphism of `(b, b') ↦ b ẇ b'` is the evaluation
at `b₁ ẇ b₂`. -/
theorem pairLift_comp_schubertOrbitComorphism (w : Equiv.Perm (Fin n))
    (b₁ b₂ : Matrix (Fin n) (Fin n) K) (hb₁ : IsUnit b₁.det) (hup₁ : b₁.BlockTriangular id)
    (hb₂ : IsUnit b₂.det) (hup₂ : b₂.BlockTriangular id) (h : IsUnit (b₁ * permMat K w * b₂).det) :
    (FlagVarieties.pairLift (FlagVarieties.borelPointOfMatrix K b₁ hb₁ hup₁)
        (FlagVarieties.borelPointOfMatrix K b₂ hb₂ hup₂)).comp
      (FlagVarieties.schubertOrbitComorphism K n w) =
      FlagVarieties.glPointOfMatrix K (b₁ * permMat K w * b₂) h := by
  apply FlagVarieties.genericMatrix_algHom_ext
  rw [FlagVarieties.genericMatrix_map_glPointOfMatrix, AlgHom.coe_comp, ← Matrix.map_map,
    FlagVarieties.schubertOrbitComorphism, FlagVarieties.genericMatrix_map_glPointOfMatrix,
    FlagVarieties.schubertOrbitMatrix]
  set φ := FlagVarieties.pairLift (FlagVarieties.borelPointOfMatrix K b₁ hb₁ hup₁)
    (FlagVarieties.borelPointOfMatrix K b₂ hb₂ hup₂)
  have h₁ : ((FlagVarieties.borelMatrix K n).map (FlagVarieties.pairInl K n)).map φ = b₁ := by
    rw [Matrix.map_map, ← AlgHom.coe_comp, FlagVarieties.pairLift_comp_pairInl,
      FlagVarieties.borelMatrix_map_borelPointOfMatrix]
  have h₂ : ((FlagVarieties.borelMatrix K n).map (FlagVarieties.pairInr K n)).map φ = b₂ := by
    rw [Matrix.map_map, ← AlgHom.coe_comp, FlagVarieties.pairLift_comp_pairInr,
      FlagVarieties.borelMatrix_map_borelPointOfMatrix]
  rw [FlagVarieties.map_mul_algHom, FlagVarieties.map_mul_algHom, h₁, h₂]
  rw [show (FlagVarieties.permMatrix n w).map φ = FlagVarieties.permMatrix (A := K) n w from
    permMatrix_map φ.toRingHom w, permMatrix_eq_permMat]

/-! ### Density of `B(K) × B(K)` in `B × B` -/

/-- **`𝒪(B) ⊗ 𝒪(B)` embeds into the functions on `B(K) × B(K)`.** -/
theorem borelPairRing_eq_zero_of_forall [Infinite K] (x : FlagVarieties.BorelPairRing K n)
    (hx : ∀ (b₁ b₂ : Matrix (Fin n) (Fin n) K) (hb₁ : IsUnit b₁.det)
      (hup₁ : b₁.BlockTriangular id) (hb₂ : IsUnit b₂.det) (hup₂ : b₂.BlockTriangular id),
      FlagVarieties.pairLift (FlagVarieties.borelPointOfMatrix K b₁ hb₁ hup₁)
        (FlagVarieties.borelPointOfMatrix K b₂ hb₂ hup₂) x = 0) : x = 0 := by
  classical
  let 𝒞 := Module.Free.chooseBasis K (FlagVarieties.BorelCoord K n)
  let e := TensorProduct.equivFinsuppOfBasisRight (M := FlagVarieties.BorelCoord K n) 𝒞
  let x' : FlagVarieties.BorelCoord K n ⊗[K] FlagVarieties.BorelCoord K n := x
  by_contra hne
  have hex : e x' ≠ 0 := fun h => hne (e.injective (h.trans e.map_zero.symm))
  obtain ⟨i₀, hi₀⟩ := Finsupp.ne_iff.mp hex
  rw [Finsupp.zero_apply] at hi₀
  obtain ⟨b₁, hb₁, hup₁, h₁⟩ : ∃ (b₁ : Matrix (Fin n) (Fin n) K) (hb₁ : IsUnit b₁.det)
      (hup₁ : b₁.BlockTriangular id),
      FlagVarieties.borelPointOfMatrix K b₁ hb₁ hup₁ (e x' i₀) ≠ 0 := by
    by_contra h
    push Not at h
    exact hi₀ (FlagVarieties.borelCoord_eq_zero_of_forall _ h)
  set p₁ := FlagVarieties.borelPointOfMatrix K b₁ hb₁ hup₁
  let c : _ →₀ K := Finsupp.mapRange p₁ (map_zero p₁) (e x')
  let y : FlagVarieties.BorelCoord K n := Finsupp.linearCombination K 𝒞 c
  have hy : 𝒞.repr y i₀ = p₁ (e x' i₀) := by
    rw [Module.Basis.repr_linearCombination, Finsupp.mapRange_apply]
  have hy0 : y ≠ 0 := fun h => h₁ (by rw [← hy, h, map_zero, Finsupp.zero_apply])
  obtain ⟨b₂, hb₂, hup₂, h₂⟩ : ∃ (b₂ : Matrix (Fin n) (Fin n) K) (hb₂ : IsUnit b₂.det)
      (hup₂ : b₂.BlockTriangular id), FlagVarieties.borelPointOfMatrix K b₂ hb₂ hup₂ y ≠ 0 := by
    by_contra h
    push Not at h
    exact hy0 (FlagVarieties.borelCoord_eq_zero_of_forall _ h)
  set p₂ := FlagVarieties.borelPointOfMatrix K b₂ hb₂ hup₂
  apply h₂
  have hxsum : x' = (e x').sum fun i a => a ⊗ₜ[K] 𝒞 i := by
    rw [← TensorProduct.equivFinsuppOfBasisRight_symm_apply, LinearEquiv.symm_apply_apply]
  have hval := hx b₁ b₂ hb₁ hup₁ hb₂ hup₂
  change FlagVarieties.pairLift p₁ p₂ x' = 0 at hval
  rw [hxsum, map_finsuppSum] at hval
  have hterm : ∀ i a, FlagVarieties.pairLift p₁ p₂ (a ⊗ₜ[K] 𝒞 i) = p₁ a * p₂ (𝒞 i) :=
    fun i a => Algebra.TensorProduct.lift_tmul _ _ _ a (𝒞 i)
  have hval' : ((e x').sum fun i a => p₁ a * p₂ (𝒞 i)) = 0 :=
    (Finsupp.sum_congr fun i _ => (hterm i (e x' i)).symm).trans hval
  show p₂ (Finsupp.linearCombination K 𝒞 c) = 0
  rw [Finsupp.linearCombination_apply, map_finsuppSum,
    Finsupp.sum_mapRange_index (fun i => by rw [zero_smul, map_zero])]
  simp only [map_smul, smul_eq_mul]
  exact hval'

/-! ### The comparison of orbit ideals -/

/-- **The orbit ideal is the ideal of the cell `B ẇ B`** (over an infinite field). -/
theorem schubertOrbitIdeal_eq_cellIdeal [Infinite K] (w : Equiv.Perm (Fin n)) :
    FlagVarieties.schubertOrbitIdeal K n w = cellIdeal K w := by
  ext t
  rw [FlagVarieties.schubertOrbitIdeal, RingHom.mem_ker, mem_cellIdeal]
  constructor
  · rintro ht g ⟨b₁, b₂, h₁, h₂, rfl⟩
    have hb₁ := (Matrix.isUnit_iff_isUnit_det _).mp b₁.isUnit
    have hb₂ := (Matrix.isUnit_iff_isUnit_det _).mp b₂.isUnit
    have hg := (Matrix.isUnit_iff_isUnit_det _).mp (b₁ * permGL K w * b₂).isUnit
    rw [glEval_eq_glPointOfMatrix]
    have e := congrArg (fun f => f t) (pairLift_comp_schubertOrbitComorphism w
      (b₁ : Matrix (Fin n) (Fin n) K) (b₂ : Matrix (Fin n) (Fin n) K) hb₁ h₁ hb₂ h₂
      (by simpa [Units.val_mul] using hg))
    simp only [AlgHom.comp_apply] at e
    have ht' : (FlagVarieties.schubertOrbitComorphism K n w) t = 0 := ht
    rw [ht', map_zero] at e
    have hcoe : ((b₁ * permGL K w * b₂ : GL (Fin n) K) : Matrix (Fin n) (Fin n) K) =
        (b₁ : Matrix (Fin n) (Fin n) K) * permMat K w * (b₂ : Matrix (Fin n) (Fin n) K) := by
      simp [Units.val_mul]
    simp only [hcoe]
    exact e.symm
  · intro ht
    change (FlagVarieties.schubertOrbitComorphism K n w) t = 0
    refine borelPairRing_eq_zero_of_forall _ fun b₁ b₂ hb₁ hup₁ hb₂ hup₂ => ?_
    have hg : IsUnit (b₁ * permMat K w * b₂).det := by
      rw [Matrix.det_mul, Matrix.det_mul]
      refine (hb₁.mul ?_).mul hb₂
      rw [← permMatrix_eq_permMat]
      exact FlagVarieties.isUnit_det_permMatrix n w
    have e := congrArg (fun f => f t)
      (pairLift_comp_schubertOrbitComorphism w b₁ b₂ hb₁ hup₁ hb₂ hup₂ hg)
    simp only [AlgHom.comp_apply] at e
    rw [e]
    let g : GL (Fin n) K := unitOfDet _ hg
    have hgcell : g ∈ bruhatCell K w :=
      ⟨unitOfDet b₁ hb₁, unitOfDet b₂ hb₂, by unfold IsBorel; rw [coe_unitOfDet]; exact hup₁,
        by unfold IsBorel; rw [coe_unitOfDet]; exact hup₂, by
          apply Units.ext
          simp [g, Units.val_mul]⟩
    have h0 := ht g hgcell
    rwa [glEval_eq_glPointOfMatrix] at h0

/-- **The ring half of the comparison** (characteristic `0`): the orbit ideal of `w` is the ideal
of `π⁻¹ X_w = ⋃_{v ≤ w} B v̇ B` of the ring model. -/
theorem schubertOrbitIdeal_eq_orbitIdeal_lowerSet [CharZero K] (w : Equiv.Perm (Fin n)) :
    FlagVarieties.schubertOrbitIdeal K n w = orbitIdeal K (lowerSet w) := by
  have : Infinite K := Infinite.of_injective (Nat.cast : ℕ → K) Nat.cast_injective
  rw [schubertOrbitIdeal_eq_cellIdeal, orbitIdeal_lowerSet (standardMonomialTheory_of_charZero K)]

/-- **Unions**: for every finite set `S` of permutations, the ideal of `orbitSet K S` is the
intersection of the orbit ideals. -/
theorem orbitIdeal_eq_iInf_schubertOrbitIdeal [Infinite K] (S : Finset (Equiv.Perm (Fin n))) :
    orbitIdeal K S = ⨅ w ∈ S, FlagVarieties.schubertOrbitIdeal K n w := by
  ext t
  simp only [Submodule.mem_iInf, schubertOrbitIdeal_eq_cellIdeal, mem_cellIdeal, mem_orbitIdeal,
    mem_orbitSet]
  constructor
  · intro h w hw g hg
    exact h g ⟨w, hw, hg⟩
  · rintro h g ⟨w, hw, hg⟩
    exact h w hw g hg

/-- For a Bruhat ideal `S`, also `orbitIdeal K S = ⋂_{w ∈ S} orbitIdeal K (lowerSet w)`. -/
theorem orbitIdeal_eq_iInf_lowerSet [CharZero K] (S : Finset (Equiv.Perm (Fin n))) :
    orbitIdeal K S = ⨅ w ∈ S, orbitIdeal K (lowerSet w) := by
  have : Infinite K := Infinite.of_injective (Nat.cast : ℕ → K) Nat.cast_injective
  rw [orbitIdeal_eq_iInf_schubertOrbitIdeal]
  simp only [schubertOrbitIdeal_eq_orbitIdeal_lowerSet]

/-! ### Transfer to the scheme level -/

/-- The ideal of `π⁻¹(X_w)` is the ideal of the ring model. -/
theorem preimageIdeal_schubertVariety_eq_orbitIdeal [CharZero K] (w : Equiv.Perm (Fin n)) :
    FlagVarieties.preimageIdeal K n (FlagVarieties.schubertVariety K n w) =
      orbitIdeal K (lowerSet w) := by
  rw [FlagVarieties.preimageIdeal_schubertVariety_eq_schubertOrbitIdeal K n w,
      schubertOrbitIdeal_eq_orbitIdeal_lowerSet]

/-- **Fulton's rank conditions define `X_w` scheme-theoretically** (scheme form): the ideal of
`π⁻¹(X_w) ⊆ GL_n` is generated by Fulton's minors. -/
theorem preimageIdeal_schubertVariety_eq_fultonIdeal [IsAlgClosed K] [CharZero K]
    (w : Equiv.Perm (Fin n)) :
    FlagVarieties.preimageIdeal K n (FlagVarieties.schubertVariety K n w) =
      (fultonIdeal K w).map (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n)) := by
  rw [preimageIdeal_schubertVariety_eq_orbitIdeal, orbitIdeal_lowerSet_eq_fultonIdeal]

/-- The same with the forbidden flag minors (the vanishing Plücker coordinates). -/
theorem preimageIdeal_schubertVariety_eq_schubertIdeal [IsAlgClosed K] [CharZero K]
    (w : Equiv.Perm (Fin n)) :
    FlagVarieties.preimageIdeal K n (FlagVarieties.schubertVariety K n w) =
      (schubertIdeal K w).map (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n)) := by
  rw [preimageIdeal_schubertVariety_eq_orbitIdeal, orbitIdeal_lowerSet_eq]

end

end FlagVarieties.PointModel
