import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Coordinate.HopfAlgebra
import Mathlib.LinearAlgebra.Matrix.Block
import Mathlib.RingTheory.TensorProduct.Basic
import Mathlib.LinearAlgebra.Matrix.MvPolynomial

/-!
# The coordinate ring model of sections

Ring-level objects behind the line bundles `𝓛(η)` on the flag scheme, over a commutative ring `R`.

* `FlagVarieties.GLCoord R n`: the coordinate ring `𝒪(GLₙ) = R[xᵢⱼ][det⁻¹]` (Tau Ceti).
* `FlagVarieties.borelCoordIdeal R n`: the ideal of the upper triangular subgroup `B`, generated by
  the entries `xᵢⱼ` with `i > j`; `BorelCoord R n = 𝒪(B)`.
* `FlagVarieties.borelCharacterUnit R n η`: the character `b ↦ ∏ᵢ bᵢᵢ^{ηᵢ}` of `B`, a unit of
  `𝒪(B)`.
* `FlagVarieties.rightCoaction R n`: the comorphism `𝒪(GLₙ) → 𝒪(GLₙ) ⊗ 𝒪(B)` of the right
  multiplication `GLₙ × B → GLₙ`, `(g, b) ↦ g b`.
* `FlagVarieties.quotientSemiInvariants R n J η`: for an ideal `J` of `𝒪(GLₙ)` (the ideal of a
  closed subscheme `Z ⊆ GLₙ`), the classes `f ∈ 𝒪(GLₙ) ⧸ J` with `f(g b) = η(b)⁻¹ f(g)`, i.e.
  `ρ(f) = f ⊗ η⁻¹` in `(𝒪(GLₙ) ⧸ J) ⊗ 𝒪(B)`. This is `(𝒪(Z))^{(B, η)}`, the model of
  `H⁰(X, 𝓛(η))` when `Z = π⁻¹(X)`.
-/

noncomputable section

namespace FlagVarieties

open TensorProduct

universe u

variable (R : Type u) [CommRing R] (n : ℕ)

/-- The coordinate ring `𝒪(GLₙ) = R[xᵢⱼ][det⁻¹]`. -/
abbrev GLCoord : Type u :=
  TauCeti.GeneralLinear.CoordinateRing R n

/-- The generic matrix `(xᵢⱼ)` over `𝒪(GLₙ)`. -/
abbrev genericMatrix : Matrix (Fin n) (Fin n) (GLCoord R n) :=
  TauCeti.GeneralLinear.localizedGenericMatrix R n

/-- The ideal of the Borel subgroup `B ⊆ GLₙ` of upper triangular matrices: it is generated by the
entries of the generic matrix below the diagonal. -/
def borelCoordIdeal : Ideal (GLCoord R n) :=
  Ideal.span (Set.range fun p : {p : Fin n × Fin n // p.2 < p.1} => genericMatrix R n p.1.1 p.1.2)

/-- The coordinate ring `𝒪(B) = 𝒪(GLₙ) ⧸ borelCoordIdeal`. -/
abbrev BorelCoord : Type u :=
  GLCoord R n ⧸ borelCoordIdeal R n

/-- The generic upper triangular matrix over `𝒪(B)`. -/
def borelMatrix : Matrix (Fin n) (Fin n) (BorelCoord R n) :=
  (genericMatrix R n).map (Ideal.Quotient.mk (borelCoordIdeal R n))

theorem borelMatrix_blockTriangular : (borelMatrix R n).BlockTriangular id := by
  intro i j hji
  simp only [borelMatrix, Matrix.map_apply]
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span ⟨⟨(i, j), hji⟩, rfl⟩

variable {R n} in
/-- The determinant commutes with ring homomorphisms applied entrywise. -/
theorem det_map_ringHom {A B : Type*} [CommRing A] [CommRing B] (f : A →+* B)
    (M : Matrix (Fin n) (Fin n) A) : (M.map f).det = f M.det :=
  (RingHom.map_det f M).symm

variable {R n} in
theorem isUnit_det_map_ringHom {A B : Type*} [CommRing A] [CommRing B] (f : A →+* B)
    {M : Matrix (Fin n) (Fin n) A} (hM : IsUnit M.det) : IsUnit (M.map f).det := by
  rw [det_map_ringHom]
  exact hM.map f

variable {R n} in
/-- `Matrix.map` along an algebra homomorphism is multiplicative. -/
theorem map_mul_algHom {A B : Type*} [CommRing A] [CommRing B] [Algebra R A] [Algebra R B]
    (f : A →ₐ[R] B) (M N : Matrix (Fin n) (Fin n) A) : (M * N).map f = M.map f * N.map f :=
  Matrix.map_mul (f := f.toRingHom)

theorem isUnit_det_borelMatrix : IsUnit (borelMatrix R n).det :=
  isUnit_det_map_ringHom _ (TauCeti.GeneralLinear.isUnit_det_localizedGenericMatrix R n)

/-- The diagonal entries of the generic upper triangular matrix are units of `𝒪(B)`. -/
theorem isUnit_borelMatrix_diag (i : Fin n) : IsUnit (borelMatrix R n i i) := by
  have h := isUnit_det_borelMatrix R n
  rw [Matrix.det_of_isUpperTriangular (borelMatrix_blockTriangular R n)] at h
  exact isUnit_of_dvd_unit
    (Finset.dvd_prod_of_mem (fun j => borelMatrix R n j j) (Finset.mem_univ i)) h

/-- The diagonal coordinate `bᵢᵢ`, a unit of `𝒪(B)`. -/
def borelDiag (i : Fin n) : (BorelCoord R n)ˣ :=
  (isUnit_borelMatrix_diag R n i).unit

/-- The character `η : B → 𝔾ₘ`, `b ↦ ∏ᵢ bᵢᵢ^{ηᵢ}`, as a unit of `𝒪(B)`. -/
def borelCharacterUnit (η : Fin n → ℤ) : (BorelCoord R n)ˣ :=
  ∏ i, borelDiag R n i ^ η i


/-! ### Points of `GLₙ` given by invertible matrices -/

variable {n} in
/-- The `A`-point of `GLₙ` given by a matrix with invertible determinant: the `R`-algebra map
`𝒪(GLₙ) → A` evaluating the generic matrix at `g`. -/
def glPointOfMatrix {A : Type*} [CommRing A] [Algebra R A] (g : Matrix (Fin n) (Fin n) A)
    (hg : IsUnit g.det) : GLCoord R n →ₐ[R] A :=
  IsLocalization.Away.liftAlgHom (Matrix.det (Matrix.mvPolynomialX (Fin n) (Fin n) R))
    (f := MvPolynomial.aeval fun ij : Fin n × Fin n => g ij.1 ij.2) (by
      rw [AlgHom.map_det, Matrix.mvPolynomialX_mapMatrix_aeval]
      exact hg)

variable {n} in
theorem genericMatrix_map_glPointOfMatrix {A : Type*} [CommRing A] [Algebra R A]
    (g : Matrix (Fin n) (Fin n) A) (hg : IsUnit g.det) :
    (genericMatrix R n).map (glPointOfMatrix R g hg) = g := by
  ext i j
  rw [Matrix.map_apply, genericMatrix, TauCeti.GeneralLinear.localizedGenericMatrix_apply,
    TauCeti.GeneralLinear.coordinateRingMap_apply, glPointOfMatrix,
    IsLocalization.Away.liftAlgHom_apply, IsLocalization.Away.lift_eq]
  simp

variable {R n} in
/-- `R`-algebra maps out of `𝒪(GLₙ)` are determined by the image of the generic matrix. -/
theorem genericMatrix_algHom_ext {A : Type*} [CommRing A] [Algebra R A]
    {k k' : GLCoord R n →ₐ[R] A}
    (h : (genericMatrix R n).map k = (genericMatrix R n).map k') : k = k' := by
  have hpoly : k.comp (IsScalarTower.toAlgHom R (MvPolynomial (Fin n × Fin n) R) (GLCoord R n)) =
      k'.comp (IsScalarTower.toAlgHom R (MvPolynomial (Fin n × Fin n) R) (GLCoord R n)) := by
    apply MvPolynomial.algHom_ext
    intro ij
    have := congrFun (congrFun h ij.1) ij.2
    rw [Matrix.map_apply, Matrix.map_apply, genericMatrix,
      TauCeti.GeneralLinear.localizedGenericMatrix_apply,
      TauCeti.GeneralLinear.coordinateRingMap_apply] at this
    simpa using this
  apply AlgHom.toRingHom_injective
  apply IsLocalization.ringHom_ext (Submonoid.powers
    (Matrix.det (Matrix.mvPolynomialX (Fin n) (Fin n) R)))
  exact congrArg AlgHom.toRingHom hpoly

variable {R n} in
/-- `R`-algebra maps out of `𝒪(B)` are determined by the image of the generic upper triangular
matrix. -/
theorem borelMatrix_algHom_ext {A : Type*} [CommRing A] [Algebra R A]
    {k k' : BorelCoord R n →ₐ[R] A}
    (h : (borelMatrix R n).map k = (borelMatrix R n).map k') : k = k' := by
  apply Ideal.Quotient.algHom_ext
  apply genericMatrix_algHom_ext
  exact h

variable {n} in
/-- An upper triangular matrix with invertible determinant is a point of `B`. -/
def borelPointOfMatrix {A : Type*} [CommRing A] [Algebra R A] (b : Matrix (Fin n) (Fin n) A)
    (hb : IsUnit b.det) (hup : b.BlockTriangular id) : BorelCoord R n →ₐ[R] A :=
  Ideal.Quotient.liftₐ (borelCoordIdeal R n) (glPointOfMatrix R b hb) (by
    have hle : borelCoordIdeal R n ≤ RingHom.ker (glPointOfMatrix R b hb).toRingHom := by
      rw [borelCoordIdeal, Ideal.span_le]
      rintro _ ⟨⟨⟨i, j⟩, hij⟩, rfl⟩
      have h := congrFun (congrFun (genericMatrix_map_glPointOfMatrix R b hb) i) j
      simp only [Matrix.map_apply] at h
      simp only [SetLike.mem_coe, RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, h]
      exact hup hij
    exact fun a ha => hle ha)

variable {n} in
theorem borelMatrix_map_borelPointOfMatrix {A : Type*} [CommRing A] [Algebra R A]
    (b : Matrix (Fin n) (Fin n) A) (hb : IsUnit b.det) (hup : b.BlockTriangular id) :
    (borelMatrix R n).map (borelPointOfMatrix R b hb hup) = b := by
  ext i j
  exact congrFun (congrFun (genericMatrix_map_glPointOfMatrix R b hb) i) j

/-! ### The group structure of `B` -/

/-- The unit of `B`: evaluation at the identity matrix, `𝒪(B) → R`. -/
def borelCounit : BorelCoord R n →ₐ[R] R :=
  borelPointOfMatrix R (1 : Matrix (Fin n) (Fin n) R) (by simp) Matrix.blockTriangular_one

/-- The multiplication of `B`: `𝒪(B) → 𝒪(B) ⊗ 𝒪(B)`, `b ↦ b₁ b₂`. -/
def borelComul : BorelCoord R n →ₐ[R] BorelCoord R n ⊗[R] BorelCoord R n :=
  borelPointOfMatrix R
    ((borelMatrix R n).map (Algebra.TensorProduct.includeLeft : BorelCoord R n →ₐ[R] _) *
      (borelMatrix R n).map (Algebra.TensorProduct.includeRight : BorelCoord R n →ₐ[R] _))
    (by
      rw [Matrix.det_mul]
      exact (isUnit_det_map_ringHom _ (isUnit_det_borelMatrix R n)).mul
        (isUnit_det_map_ringHom _ (isUnit_det_borelMatrix R n)))
    (by
      apply Matrix.BlockTriangular.mul
      · intro i j h
        simp [Matrix.map_apply, borelMatrix_blockTriangular R n h]
      · intro i j h
        simp [Matrix.map_apply, borelMatrix_blockTriangular R n h])

/-- The comorphism `𝒪(GLₙ) → 𝒪(GLₙ) ⊗ 𝒪(B)` of the right multiplication `(g, b) ↦ g b`. -/
def rightCoaction : GLCoord R n →ₐ[R] GLCoord R n ⊗[R] BorelCoord R n :=
  (Algebra.TensorProduct.map (AlgHom.id R (GLCoord R n))
    (Ideal.Quotient.mkₐ R (borelCoordIdeal R n))).comp (TauCeti.GeneralLinear.comul R n)

/-- On the generic matrix, the coaction is the product `X ⊗ B` of the generic matrices. -/
theorem map_rightCoaction_genericMatrix :
    (genericMatrix R n).map (rightCoaction R n) =
      (genericMatrix R n).map (Algebra.TensorProduct.includeLeft : GLCoord R n →ₐ[R] _) *
        (borelMatrix R n).map (Algebra.TensorProduct.includeRight : BorelCoord R n →ₐ[R] _) := by
  have h := TauCeti.GeneralLinear.map_comul_localizedGenericMatrix R n
  ext i j
  have hij := congrArg (fun M => (Algebra.TensorProduct.map (AlgHom.id R (GLCoord R n))
    (Ideal.Quotient.mkₐ R (borelCoordIdeal R n))) (M i j)) h
  simp only [Matrix.map_apply] at hij
  simp only [rightCoaction, Matrix.map_apply, AlgHom.comp_apply, hij, Matrix.mul_apply, map_sum,
    map_mul]
  rfl

/-- The coaction followed by the quotient map of a closed subscheme `Z = Spec (𝒪(GLₙ) ⧸ J)`. -/
def rightCoactionMod (J : Ideal (GLCoord R n)) :
    GLCoord R n →ₐ[R] (GLCoord R n ⧸ J) ⊗[R] BorelCoord R n :=
  (Algebra.TensorProduct.map (Ideal.Quotient.mkₐ R J) (AlgHom.id R (BorelCoord R n))).comp
    (rightCoaction R n)

/-- `J` is stable under right multiplication by `B`: the coaction descends to `𝒪(GLₙ) ⧸ J`. -/
def IsBorelStable (J : Ideal (GLCoord R n)) : Prop :=
  J ≤ RingHom.ker (rightCoactionMod R n J).toRingHom

/-- The `R`-linear map `f ↦ ρ(f) - f ⊗ η⁻¹`, whose kernel consists of the functions on
`Z = Spec (𝒪(GLₙ) ⧸ J)` that are semi-invariant of weight `η`. -/
def semiInvariantDefect (J : Ideal (GLCoord R n)) (η : Fin n → ℤ) :
    GLCoord R n →ₗ[R] (GLCoord R n ⧸ J) ⊗[R] BorelCoord R n :=
  (rightCoactionMod R n J).toLinearMap -
    ((TensorProduct.mk R (GLCoord R n ⧸ J) (BorelCoord R n)).flip
      (((borelCharacterUnit R n η)⁻¹ : (BorelCoord R n)ˣ) : BorelCoord R n)).comp
      (Ideal.Quotient.mkₐ R J).toLinearMap

/-- **The model of `H⁰(X, 𝓛(η))`.** For an ideal `J` of `𝒪(GLₙ)` (the ideal of a closed
subscheme `Z ⊆ GLₙ`), the classes in `𝒪(Z) = 𝒪(GLₙ) ⧸ J` of the functions `f` that are
semi-invariant of weight `η` under right multiplication by `B`, `f(g b) = η(b)⁻¹ f(g)`, i.e.
`ρ(f) = f ⊗ η⁻¹` in `𝒪(Z) ⊗ 𝒪(B)` (`mem_quotientSemiInvariants_iff`). -/
def quotientSemiInvariants (J : Ideal (GLCoord R n)) (η : Fin n → ℤ) :
    Submodule R (GLCoord R n ⧸ J) :=
  (LinearMap.ker (semiInvariantDefect R n J η)).map (Ideal.Quotient.mkₐ R J).toLinearMap

variable {R n}

theorem semiInvariantDefect_apply (J : Ideal (GLCoord R n)) (η : Fin n → ℤ) (f : GLCoord R n) :
    semiInvariantDefect R n J η f = rightCoactionMod R n J f -
      Ideal.Quotient.mk J f ⊗ₜ (((borelCharacterUnit R n η)⁻¹ : (BorelCoord R n)ˣ) :
          BorelCoord R n) :=
  rfl

theorem semiInvariantDefect_eq_zero_of_mem {J : Ideal (GLCoord R n)} (hJ : IsBorelStable R n J)
    (η : Fin n → ℤ) {f : GLCoord R n} (hf : f ∈ J) : semiInvariantDefect R n J η f = 0 := by
  rw [semiInvariantDefect_apply, Ideal.Quotient.eq_zero_iff_mem.mpr hf, zero_tmul, sub_zero]
  exact hJ hf

theorem mem_quotientSemiInvariants_iff {J : Ideal (GLCoord R n)} (hJ : IsBorelStable R n J)
    (η : Fin n → ℤ) (f : GLCoord R n) :
    Ideal.Quotient.mk J f ∈ quotientSemiInvariants R n J η ↔
      rightCoactionMod R n J f =
        Ideal.Quotient.mk J f ⊗ₜ
          (((borelCharacterUnit R n η)⁻¹ : (BorelCoord R n)ˣ) : BorelCoord R n) := by
  rw [← sub_eq_zero, ← semiInvariantDefect_apply]
  constructor
  · rintro ⟨g, hg, hgf⟩
    have hd : f - g ∈ J := by
      rw [← Ideal.Quotient.eq]
      exact hgf.symm
    have : semiInvariantDefect R n J η f =
        semiInvariantDefect R n J η g + semiInvariantDefect R n J η (f - g) := by
      rw [← map_add, add_sub_cancel]
    rw [this, LinearMap.mem_ker.mp hg, semiInvariantDefect_eq_zero_of_mem hJ η hd, add_zero]
  · intro h
    exact ⟨f, h, rfl⟩

end FlagVarieties
