import Schubert.GLRep.Weyl.WeylCharacter

/-!
# Highest weight vectors of `gl_n`-modules

Let `M` be a finite-dimensional `gl_n(K)`-module, `K` a field of characteristic zero.

* If `M` has a nonzero integral weight space, then it has a highest weight vector of integral
  weight (`GLRep.exists_isGlHighestWeightVector`): take a nonzero vector in the weight space of
  largest height `∑_i (n − i) μ_i`, since raising operators increase the height.
* **Schur's lemma.** If `M` is generated by a highest weight vector, every endomorphism of `M` is
  a scalar (`GLRep.exists_eq_smul_of_isGlHighestWeightVector`): it preserves the highest weight
  space, which is a line.

## Main definitions

* `GLRep.weightHeight`: the height `∑_i (n − i) μ_i` of an integral weight.

## Main results

* `GLRep.exists_isGlHighestWeightVector`.
* `GLRep.lieSpan_eq_top_of_isIrreducible`.
* `GLRep.exists_eq_smul_of_isGlHighestWeightVector`.
-/

namespace GLRep

open Module LieModule Finset

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

variable {K : Type*} [Field K] [CharZero K] {n : ℕ}
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule (Matrix (Fin n) (Fin n) K) M]
  [LieModule K (Matrix (Fin n) (Fin n) K) M]

/-- The height `∑_i (n − i) μ_i` of an integral weight. Raising by a positive root increases it. -/
def weightHeight (μ : Fin n → ℤ) : ℤ := ∑ i : Fin n, ((n : ℤ) - (i : ℕ)) * μ i

theorem weightHeight_add_root (μ : Fin n → ℤ) (a b : Fin n) :
    weightHeight (μ + root a b) = weightHeight μ + ((b : ℕ) - (a : ℕ) : ℤ) := by
  simp only [weightHeight, root, Pi.add_apply, Pi.sub_apply, mul_add, mul_sub, sum_add_distrib,
    sum_sub_distrib, Pi.single_apply, mul_ite, mul_one, mul_zero, sum_ite_eq', mem_univ,
    ↓reduceIte]
  ring

omit [CharZero K] in
/-- A nonzero vector of a weight space of maximal height is a highest weight vector. -/
theorem isGlHighestWeightVector_of_forall_weightHeight_le {ν : Fin n → ℤ} {v : M}
    (hv : v ∈ glWeightSpace K M ν) (hv0 : v ≠ 0)
    (hmax : ∀ μ : Fin n → ℤ, glWeightSpace K M μ ≠ ⊥ → weightHeight μ ≤ weightHeight ν) :
    TauCeti.IsGlHighestWeightVector (fun i => (ν i : K)) v := by
  refine TauCeti.isGlHighestWeightVector_iff.mpr ⟨hv0, mem_glWeightSpace.mp hv, fun a b hab => ?_⟩
  have hmem := lie_mem_glWeightSpace hv a b
  have hbot : glWeightSpace K M (ν + root a b) = ⊥ := by
    by_contra hne
    have := hmax _ hne
    rw [weightHeight_add_root] at this
    have : (a : ℕ) < b := hab
    omega
  rw [hbot, Submodule.mem_bot] at hmem
  exact hmem

/-- **Existence of highest weight vectors.** A finite-dimensional `gl_n`-module with a nonzero
integral weight space has a highest weight vector of integral weight. -/
theorem exists_isGlHighestWeightVector [FiniteDimensional K M] {μ : Fin n → ℤ}
    (hμ : glWeightSpace K M μ ≠ ⊥) :
    ∃ (ν : Fin n → ℤ) (v : M), v ∈ glWeightSpace K M ν ∧
      TauCeti.IsGlHighestWeightVector (fun i => (ν i : K)) v := by
  set S := (finite_glWeightSpace_ne_bot K M (n := n)).toFinset
  obtain ⟨ν, hνS, hmax⟩ := S.exists_max_image weightHeight
    ⟨μ, (Set.Finite.mem_toFinset _).mpr hμ⟩
  have hν : glWeightSpace K M ν ≠ ⊥ := (Set.Finite.mem_toFinset _).mp hνS
  obtain ⟨v, hv, hv0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hν
  exact ⟨ν, v, hv, isGlHighestWeightVector_of_forall_weightHeight_le hv hv0 fun μ hμ =>
    hmax μ ((Set.Finite.mem_toFinset _).mpr hμ)⟩

omit [CharZero K] [LieModule K (Matrix (Fin n) (Fin n) K) M] in
/-- In an irreducible module, every nonzero vector generates. -/
theorem lieSpan_eq_top_of_isIrreducible [IsIrreducible K (Matrix (Fin n) (Fin n) K) M] {v : M}
    (hv : v ≠ 0) : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤ := by
  refine (IsSimpleOrder.eq_bot_or_eq_top _).resolve_left fun h => hv ?_
  have : v ∈ LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} :=
    LieSubmodule.subset_lieSpan rfl
  rwa [h, LieSubmodule.mem_bot] at this

/-- **Schur's lemma** for modules generated by a highest weight vector: every endomorphism is a
scalar. -/
theorem exists_eq_smul_of_isGlHighestWeightVector {lam : Fin n → ℤ} {v : M}
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤)
    (f : M →ₗ⁅K, Matrix (Fin n) (Fin n) K⁆ M) : ∃ c : K, ∀ m, f m = c • m := by
  have hfv : f v ∈ glWeightSpace K M lam := by
    refine mem_glWeightSpace.mpr fun i => ?_
    rw [← LieModuleHom.map_lie, (mem_glWeightSpace.mp
      (mem_glWeightSpace_of_isGlHighestWeightVector hv)) i, map_smul]
  rw [glWeightSpace_eq_span_singleton hv hgen, Submodule.mem_span_singleton] at hfv
  obtain ⟨c, hc⟩ := hfv
  refine ⟨c, fun m => ?_⟩
  have hker : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} ≤
      (f - c • LieModuleHom.id).ker := by
    rw [LieSubmodule.lieSpan_le, Set.singleton_subset_iff, SetLike.mem_coe,
      LieModuleHom.mem_ker, sub_apply, smul_apply,
      LieModuleHom.id_apply, hc, sub_self]
  have hm := hker (hgen ▸ LieSubmodule.mem_top m)
  rwa [LieModuleHom.mem_ker, sub_apply, smul_apply,
    LieModuleHom.id_apply, sub_eq_zero] at hm

end

end GLRep
