import Schubert.GLRep.HighestWeight.Basic
import Schubert.GLRep.Weyl.GroupCharacter

/-!
# Irreducible polynomial representations of `GL_n` and their highest weights

Let `ρ` be an irreducible polynomial representation of `GL_n(K)`, `K` a field of characteristic
zero. Its Lie module has a highest weight vector, which generates it. The highest weight `λ` has
nonnegative entries, since all weights of `ρ` do, and it is weakly decreasing, since the character
of `ρ` is symmetric (`GLRep.IsPolynomialRep.exists_highestWeight`). So `λ` is the row lengths of
a Young diagram `μ` with at most `n` rows, and the character of `ρ` is the Schur polynomial `s_μ`
(`GLRep.IsPolynomialRep.exists_character_eq_diagramSchurPoly`).

Two irreducible polynomial representations with highest weight vectors of the same weight are
equivalent (`GLRep.IsPolynomialRep.nonempty_equiv_of_isGlHighestWeightVector`, from Tau Ceti's
uniqueness theorem for `gl_n`-modules). Hence irreducible polynomial representations with the same
character are equivalent (`GLRep.IsPolynomialRep.nonempty_equiv_of_character_eq`). **Schur's
lemma** holds without algebraic closure: the endomorphisms of an irreducible polynomial
representation are the scalars (`GLRep.IsPolynomialRep.finrank_intertwiningMap_self`).

## Main results

* `GLRep.IsPolynomialRep.iSup_glWeightSpace_eq_top`: the Lie module is integral.
* `GLRep.IsPolynomialRep.exists_highestWeight`,
  `GLRep.IsPolynomialRep.exists_character_eq_diagramSchurPoly`.
* `GLRep.IsPolynomialRep.weightSpace_eq_bot_of_not_dominated`,
  `GLRep.IsPolynomialRep.finrank_weightSpace_of_isGlHighestWeightVector`.
* `GLRep.IsPolynomialRep.highestWeight_eq_of_character_eq`,
  `GLRep.IsPolynomialRep.nonempty_equiv_of_isGlHighestWeightVector`,
  `GLRep.IsPolynomialRep.nonempty_equiv_of_character_eq`.
* `GLRep.IsPolynomialRep.finrank_intertwiningMap_self`.
-/

namespace GLRep

open Module LieModule

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

variable {K : Type*} [Field K] [CharZero K] {n : ℕ}
variable {W : Type*} [AddCommGroup W] [Module K W] {ρ : Representation K (GL (Fin n) K) W}
variable {V : Type*} [AddCommGroup V] [Module K V] {σ : Representation K (GL (Fin n) K) V}

omit [CharZero K] in
/-- An irreducible representation is nonzero. -/
theorem nontrivial_of_isIrreducible (hirr : ρ.IsIrreducible) : Nontrivial W := by
  by_contra hW
  rw [not_nontrivial_iff_subsingleton] at hW
  apply (bot_ne_top : (⊥ : Subrepresentation ρ) ≠ ⊤)
  apply Subrepresentation.toSubmodule_injective
  ext w
  rw [Subsingleton.elim w 0]
  exact ⟨fun _ => zero_mem _, fun _ => zero_mem _⟩

namespace IsPolynomialRep

variable (h : IsPolynomialRep ρ)
include h

/-- The Lie module of a polynomial representation is spanned by its integral weight spaces. -/
theorem iSup_glWeightSpace_eq_top : ⨆ μ : Fin n → ℤ, glWeightSpace K h.LieRep μ = ⊤ := by
  simp_rw [← h.map_weightSpace]
  rw [← Submodule.map_iSup, h.comp_diagGL.iSup_torusWeightSpace_eq_top, Submodule.map_top,
    LinearEquiv.range]

/-- The Lie module of a polynomial representation is integral. -/
theorem isIntegralGLModule : IsIntegralGLModule K n h.LieRep :=
  ⟨inferInstance, h.iSup_glWeightSpace_eq_top⟩

/-- The weights of the Lie module of a polynomial representation are nonnegative. -/
theorem glWeightSpace_eq_bot_of_neg {μ : Fin n → ℤ} (hμ : ∃ i, μ i < 0) :
    glWeightSpace K h.LieRep μ = ⊥ := by
  rw [← h.map_weightSpace, weightSpace, h.comp_diagGL.torusWeightSpace_eq_bot hμ,
    Submodule.map_bot]

/-- A nonzero polynomial representation has a highest weight vector of integral weight. -/
theorem exists_isGlHighestWeightVector [Nontrivial W] :
    ∃ (ν : Fin n → ℤ) (v : h.LieRep), v ∈ glWeightSpace K h.LieRep ν ∧
      TauCeti.IsGlHighestWeightVector (fun i => (ν i : K)) v := by
  have : Nontrivial h.LieRep := inferInstanceAs (Nontrivial W)
  obtain ⟨μ, hμ⟩ : ∃ μ : Fin n → ℤ, glWeightSpace K h.LieRep μ ≠ ⊥ := by
    by_contra hall
    push Not at hall
    have htop := h.iSup_glWeightSpace_eq_top
    simp only [hall, iSup_bot] at htop
    exact bot_ne_top htop
  exact GLRep.exists_isGlHighestWeightVector hμ

/-- **The highest weight of an irreducible polynomial representation.** Its Lie module is
generated by a highest weight vector whose weight is weakly decreasing with nonnegative
entries. -/
theorem exists_highestWeight (hirr : ρ.IsIrreducible) :
    ∃ lam : Fin n → ℤ, Antitone lam ∧ (∀ i, 0 ≤ lam i) ∧ ∃ v : h.LieRep,
      TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v ∧
        LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤ := by
  have := nontrivial_of_isIrreducible hirr
  have : IsIrreducible K (Matrix (Fin n) (Fin n) K) h.LieRep := h.isIrreducible_iff.mp hirr
  obtain ⟨lam, v, hvlam, hv⟩ := h.exists_isGlHighestWeightVector
  have hgen := lieSpan_eq_top_of_isIrreducible (K := K) (n := n) hv.ne_zero
  refine ⟨lam, antitone_of_isGlHighestWeightVector hv hgen h.isSymm_glCharacter,
    fun i => ?_, v, hv, hgen⟩
  by_contra hi
  have hbot := h.glWeightSpace_eq_bot_of_neg ⟨i, not_le.mp hi⟩
  rw [hbot, Submodule.mem_bot] at hvlam
  exact hv.ne_zero hvlam

/-- **The character of an irreducible polynomial representation is a Schur polynomial.** -/
theorem exists_character_eq_diagramSchurPoly (hirr : ρ.IsIrreducible) :
    ∃ μ : YoungDiagram, μ.colLen 0 ≤ n ∧ character ρ = TauCeti.diagramSchurPoly n ℤ μ := by
  obtain ⟨lam, hanti, hnonneg, v, hv, hgen⟩ := h.exists_highestWeight hirr
  set l : TauCeti.DominantWeight n := ⟨lam, hanti⟩
  have hl : l.IsPolynomial := hnonneg
  refine ⟨l.shape, TauCeti.DominantWeight.colLen_zero_shape_le l,
    h.character_eq_diagramSchurPoly (TauCeti.DominantWeight.colLen_zero_shape_le l) (v := v) ?_
      hgen⟩
  convert hv using 2 with i
  rw [← Int.cast_natCast, TauCeti.DominantWeight.natCast_rowLen_shape hl]

/-- The weights of a polynomial representation generated by a highest weight vector of weight `λ`
are dominated by `λ`. -/
theorem weightSpace_eq_bot_of_not_dominated {lam : Fin n → ℤ} {v : h.LieRep}
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) {μ : Fin n → ℤ}
    (hμ : ¬Dominated μ lam) : weightSpace ρ μ = ⊥ := by
  have h1 := glWeightSpace_eq_bot_of_not_dominated hv hgen hμ
  rwa [← h.map_weightSpace, Submodule.map_eq_bot_iff] at h1

/-- In a polynomial representation generated by a highest weight vector of weight `λ`, the weight
space of `λ` is a line. -/
theorem finrank_weightSpace_of_isGlHighestWeightVector {lam : Fin n → ℤ} {v : h.LieRep}
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) :
    finrank K (weightSpace ρ lam) = 1 := by
  rw [← h.finrank_glWeightSpace, finrank_glWeightSpace_of_isGlHighestWeightVector hv hgen]

omit h in
/-- Polynomial representations with the same character have weight spaces of the same
dimensions. -/
theorem finrank_weightSpace_eq_of_character_eq (hρ : IsPolynomialRep ρ) (hσ : IsPolynomialRep σ)
    (hχ : character ρ = character σ) (μ : Fin n → ℤ) :
    finrank K (weightSpace ρ μ) = finrank K (weightSpace σ μ) := by
  by_cases hμ : ∃ i, μ i < 0
  · rw [weightSpace, hρ.comp_diagGL.torusWeightSpace_eq_bot hμ, weightSpace,
      hσ.comp_diagGL.torusWeightSpace_eq_bot hμ, finrank_bot, finrank_bot]
  · push Not at hμ
    have heq : μ = fun i => ((Finsupp.equivFunOnFinite.symm fun i => (μ i).toNat) i : ℤ) := by
      funext i
      simp [Int.toNat_of_nonneg (hμ i)]
    rw [heq]
    have h1 := coeff_character hρ (Finsupp.equivFunOnFinite.symm fun i => (μ i).toNat)
    have h2 := coeff_character hσ (Finsupp.equivFunOnFinite.symm fun i => (μ i).toNat)
    rw [hχ] at h1
    exact_mod_cast h1.symm.trans h2

/-- The weights of a polynomial representation generated by a highest weight vector of weight `λ`
are dominated by `λ`. -/
theorem dominated_of_finrank_ne_zero {lam : Fin n → ℤ} {v : h.LieRep}
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) {μ : Fin n → ℤ}
    (hμ : finrank K (weightSpace ρ μ) ≠ 0) : Dominated μ lam := by
  by_contra hnd
  rw [h.weightSpace_eq_bot_of_not_dominated hv hgen hnd, finrank_bot] at hμ
  exact hμ rfl

omit h in
/-- **Highest weights determine irreducible polynomial representations.** -/
theorem nonempty_equiv_of_isGlHighestWeightVector (hρ : IsPolynomialRep ρ)
    (hσ : IsPolynomialRep σ) (hirrρ : ρ.IsIrreducible) (hirrσ : σ.IsIrreducible)
    {mu : Fin n → K} {v : hρ.LieRep} {v' : hσ.LieRep} (hv : TauCeti.IsGlHighestWeightVector mu v)
    (hv' : TauCeti.IsGlHighestWeightVector mu v') : Nonempty (ρ.Equiv σ) := by
  have : IsIrreducible K (Matrix (Fin n) (Fin n) K) hρ.LieRep := hρ.isIrreducible_iff.mp hirrρ
  have : IsIrreducible K (Matrix (Fin n) (Fin n) K) hσ.LieRep := hσ.isIrreducible_iff.mp hirrσ
  exact ⟨equivOfLieModuleEquiv hσ (TauCeti.lieModuleEquivOfIsGlHighestWeightVector hv hv')⟩

omit h in
/-- **The highest weight is determined by the character.** -/
theorem highestWeight_eq_of_character_eq (hρ : IsPolynomialRep ρ) (hσ : IsPolynomialRep σ)
    (hχ : character ρ = character σ) {lam lam' : Fin n → ℤ} {v : hρ.LieRep} {v' : hσ.LieRep}
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤)
    (hv' : TauCeti.IsGlHighestWeightVector (fun i => (lam' i : K)) v')
    (hgen' : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v'} = ⊤) : lam = lam' := by
  have h1 : Dominated lam lam' := by
    refine hσ.dominated_of_finrank_ne_zero hv' hgen' ?_
    rw [← finrank_weightSpace_eq_of_character_eq hρ hσ hχ,
      hρ.finrank_weightSpace_of_isGlHighestWeightVector hv hgen]
    exact one_ne_zero
  have h2 : Dominated lam' lam := by
    refine hρ.dominated_of_finrank_ne_zero hv hgen ?_
    rw [finrank_weightSpace_eq_of_character_eq hρ hσ hχ,
      hσ.finrank_weightSpace_of_isGlHighestWeightVector hv' hgen']
    exact one_ne_zero
  exact LaurentPoly.Dominated.antisymm h1 h2

omit h in
/-- **Characters determine irreducible polynomial representations.** -/
theorem nonempty_equiv_of_character_eq (hρ : IsPolynomialRep ρ) (hσ : IsPolynomialRep σ)
    (hirrρ : ρ.IsIrreducible) (hirrσ : σ.IsIrreducible) (hχ : character ρ = character σ) :
    Nonempty (ρ.Equiv σ) := by
  obtain ⟨lam, -, -, v, hv, hgen⟩ := hρ.exists_highestWeight hirrρ
  obtain ⟨lam', -, -, v', hv', hgen'⟩ := hσ.exists_highestWeight hirrσ
  obtain rfl := highestWeight_eq_of_character_eq hρ hσ hχ hv hgen hv' hgen'
  exact nonempty_equiv_of_isGlHighestWeightVector hρ hσ hirrρ hirrσ hv hv'

/-- **Schur's lemma.** Every endomorphism of an irreducible polynomial representation is a
scalar. -/
theorem exists_eq_smul_of_isIrreducible (hirr : ρ.IsIrreducible) (φ : ρ.IntertwiningMap ρ) :
    ∃ c : K, φ = c • Representation.IntertwiningMap.id ρ := by
  obtain ⟨lam, -, -, v, hv, hgen⟩ := h.exists_highestWeight hirr
  obtain ⟨c, hc⟩ := exists_eq_smul_of_isGlHighestWeightVector hv hgen
    (intertwiningEquivLieHom h φ)
  refine ⟨c, Representation.IntertwiningMap.ext (LinearMap.ext fun w => ?_)⟩
  exact hc (h.toLieRep w)

/-- **Schur's lemma.** The endomorphisms of an irreducible polynomial representation form a line.
-/
theorem finrank_intertwiningMap_self (hirr : ρ.IsIrreducible) :
    finrank K (ρ.IntertwiningMap ρ) = 1 := by
  have := nontrivial_of_isIrreducible hirr
  let L : K →ₗ[K] ρ.IntertwiningMap ρ :=
    LinearMap.toSpanSingleton K _ (Representation.IntertwiningMap.id ρ)
  have hL : Function.Bijective L := by
    refine ⟨fun c c' hcc' => ?_, fun φ => ?_⟩
    · obtain ⟨w, hw⟩ := exists_ne (0 : W)
      have := congrArg (fun ψ : ρ.IntertwiningMap ρ => ψ w) hcc'
      simp only [L, LinearMap.toSpanSingleton_apply, Representation.IntertwiningMap.coe_smul,
        Representation.IntertwiningMap.coe_id, Pi.smul_apply, id_eq] at this
      exact smul_left_injective K hw this
    · obtain ⟨c, rfl⟩ := h.exists_eq_smul_of_isIrreducible hirr φ
      exact ⟨c, rfl⟩
  rw [← (LinearEquiv.ofBijective L hL).finrank_eq, Module.finrank_self]

end IsPolynomialRep

end

end GLRep
