import Schubert.GLRep.HighestWeight.Integral
import Schubert.GLRep.HighestWeight.Classification
import TauCeti.Algebra.Lie.Submodule.Atom
import TauCeti.Algebra.Lie.GeneralLinear.Existence
import Mathlib.RepresentationTheory.Semisimple

/-!
# Complete reducibility of integral `gl_n`-modules

Let `K` be a field of characteristic zero. **Every Lie submodule of an integral `gl_n(K)`-module
has a complement** (`GLRep.IsIntegralGLModule.exists_isCompl`); no algebraic closure is needed.
Consequently every polynomial representation of `GL_n(K)` is semisimple
(`GLRep.IsPolynomialRep.isSemisimpleRepresentation`).

The heart of the proof is the case of length two (`GLRep.exists_isCompl_of_isAtom_of_isCoatom`):
`A ≤ M` with `A` and `M ⧸ A` irreducible, of highest weights `μ` and `λ`, both dominant. Let
`c(ν) = ∑_i ν_i (ν_i + n − 1 − 2i)` be the scalar by which the Casimir element acts on a module
generated by a highest weight vector of weight `ν`. For dominant `ν < ν'` in the dominance order,
`c(ν) < c(ν')` (`GLRep.casimirScalar_ne_of_dominated`), by the strict convexity of the norm.

* If `c(μ) ≠ c(λ)`, the kernel of `Ω − c(λ)` is a complement.
* If `c(μ) = c(λ)`, lift the highest weight vector of `M ⧸ A` to a weight vector `e` of `M`. The
  raising operators carry `e` into `A`, into weight spaces of weights above `λ`; such a weight
  would be dominated by `μ`, forcing `λ < μ`. So `e` is a highest weight vector. The submodule
  it generates meets `A` trivially: otherwise it would be all of `M`, whose weights would then be
  dominated by `λ` with the `λ`-weight space a line, forcing `μ < λ`.

The general case follows by induction on the dimension, through the atoms of the lattice of Lie
submodules.

## Main definitions

* `GLRep.casimirEnd K n M`: the action of the Casimir element `∑_{a,b} E_ab E_ba`.

## Main results

* `GLRep.normSq_lt_of_dominated`, `GLRep.casimirScalar_ne_of_dominated`.
* `GLRep.exists_isCompl_of_isAtom_of_isCoatom`.
* `GLRep.IsIntegralGLModule.exists_isCompl`: **complete reducibility**.
* `GLRep.IsPolynomialRep.isSemisimpleRepresentation`.
-/

namespace GLRep

open Module LieModule Finset

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

/-! ### Norms and Casimir scalars along the dominance order -/

section Scalar

variable {n : ℕ}

/-- The norm is monotone along the dominance order towards a strictly decreasing weight. -/
theorem normSq_le_of_dominated {ν Λ : Fin n → ℤ} (hΛ : StrictAnti Λ) (hν : Antitone ν)
    (hd : Dominated ν Λ) : LaurentPoly.normSq ν ≤ LaurentPoly.normSq Λ := by
  classical
  let ext : (Fin n → ℤ) → ℕ → ℤ := fun μ i => if h : i < n then μ ⟨i, h⟩ else 0
  let D : ℕ → ℤ := fun k => partialSum Λ k - partialSum ν k
  let s : ℕ → ℤ := fun i => ext Λ i + ext ν i
  have hD : ∀ k, 0 ≤ D k := fun k => sub_nonneg.mpr (hd.1 k)
  have hD0 : D 0 = 0 := by simp [D, partialSum_zero]
  have hDn : D n = 0 := by simp only [D, partialSum_of_le le_rfl, hd.2, sub_self]
  have hstep : ∀ i : Fin n, D (i + 1) - D i = Λ i - ν i := by
    intro i
    simp only [D, partialSum_succ]
    ring
  have h1 : LaurentPoly.normSq Λ - LaurentPoly.normSq ν =
      ∑ i ∈ range n, (D (i + 1) - D i) * s i := by
    rw [LaurentPoly.normSq, LaurentPoly.normSq, ← sum_sub_distrib,
      ← Fin.sum_univ_eq_sum_range (fun i => (D (i + 1) - D i) * s i)]
    refine sum_congr rfl fun i _ => ?_
    rw [hstep i]
    simp only [s, ext, i.isLt, ↓reduceDIte]
    ring
  rw [sum_range_sub_mul, hD0, hDn, zero_mul, zero_mul, sub_zero, zero_add] at h1
  have hgap : ∀ i, i + 1 < n → 0 < s i - s (i + 1) := by
    intro i hi
    have h1 : Λ ⟨i + 1, hi⟩ < Λ ⟨i, by omega⟩ := hΛ (Fin.mk_lt_mk.mpr (Nat.lt_succ_self i))
    have h2 : ν ⟨i + 1, hi⟩ ≤ ν ⟨i, by omega⟩ := hν (Fin.mk_le_mk.mpr (Nat.le_succ i))
    simp only [s, ext, hi, show i < n by omega, ↓reduceDIte]
    linarith
  have hterm : ∀ i ∈ range n, 0 ≤ D (i + 1) * (s i - s (i + 1)) := by
    intro i hi
    rcases Nat.lt_or_ge (i + 1) n with h | h
    · exact mul_nonneg (hD _) (hgap i h).le
    · have : i + 1 = n := by have := mem_range.mp hi; omega
      rw [this, hDn, zero_mul]
  linarith [sum_nonneg hterm]

/-- **Strict monotonicity of `|ν + δ|²` along the dominance order** of dominant weights. -/
theorem normSq_lt_of_dominated {μ lam : Fin n → ℤ} (hμ : Antitone μ) (hlam : Antitone lam)
    (hd : Dominated μ lam) (hne : μ ≠ lam) :
    LaurentPoly.normSq (μ + LaurentPoly.staircase n) <
      LaurentPoly.normSq (lam + LaurentPoly.staircase n) := by
  have hδ := LaurentPoly.staircase_strictAnti n
  have hd' : Dominated (μ + LaurentPoly.staircase n) (lam + LaurentPoly.staircase n) :=
    dominated_add hd (dominated_refl _)
  refine lt_of_le_of_ne (normSq_le_of_dominated (hlam.add_strictAnti hδ) (hμ.add hδ.antitone)
    hd') fun heq => hne ?_
  have := eq_of_dominated_of_normSq_eq (hlam.add_strictAnti hδ) (hμ.add hδ.antitone) hd' heq
  exact add_right_cancel this

variable {K : Type*} [Field K] [CharZero K]

/-- The scalar `c(ν) = ∑_i ν_i (ν_i + n − 1 − 2i)` by which the Casimir element acts on a module
generated by a highest weight vector of weight `ν`. -/
def casimirScalar (K : Type*) [Field K] (ν : Fin n → ℤ) : K :=
  ∑ i : Fin n, (ν i : K) * ((ν i : K) + n - 1 - 2 * ((i : ℕ) : K))

/-- **Distinct dominant weights, one dominating the other, have distinct Casimir scalars.** -/
theorem casimirScalar_ne_of_dominated {μ lam : Fin n → ℤ} (hμ : Antitone μ) (hlam : Antitone lam)
    (hd : Dominated μ lam) (hne : μ ≠ lam) : casimirScalar K μ ≠ casimirScalar K lam := by
  intro heq
  have h1 := casimir_add_eq_normSq (K := K) μ
  have h2 := casimir_add_eq_normSq (K := K) lam
  have hsum : (∑ i, (μ i : K)) = ∑ i, (lam i : K) := by
    rw [← Int.cast_sum, ← Int.cast_sum, hd.2]
  have hlt := normSq_lt_of_dominated hμ hlam hd hne
  have : (LaurentPoly.normSq (μ + LaurentPoly.staircase n) : K) =
      LaurentPoly.normSq (lam + LaurentPoly.staircase n) := by
    rw [← h1, ← h2, hsum]
    exact congrArg (· + _ + _) heq
  exact hlt.ne (Int.cast_injective this)

end Scalar

variable {K : Type*} [Field K] [CharZero K] {n : ℕ}
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule (Matrix (Fin n) (Fin n) K) M]
  [LieModule K (Matrix (Fin n) (Fin n) K) M]

/-- The weight of a highest weight vector in a finite-dimensional module is dominant. -/
theorem antitone_of_isGlHighestWeightVector' [FiniteDimensional K M] {lam : Fin n → ℤ} {v : M}
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v) : Antitone lam := by
  intro p q hpq
  obtain ⟨k, hk⟩ := (TauCeti.isGlDominantIntegral_iff_forall_le.mp
    (TauCeti.IsGlHighestWeightVector.isGlDominantIntegral hv)) p q hpq
  have : lam p - lam q = k := Int.cast_injective (by push_cast; exact hk)
  omega

/-! ### The Casimir operator -/

variable (K n M) in
/-- The action of the Casimir element `∑_{a,b} E_ab E_ba` on `M`. -/
def casimirEnd : Module.End K M :=
  ∑ i, ∑ j, toEnd K (Matrix (Fin n) (Fin n) K) M (matUnit i j) *
    toEnd K (Matrix (Fin n) (Fin n) K) M (matUnit j i)

omit [CharZero K] in
theorem casimirEnd_apply (m : M) :
    casimirEnd K n M m = ∑ i, ∑ j, ⁅(matUnit i j : Matrix (Fin n) (Fin n) K),
      ⁅(matUnit j i : Matrix (Fin n) (Fin n) K), m⁆⁆ := by
  simp [casimirEnd, LinearMap.sum_apply]

omit [CharZero K] in
/-- The Casimir operator commutes with the action. -/
theorem casimirEnd_lie (X : Matrix (Fin n) (Fin n) K) (m : M) :
    casimirEnd K n M ⁅X, m⁆ = ⁅X, casimirEnd K n M m⁆ := by
  rw [casimirEnd_apply, casimirEnd_apply, ← TauCeti.representation_glCasimir_apply K (Fin n),
    ← TauCeti.representation_glCasimir_apply K (Fin n)]
  have h := congrArg (fun a => TauCeti.UniversalEnvelopingAlgebra.representation K
    (Matrix (Fin n) (Fin n) K) M a m) (TauCeti.ι_mul_glCasimir K (Fin n) X)
  simp only [map_mul, Module.End.mul_apply,
    TauCeti.UniversalEnvelopingAlgebra.representation_ι_apply] at h
  exact h.symm

omit [CharZero K] in
/-- Lie module maps commute with the Casimir operators. -/
theorem LieModuleHom.map_casimirEnd {M' : Type*} [AddCommGroup M'] [Module K M']
    [LieRingModule (Matrix (Fin n) (Fin n) K) M'] [LieModule K (Matrix (Fin n) (Fin n) K) M']
    (f : M →ₗ⁅K, Matrix (Fin n) (Fin n) K⁆ M') (m : M) :
    f (casimirEnd K n M m) = casimirEnd K n M' (f m) := by
  simp only [casimirEnd_apply, map_sum, LieModuleHom.map_lie]

/-! ### The case of length two -/

omit [CharZero K] in
/-- In a module generated by a highest weight vector, the Casimir operator is the scalar of the
highest weight. -/
theorem casimirEnd_eq_smul {lam : Fin n → ℤ} {v : M}
    (hv : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {v} = ⊤) (m : M) :
    casimirEnd K n M m = casimirScalar K lam • m := by
  rw [casimirEnd_apply, casimir_apply_of_isGlHighestWeightVector hv hgen, casimirScalar]

/-- **Complete reducibility in length two.** If `A ≤ M` with `A` and `M ⧸ A` irreducible, `M`
integral, then `A` has a complement. -/
theorem exists_isCompl_of_isAtom_of_isCoatom (hM : IsIntegralGLModule K n M)
    {A : LieSubmodule K (Matrix (Fin n) (Fin n) K) M} (hat : IsAtom A) (hco : IsCoatom A) :
    ∃ B, IsCompl A B := by
  classical
  have := hM.finiteDimensional
  -- the highest weight of `A`
  have hAint := hM.lieSubmodule A
  have : IsIrreducible K (Matrix (Fin n) (Fin n) K) A :=
    (TauCeti.isIrreducible_iff_isAtom A).mpr hat
  have : Nontrivial A := LieModule.nontrivial_of_isIrreducible K (Matrix (Fin n) (Fin n) K) A
  obtain ⟨μ, a, haμ, ha⟩ := hAint.exists_isGlHighestWeightVector
  have hgenA := lieSpan_eq_top_of_isIrreducible (K := K) (n := n) ha.ne_zero
  have hμ : Antitone μ := antitone_of_isGlHighestWeightVector' ha
  -- the highest weight of `M ⧸ A`
  have hQint := hM.quotient A
  have : IsIrreducible K (Matrix (Fin n) (Fin n) K) (M ⧸ A) :=
    TauCeti.isIrreducible_quotient_iff_isCoatom.mpr hco
  have : Nontrivial (M ⧸ A) :=
    LieModule.nontrivial_of_isIrreducible K (Matrix (Fin n) (Fin n) K) (M ⧸ A)
  obtain ⟨lam, q, hqlam, hq⟩ := hQint.exists_isGlHighestWeightVector
  have hgenQ := lieSpan_eq_top_of_isIrreducible (K := K) (n := n) hq.ne_zero
  have hlam : Antitone lam := antitone_of_isGlHighestWeightVector' hq
  set mk := LieSubmodule.Quotient.mk' A
  -- the Casimir operator on `A` and on `M ⧸ A`
  have hΩA : ∀ x ∈ A, casimirEnd K n M x = casimirScalar K μ • x := by
    intro x hx
    have h := LieModuleHom.map_casimirEnd A.incl ⟨x, hx⟩
    rw [casimirEnd_eq_smul ha hgenA, map_smul] at h
    exact h.symm
  have hΩQ : ∀ x : M, mk (casimirEnd K n M x) = casimirScalar K lam • mk x := by
    intro x
    rw [LieModuleHom.map_casimirEnd mk x, casimirEnd_eq_smul hq hgenQ]
  by_cases hc : casimirScalar K μ = casimirScalar K lam
  · -- lift the highest weight vector of `M ⧸ A`
    have hq' : q ∈ (glWeightSpace K M lam).map (mk : M →ₗ[K] M ⧸ A) := by
      rw [hM.map_mk'_glWeightSpace A]
      exact hqlam
    obtain ⟨e, he, hmke⟩ := hq'
    have hmke' : mk e = q := hmke
    have heA : e ∉ A := fun h => hq.ne_zero (by
      rw [← hmke', LieSubmodule.Quotient.mk_eq_zero]
      exact h)
    -- `e` is a highest weight vector
    have hraise : ∀ a b : Fin n, a < b →
        ⁅(Matrix.single a b (1 : K) : Matrix (Fin n) (Fin n) K), e⁆ = 0 := by
      intro a b hab
      by_contra hx
      set x := ⁅(Matrix.single a b (1 : K) : Matrix (Fin n) (Fin n) K), e⁆
      have hxA : x ∈ A := by
        rw [← LieSubmodule.Quotient.mk_eq_zero]
        change mk ⁅_, e⁆ = 0
        rw [LieModuleHom.map_lie, hmke', hq.lie_single_eq_zero hab]
      have hxw : x ∈ glWeightSpace K M (lam + root a b) := lie_mem_glWeightSpace he a b
      have hdom : Dominated (lam + root a b) μ := by
        by_contra hnd
        have hbot := glWeightSpace_eq_bot_of_not_dominated ha hgenA hnd
        have hmem : (⟨x, hxA⟩ : A) ∈ glWeightSpace K A (lam + root a b) :=
          mem_glWeightSpace_lieSubmodule_iff.mpr hxw
        rw [hbot, Submodule.mem_bot] at hmem
        exact hx (congrArg Subtype.val hmem)
      have hdom' : Dominated lam μ := (dominated_add_root lam hab).trans hdom
      have hne : lam ≠ μ := by
        rintro rfl
        have := LaurentPoly.Dominated.antisymm hdom (dominated_add_root lam hab)
        have h1 := congrFun this a
        simp [root, hab.ne] at h1
      exact casimirScalar_ne_of_dominated (K := K) hlam hμ hdom' hne hc.symm
    have hev : TauCeti.IsGlHighestWeightVector (fun i => (lam i : K)) e :=
      TauCeti.isGlHighestWeightVector_iff.mpr ⟨fun h0 => heA (h0 ▸ A.zero_mem),
        mem_glWeightSpace.mp he, fun a b hab => hraise a b hab⟩
    set U := LieSubmodule.lieSpan K (Matrix (Fin n) (Fin n) K) {e}
    have heU : e ∈ U := LieSubmodule.subset_lieSpan rfl
    have hsup : A ⊔ U = ⊤ := hco.2 _ (lt_of_le_of_ne le_sup_left fun h =>
      heA (h ▸ LieSubmodule.mem_sup_right heU))
    rcases hat.le_iff.mp (inf_le_left : A ⊓ U ≤ A) with hinf | hinf
    · exact ⟨U, IsCompl.of_eq hinf hsup⟩
    · -- otherwise `e` generates `M`, which is impossible
      exfalso
      have hAU : A ≤ U := inf_eq_left.mp hinf
      have hU : U = ⊤ := by rwa [sup_eq_right.mpr hAU] at hsup
      have haM : (a : M) ∈ glWeightSpace K M μ := mem_glWeightSpace_lieSubmodule_iff.mp haμ
      have ha0 : (a : M) ≠ 0 := fun h => ha.ne_zero (Subtype.ext h)
      have hdom : Dominated μ lam := by
        by_contra hnd
        have := glWeightSpace_eq_bot_of_not_dominated hev hU hnd
        rw [this, Submodule.mem_bot] at haM
        exact ha0 haM
      have hne : μ ≠ lam := by
        rintro rfl
        rw [glWeightSpace_eq_span_singleton hev hU, Submodule.mem_span_singleton] at haM
        obtain ⟨c, hc'⟩ := haM
        have h1 : mk (a : M) = 0 := (LieSubmodule.Quotient.mk_eq_zero A).mpr a.2
        rw [← hc', map_smul, hmke'] at h1
        rcases smul_eq_zero.mp h1 with h2 | h2
        · rw [h2, zero_smul] at hc'
          exact ha0 hc'.symm
        · exact hq.ne_zero h2
      exact casimirScalar_ne_of_dominated (K := K) hμ hlam hdom hne hc
  · -- the kernel of `Ω − c(λ)` is a complement
    set c := casimirScalar K lam
    set d := casimirScalar K μ
    have hdc : d - c ≠ 0 := sub_ne_zero.mpr hc
    let E : LieSubmodule K (Matrix (Fin n) (Fin n) K) M :=
      { toSubmodule := LinearMap.ker (casimirEnd K n M - c • LinearMap.id)
        lie_mem := fun {X m} hm => by
          have hm' : m ∈ LinearMap.ker (casimirEnd K n M - c • LinearMap.id) := hm
          change ⁅X, m⁆ ∈ LinearMap.ker (casimirEnd K n M - c • LinearMap.id)
          rw [LinearMap.mem_ker] at hm' ⊢
          rw [LinearMap.sub_apply, LinearMap.smul_apply, LinearMap.id_apply] at hm' ⊢
          rw [casimirEnd_lie, sub_eq_zero.mp hm', lie_smul, sub_self] }
    have hmemE : ∀ m, m ∈ E ↔ casimirEnd K n M m = c • m := fun m => by
      change m ∈ LinearMap.ker _ ↔ _
      rw [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.smul_apply, LinearMap.id_apply,
        sub_eq_zero]
    refine ⟨E, IsCompl.of_eq ?_ ?_⟩
    · refine (LieSubmodule.eq_bot_iff _).mpr fun x hx => ?_
      obtain ⟨hxA, hxE⟩ := (LieSubmodule.mem_inf _ _ x).mp hx
      have h1 := hΩA x hxA
      rw [(hmemE x).mp hxE] at h1
      have : (d - c) • x = 0 := by rw [sub_smul, h1, sub_self]
      exact (smul_eq_zero.mp this).resolve_left hdc
    · refine eq_top_iff.mpr fun m _ => (LieSubmodule.mem_sup _ _ m).mpr ?_
      obtain ⟨u, hu_def⟩ : ∃ u, u = casimirEnd K n M m - c • m := ⟨_, rfl⟩
      have huA : u ∈ A := by
        rw [← LieSubmodule.Quotient.mk_eq_zero, hu_def]
        change mk (casimirEnd K n M m - c • m) = 0
        rw [map_sub, map_smul, hΩQ, sub_self]
      refine ⟨(d - c)⁻¹ • u, A.smul_mem _ huA, m - (d - c)⁻¹ • u, (hmemE _).mpr ?_,
        add_sub_cancel _ _⟩
      have hΩm : casimirEnd K n M m = u + c • m := by rw [hu_def, sub_add_cancel]
      have key : (d - c)⁻¹ * d = 1 + c * (d - c)⁻¹ := by
        field_simp
        ring
      rw [map_sub, map_smul, hΩA u huA, hΩm, smul_sub, smul_smul, smul_smul, key, add_smul,
        one_smul]
      abel

/-! ### The induction on the dimension -/

universe v

/-- Complete reducibility for the integral modules of dimension at most `d`. -/
private def ComplBelow (K : Type*) [Field K] (n d : ℕ) : Prop :=
  ∀ {M : Type v} [AddCommGroup M] [Module K M] [LieRingModule (Matrix (Fin n) (Fin n) K) M]
    [LieModule K (Matrix (Fin n) (Fin n) K) M], IsIntegralGLModule K n M → finrank K M ≤ d →
    ∀ N : LieSubmodule K (Matrix (Fin n) (Fin n) K) M, ∃ N', IsCompl N N'

omit [CharZero K] [LieModule K (Matrix (Fin n) (Fin n) K) M] in
private theorem finrank_lieSubmodule_lt [FiniteDimensional K M]
    {B : LieSubmodule K (Matrix (Fin n) (Fin n) K) M} (hB : B ≠ ⊤) :
    finrank K B < finrank K M := by
  have : (B : Submodule K M) ≠ ⊤ := fun h =>
    hB (LieSubmodule.toSubmodule_injective (h.trans LieSubmodule.top_toSubmodule.symm))
  exact Submodule.finrank_lt this

omit [CharZero K] [LieModule K (Matrix (Fin n) (Fin n) K) M] in
private theorem finrank_quotient_lt [FiniteDimensional K M]
    {D : LieSubmodule K (Matrix (Fin n) (Fin n) K) M} (hD : D ≠ ⊥) :
    finrank K (M ⧸ D) < finrank K M := by
  have h1 := Submodule.finrank_quotient_add_finrank (D : Submodule K M)
  have h2 : finrank K (D : Submodule K M) ≠ 0 := fun h0 =>
    hD (LieSubmodule.toSubmodule_injective
      ((Submodule.finrank_eq_zero.mp h0).trans LieSubmodule.bot_toSubmodule.symm))
  change finrank K (M ⧸ (D : Submodule K M)) < finrank K M
  omega

private theorem complBelow (d : ℕ) : ComplBelow.{v} K n d := by
  induction d using Nat.strong_induction_on with
  | _ d ih =>
  intro M _ _ _ _ hM hd
  have := hM.finiteDimensional
  have ihM : ∀ {M' : Type v} [AddCommGroup M'] [Module K M']
      [LieRingModule (Matrix (Fin n) (Fin n) K) M'] [LieModule K (Matrix (Fin n) (Fin n) K) M'],
      IsIntegralGLModule K n M' → finrank K M' < finrank K M →
      ∀ N' : LieSubmodule K (Matrix (Fin n) (Fin n) K) M', ∃ N'', IsCompl N' N'' :=
    fun hM' hlt N' => ih _ (lt_of_lt_of_le hlt hd) hM' le_rfl N'
  -- atoms have complements
  have hatom : ∀ A : LieSubmodule K (Matrix (Fin n) (Fin n) K) M, IsAtom A →
      ∃ B, IsCompl A B := by
    intro A hA
    by_cases hAtop : A = ⊤
    · exact ⟨⊥, hAtop ▸ isCompl_top_bot⟩
    by_cases hAco : IsCoatom A
    · exact exists_isCompl_of_isAtom_of_isCoatom hM hA hAco
    obtain ⟨B, hB, hAB⟩ := (eq_top_or_exists_le_coatom A).resolve_left hAtop
    have hAB' : A ≠ B := fun h => hAco (h ▸ hB)
    -- a complement `D` of `A` in `B`
    obtain ⟨D₀, hD₀⟩ := ihM (hM.lieSubmodule B) (finrank_lieSubmodule_lt hB.1)
      (A.comap B.incl)
    set D := D₀.map B.incl
    have hDB : D ≤ B := by
      rintro _ ⟨d, -, rfl⟩
      exact d.2
    have hDA : ∀ x, x ∈ D → x ∈ A → x = 0 := by
      rintro _ ⟨d, hd, rfl⟩ hdA
      have : d ∈ A.comap B.incl ⊓ D₀ := (LieSubmodule.mem_inf _ _ _).mpr ⟨hdA, hd⟩
      rw [hD₀.inf_eq_bot, LieSubmodule.mem_bot] at this
      rw [this, map_zero]
    have hADB : ∀ x ∈ B, ∃ a ∈ A, ∃ y ∈ D, a + y = x := by
      intro x hx
      have : (⟨x, hx⟩ : B) ∈ A.comap B.incl ⊔ D₀ := hD₀.sup_eq_top ▸ LieSubmodule.mem_top _
      obtain ⟨y, hy, z, hz, hyz⟩ := (LieSubmodule.mem_sup _ _ _).mp this
      exact ⟨y, hy, z, ⟨z, hz, rfl⟩, by rw [← LieSubmodule.coe_add, hyz]⟩
    have hDbot : D ≠ ⊥ := by
      intro hD
      apply hAB'
      refine le_antisymm hAB fun x hx => ?_
      obtain ⟨a, ha, y, hy, rfl⟩ := hADB x hx
      rw [hD, LieSubmodule.mem_bot] at hy
      rwa [hy, add_zero]
    -- a complement of the image of `B` in `M ⧸ D`
    set mk := LieSubmodule.Quotient.mk' D
    obtain ⟨E', hE'⟩ := ihM (hM.quotient D) (finrank_quotient_lt hDbot) (B.map mk)
    refine ⟨E'.comap mk, IsCompl.of_eq ?_ ?_⟩
    · refine (LieSubmodule.eq_bot_iff _).mpr fun x hx => ?_
      obtain ⟨hxA, hxE⟩ := (LieSubmodule.mem_inf _ _ x).mp hx
      have hmk : mk x ∈ B.map mk ⊓ E' :=
        (LieSubmodule.mem_inf _ _ _).mpr ⟨⟨x, hAB hxA, rfl⟩, hxE⟩
      rw [hE'.inf_eq_bot, LieSubmodule.mem_bot, LieSubmodule.Quotient.mk_eq_zero] at hmk
      exact hDA x hmk hxA
    · refine eq_top_iff.mpr fun m _ => (LieSubmodule.mem_sup _ _ m).mpr ?_
      have : mk m ∈ B.map mk ⊔ E' := hE'.sup_eq_top ▸ LieSubmodule.mem_top _
      obtain ⟨_, ⟨b, hb, rfl⟩, z, hz, hbz⟩ := (LieSubmodule.mem_sup _ _ _).mp this
      obtain ⟨a, ha, y, hy, rfl⟩ := hADB b hb
      refine ⟨a, ha, m - a, ?_, add_sub_cancel _ _⟩
      have hyD : mk y = 0 := (LieSubmodule.Quotient.mk_eq_zero D).mpr hy
      change mk (m - a) ∈ E'
      have : mk (m - a) = z := by
        have h3 : mk (a + y) + z = mk m := hbz
        rw [map_add, hyD, add_zero] at h3
        rw [map_sub, ← h3, add_sub_cancel_left]
      rw [this]
      exact hz
  -- every submodule has a complement
  intro N
  rcases eq_bot_or_exists_atom_le N with hN | ⟨A, hA, hAN⟩
  · exact ⟨⊤, hN ▸ isCompl_bot_top⟩
  obtain ⟨C, hC⟩ := hatom A hA
  have hCtop : C ≠ ⊤ := by
    rintro rfl
    exact hA.1 (by simpa using hC.inf_eq_bot)
  obtain ⟨R₀, hR₀⟩ := ihM (hM.lieSubmodule C) (finrank_lieSubmodule_lt hCtop) (N.comap C.incl)
  refine ⟨R₀.map C.incl, IsCompl.of_eq ?_ ?_⟩
  · refine (LieSubmodule.eq_bot_iff _).mpr fun x hx => ?_
    obtain ⟨hxN, ⟨r, hr, hrx⟩⟩ := (LieSubmodule.mem_inf _ _ x).mp hx
    have : r ∈ N.comap C.incl ⊓ R₀ := (LieSubmodule.mem_inf _ _ _).mpr
      ⟨by
        have h' : (r : M) = x := hrx
        rw [LieSubmodule.mem_comap, LieSubmodule.incl_apply, h']
        exact hxN, hr⟩
    rw [hR₀.inf_eq_bot, LieSubmodule.mem_bot] at this
    rw [← hrx, this, map_zero]
  · refine eq_top_iff.mpr fun m _ => (LieSubmodule.mem_sup _ _ m).mpr ?_
    have : m ∈ A ⊔ C := hC.sup_eq_top ▸ LieSubmodule.mem_top _
    obtain ⟨a, ha, c, hc, rfl⟩ := (LieSubmodule.mem_sup _ _ _).mp this
    have : (⟨c, hc⟩ : C) ∈ N.comap C.incl ⊔ R₀ := hR₀.sup_eq_top ▸ LieSubmodule.mem_top _
    obtain ⟨y, hy, z, hz, hyz⟩ := (LieSubmodule.mem_sup _ _ _).mp this
    refine ⟨a + y, N.add_mem (hAN ha) hy, z, ⟨z, hz, rfl⟩, ?_⟩
    have := congrArg Subtype.val hyz
    simp only [LieSubmodule.coe_add] at this
    rw [add_assoc]
    change a + ((y : M) + (z : M)) = a + c
    rw [this]

/-- **Complete reducibility of integral `gl_n`-modules** over a field of characteristic zero:
every Lie submodule has a complement. -/
theorem IsIntegralGLModule.exists_isCompl (hM : IsIntegralGLModule K n M)
    (N : LieSubmodule K (Matrix (Fin n) (Fin n) K) M) : ∃ N', IsCompl N N' :=
  have := hM.finiteDimensional
  complBelow (finrank K M) hM le_rfl N

theorem IsIntegralGLModule.complementedLattice (hM : IsIntegralGLModule K n M) :
    ComplementedLattice (LieSubmodule K (Matrix (Fin n) (Fin n) K) M) :=
  ⟨hM.exists_isCompl⟩

/-- **Polynomial representations of `GL_n(K)` are semisimple**, `K` of characteristic zero. -/
theorem IsPolynomialRep.isSemisimpleRepresentation {W : Type*} [AddCommGroup W] [Module K W]
    {ρ : Representation K (GL (Fin n) K) W} (h : IsPolynomialRep ρ) :
    Representation.IsSemisimpleRepresentation ρ :=
  (OrderIso.complementedLattice_iff h.subrepOrderIso).mpr h.isIntegralGLModule.complementedLattice

end

end GLRep
