import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Algebra.Order.Ring.Int
import Mathlib.Data.Set.Finite.List
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import Schubert.QuiverInvariants.Basic

/-!
# Positivity of the dimension vector attached to a weight

Let `Q` be a forward quiver with `m p q` arrows from `p` to `q`. For a dimension vector `n` and a
weight `σ`, the vector `liftWeight m n σ` is defined recursively by `0` at the vertices where `n`
vanishes and by `σ q + ∑_p m p q · A p` at the others. It is the unique vector `A` vanishing off
the support of `n` such that `A q - ∑_p m p q · A p = σ q` on the support of `n`; in other words
`⟨A, β⟩ = ∑_p σ_p β_p` for every `β` supported on the support of `n`, where `⟨·, ·⟩` is the Euler
form.

This file proves Lemma 4.4 of Baldoni–Vergne–Walter, with vertices of dimension `0` allowed: if
`∑_p σ_p β_p ≥ 0` for every `β` such that a general representation of dimension `n` has a quotient
of dimension `β`, then `liftWeight m n σ ≥ 0`.

The proof has two parts.
* *Combinatorics* (`QuiverInvariants.liftWeight_nonneg`): positivity follows by induction from
  vectors `θ k`, one for each vertex `k` in the support of `n`, with `θ k k = 1`, supported on
  `{j ≤ k} ∩ supp n`, with `θ k j ≤ ∑_i m j i · θ k i` for `j < k`, and pairing nonnegatively
  with `σ`.
* *Geometry*: `θ k` is the dimension vector of the quotient of a general representation `V`
  generated by a nonzero covector `ξ` at `k`. Its kernel at `j` consists of the vectors `v` with
  `ξ(V_w v) = 0` for all paths `w` from `j` to `k`. Paths are encoded as words of arrows of
  bounded length acting on families of vectors, so that the conditions are the kernels of
  matrices of polynomials, and generic ranks give the dimensions.

## Main definitions

* `QuiverInvariants.liftWeight m n σ`: the vector described above.
* `QuiverInvariants.FQuiver.wordLin V w`: the action of a word of arrows on families of vectors.
* `QuiverInvariants.FQuiver.wordFun V k i₀ j`: the functionals `v ↦ (w · v)_{k, i₀}`.
* `QuiverInvariants.FQuiver.genericQuotDim K ι k i₀`: the generic dimension vector of the
  quotient generated by the covector `e_{i₀}^*` at `k`.

## Main results

* `QuiverInvariants.liftWeight_sub_sum`: `A q - ∑_p m p q · A p = σ q` on the support of `n`.
* `QuiverInvariants.liftWeight_nonneg`: the combinatorial positivity statement.
* `QuiverInvariants.FQuiver.generalQuot_genericQuotDim`: a general representation has a quotient
  of dimension `genericQuotDim`.
* `QuiverInvariants.FQuiver.liftWeight_nonneg_of_generalQuot`: Lemma 4.4.
-/

open Finset

open scoped Matrix

namespace QuiverInvariants

section Combinatorics

variable {s : ℕ} {m : Fin s → Fin s → ℕ}

/-- **The induction step.** Let `A` be nonnegative below `k` and let `t` be a vector with
`t k = 1`, vanishing above `k`, and satisfying `t j ≤ ∑_i m j i · t i` for `j < k`. If the
pairing of `t` with the weight `q ↦ A q - ∑_p m p q · A p` is nonnegative, then `A k ≥ 0`. -/
theorem nonneg_of_pairing_nonneg (hm : ∀ p q, m p q ≠ 0 → p < q) {A : Fin s → ℤ} {k : Fin s}
    (hA : ∀ i < k, 0 ≤ A i) {t : Fin s → ℕ} (htk : t k = 1) (ht : ∀ j, k < j → t j = 0)
    (hle : ∀ j < k, t j ≤ ∑ i, m j i * t i)
    (h : 0 ≤ ∑ j, (A j - ∑ i, (m i j : ℤ) * A i) * t j) : 0 ≤ A k := by
  -- the coefficient of `A i` in the pairing
  set c : Fin s → ℤ := fun i => (t i : ℤ) - ∑ j, (m i j : ℤ) * t j with hc
  have hsum : ∑ j, (A j - ∑ i, (m i j : ℤ) * A i) * t j = ∑ i, A i * c i := by
    simp only [hc, sub_mul, mul_sub, sum_sub_distrib, sum_mul, mul_sum]
    rw [sum_comm (f := fun j i => (m i j : ℤ) * A i * t j)]
    congr 1
    refine sum_congr rfl fun i _ => sum_congr rfl fun j _ => ?_
    ring
  -- `t` vanishes beyond any vertex `i ≥ k` along the arrows
  have hzero : ∀ i, k ≤ i → ∑ j, (m i j : ℤ) * t j = 0 := fun i hi =>
    sum_eq_zero fun j _ => by
      by_cases hmij : m i j = 0
      · simp [hmij]
      · rw [ht j (lt_of_le_of_lt hi (hm i j hmij)), Nat.cast_zero, mul_zero]
  have hck : c k = 1 := by simp [hc, htk, hzero k le_rfl]
  have hterm : ∀ i ∈ univ.erase k, A i * c i ≤ 0 := fun i hi => by
    rcases lt_or_gt_of_ne (ne_of_mem_erase hi) with hik | hik
    · refine mul_nonpos_of_nonneg_of_nonpos (hA i hik) ?_
      have := hle i hik
      simp only [hc, sub_nonpos]
      exact_mod_cast this
    · simp [hc, ht i hik, hzero i hik.le]
  rw [hsum, ← add_sum_erase _ _ (mem_univ k), hck, mul_one] at h
  linarith [sum_nonpos hterm]

/-- The **dimension vector attached to a weight**: `0` off the support of `n`, and
`σ q + ∑_{p < q} m p q · A p` on it. -/
def liftWeight (m : Fin s → Fin s → ℕ) (n : Fin s → ℕ) (σ : Fin s → ℤ) (q : Fin s) : ℤ :=
  if n q = 0 then 0
  else σ q + ∑ p : Fin s, if _h : p < q then (m p q : ℤ) * liftWeight m n σ p else 0
termination_by q.val
decreasing_by assumption

theorem liftWeight_of_eq_zero (n : Fin s → ℕ) (σ : Fin s → ℤ) {q : Fin s} (hq : n q = 0) :
    liftWeight m n σ q = 0 := by
  rw [liftWeight, ite_eq_left hq]

theorem liftWeight_of_ne_zero (hm : ∀ p q, m p q ≠ 0 → p < q) (n : Fin s → ℕ) (σ : Fin s → ℤ)
    {q : Fin s} (hq : n q ≠ 0) :
    liftWeight m n σ q = σ q + ∑ p, (m p q : ℤ) * liftWeight m n σ p := by
  rw [liftWeight, ite_eq_right hq]
  congr 1
  refine sum_congr rfl fun p _ => ?_
  split_ifs with hpq
  · rfl
  · have : m p q = 0 := by_contra fun h => hpq (hm p q h)
    simp [this]

/-- On the support of `n`, the vector `liftWeight m n σ` solves `A q - ∑_p m p q · A p = σ q`. -/
theorem liftWeight_sub_sum (hm : ∀ p q, m p q ≠ 0 → p < q) (n : Fin s → ℕ) (σ : Fin s → ℤ)
    {q : Fin s} (hq : n q ≠ 0) :
    liftWeight m n σ q - ∑ p, (m p q : ℤ) * liftWeight m n σ p = σ q := by
  rw [liftWeight_of_ne_zero hm n σ hq]
  ring

/-- **Positivity of `liftWeight`** (the combinatorial core of Baldoni–Vergne–Walter,
Lemma 4.4). Suppose that every vertex `k` in the support of `n` carries a vector `θ k` with
`θ k k = 1`, vanishing above `k` and off the support of `n`, satisfying
`θ k j ≤ ∑_i m j i · θ k i` for `j < k`, and with `∑_j σ j · θ k j ≥ 0`. Then
`liftWeight m n σ ≥ 0`. -/
theorem liftWeight_nonneg (hm : ∀ p q, m p q ≠ 0 → p < q) (n : Fin s → ℕ) (σ : Fin s → ℤ)
    (θ : Fin s → Fin s → ℕ) (hθk : ∀ k, n k ≠ 0 → θ k k = 1)
    (hθgt : ∀ k, n k ≠ 0 → ∀ j, k < j → θ k j = 0)
    (hθle : ∀ k, n k ≠ 0 → ∀ j < k, θ k j ≤ ∑ i, m j i * θ k i)
    (hθn : ∀ k, n k ≠ 0 → ∀ j, n j = 0 → θ k j = 0)
    (hσ : ∀ k, n k ≠ 0 → 0 ≤ ∑ j, σ j * θ k j) (k : Fin s) : 0 ≤ liftWeight m n σ k := by
  induction k using WellFoundedLT.induction with
  | ind k ih =>
    by_cases hk : n k = 0
    · rw [liftWeight_of_eq_zero n σ hk]
    refine nonneg_of_pairing_nonneg hm (fun i hi => ih i hi) (hθk k hk) (hθgt k hk)
      (hθle k hk) ?_
    refine (hσ k hk).trans_eq (sum_congr rfl fun j _ => ?_)
    by_cases hj : n j = 0
    · simp [hθn k hk j hj]
    · rw [liftWeight_sub_sum hm n σ hj]

end Combinatorics

/-! ### A dimension bound for intersections of kernels -/

section Rank

variable {K V W : Type*} [Field K] [AddCommGroup V] [Module K V] [FiniteDimensional K V]
  [AddCommGroup W] [Module K W]

/-- The dimension of a finite sum of subspaces is at most the sum of their dimensions. -/
theorem finrank_iSup_le_sum {α : Type*} [Fintype α] (p : α → Submodule K V) :
    Module.finrank K ↥(⨆ a, p a) ≤ ∑ a, Module.finrank K (p a) := by
  classical
  rw [← Finset.sup_univ_eq_iSup]
  induction (Finset.univ : Finset α) using Finset.induction_on with
  | empty => simp
  | insert a s ha ih =>
    rw [Finset.sup_insert, Finset.sum_insert ha]
    exact (Submodule.finrank_add_le_finrank_add_finrank _ _).trans (Nat.add_le_add_left ih _)

/-- **Rank of a map controlled by finitely many maps.** If every vector killed by all the `g a`
is killed by `f`, then `rank f ≤ ∑_a rank (g a)`. -/
theorem finrank_range_le_sum_of_iInf_ker_le {α : Type*} [Fintype α] {W' : α → Type*}
    [∀ a, AddCommGroup (W' a)] [∀ a, Module K (W' a)] [∀ a, FiniteDimensional K (W' a)]
    (f : V →ₗ[K] W) (g : (a : α) → V →ₗ[K] W' a) (h : ⨅ a, LinearMap.ker (g a) ≤ LinearMap.ker f) :
    Module.finrank K (LinearMap.range f) ≤ ∑ a, Module.finrank K (LinearMap.range (g a)) := by
  classical
  set G := LinearMap.pi g
  have hker : LinearMap.ker G ≤ LinearMap.ker f := by rwa [LinearMap.ker_pi]
  have h₁ : Module.finrank K (LinearMap.range f) ≤ Module.finrank K (LinearMap.range G) := by
    have := Submodule.finrank_mono hker
    have hf := LinearMap.finrank_range_add_finrank_ker f
    have hG := LinearMap.finrank_range_add_finrank_ker G
    omega
  have h₂ : LinearMap.range G ≤
      ⨆ a, LinearMap.range (LinearMap.single K W' a ∘ₗ g a) := by
    rintro _ ⟨x, rfl⟩
    rw [show G x = ∑ a, LinearMap.single K W' a (g a x) from
      (Finset.univ_sum_single (G x)).symm]
    exact Submodule.sum_mem _ fun a _ =>
      Submodule.mem_iSup_of_mem a (LinearMap.mem_range_self (LinearMap.single K W' a ∘ₗ g a) x)
  refine h₁.trans ((Submodule.finrank_mono h₂).trans ((finrank_iSup_le_sum _).trans
    (Finset.sum_le_sum fun a _ => ?_)))
  rw [LinearMap.range_comp]
  exact Submodule.finrank_map_le _ _

end Rank

/-! ### Words of arrows -/

namespace FQuiver

variable (Q : FQuiver)

/-- The **words** of arrows of length less than the number of vertices. Since arrows go forward,
longer words act by zero (`FQuiver.wordLin_apply_eq_zero`). -/
abbrev Word : Type := {w : List Q.Arrow // w.length < Q.s}

instance : Finite Q.Word :=
  Set.Finite.to_subtype (List.finite_length_lt Q.Arrow Q.s)

noncomputable instance : Fintype Q.Word :=
  Fintype.ofFinite _

section Words

variable {R : Type*} [CommRing R] {ι : Fin Q.s → Type} [∀ p, Fintype (ι p)]
  [∀ p, DecidableEq (ι p)]

/-- The action of a word of arrows on families of vectors, one vector per vertex. The arrow
`e : p → q` takes the component at `p`, applies `V e` and puts the result at `q`; the last letter
of the word acts first. -/
def wordLin (V : Q.Rep R ι) :
    List Q.Arrow → (((p : Fin Q.s) → ι p → R) →ₗ[R] ((p : Fin Q.s) → ι p → R))
  | [] => LinearMap.id
  | e :: w => LinearMap.single R (fun p => ι p → R) (Q.tgt e) ∘ₗ Matrix.toLin' (V e) ∘ₗ
      LinearMap.proj (Q.src e) ∘ₗ wordLin V w

@[simp] theorem wordLin_nil (V : Q.Rep R ι) (x : (p : Fin Q.s) → ι p → R) :
    Q.wordLin V [] x = x :=
  rfl

theorem wordLin_cons (V : Q.Rep R ι) (e : Q.Arrow) (w : List Q.Arrow)
    (x : (p : Fin Q.s) → ι p → R) :
    Q.wordLin V (e :: w) x = Pi.single (Q.tgt e) (V e *ᵥ Q.wordLin V w x (Q.src e)) :=
  rfl

theorem wordLin_append (V : Q.Rep R ι) (w w' : List Q.Arrow) (x : (p : Fin Q.s) → ι p → R) :
    Q.wordLin V (w ++ w') x = Q.wordLin V w (Q.wordLin V w' x) := by
  induction w with
  | nil => rfl
  | cons e w ih => rw [List.cons_append, wordLin_cons, wordLin_cons, ih]

/-- **Words move components forward**: if `x` vanishes at the vertices below `m`, then `w · x`
vanishes at the vertices below `m + |w|`. -/
theorem wordLin_apply_eq_zero (V : Q.Rep R ι) (w : List Q.Arrow) {x : (p : Fin Q.s) → ι p → R}
    {m : ℕ} (hx : ∀ p : Fin Q.s, p.val < m → x p = 0) :
    ∀ q : Fin Q.s, q.val < m + w.length → Q.wordLin V w x q = 0 := by
  induction w with
  | nil => exact fun q hq => hx q (by simpa using hq)
  | cons e w ih =>
    intro q hq
    rw [wordLin_cons]
    by_cases he : (Q.src e).val < m + w.length
    · rw [ih _ he, Matrix.mulVec_zero, Pi.single_zero, Pi.zero_apply]
    · have hlt : (Q.src e).val < (Q.tgt e).val := Q.src_lt_tgt e
      have hne : q ≠ Q.tgt e := by
        rintro rfl
        simp only [List.length_cons] at hq
        omega
      exact Pi.single_eq_of_ne hne _

omit [∀ p, Fintype (ι p)] [∀ p, DecidableEq (ι p)] in
/-- The vector `v` placed at the vertex `j` vanishes at the vertices below `j`. -/
theorem single_eq_zero_of_lt {j : Fin Q.s} (v : ι j → R) :
    ∀ p : Fin Q.s, p.val < j.val → (Pi.single j v : (p : Fin Q.s) → ι p → R) p = 0 :=
  fun p hp => Pi.single_eq_of_ne (M := fun p => ι p → R) (show p ≠ j from fun h => by
    subst h; omega) v

theorem wordLin_map {S : Type*} [CommRing S] (f : R →+* S) (V : Q.Rep R ι) (w : List Q.Arrow)
    (x : (p : Fin Q.s) → ι p → R) :
    Q.wordLin (Q.mapArrowHom f V) w (fun p i => f (x p i)) =
      fun p i => f (Q.wordLin V w x p i) := by
  induction w with
  | nil => rfl
  | cons e w ih =>
    funext p i
    rw [wordLin_cons, wordLin_cons, ih]
    by_cases hp : p = Q.tgt e
    · subst hp
      simp only [Pi.single_eq_same, mapArrowHom_apply]
      rw [RingHom.map_mulVec]
      rfl
    · simp [Pi.single_eq_of_ne hp]

/-! ### The quotient generated by a covector -/

/-- The functional `v ↦ (w · v)_{k, i₀}` for all words `w`, on the vertex space at `j`: the
evaluations at `v` of the covectors `e_{i₀}^* ∘ V_w` for the paths `w` from `j` to `k`. -/
def wordFun (V : Q.Rep R ι) (k : Fin Q.s) (i₀ : ι k) (j : Fin Q.s) :
    (ι j → R) →ₗ[R] (Q.Word → R) :=
  LinearMap.pi fun w => LinearMap.proj i₀ ∘ₗ LinearMap.proj k ∘ₗ Q.wordLin V w.1 ∘ₗ
    LinearMap.single R (fun p => ι p → R) j

theorem wordFun_apply (V : Q.Rep R ι) (k : Fin Q.s) (i₀ : ι k) (j : Fin Q.s) (v : ι j → R)
    (w : Q.Word) : Q.wordFun V k i₀ j v w = Q.wordLin V w.1 (Pi.single j v) k i₀ :=
  rfl

/-- The matrix of `wordFun`; its entries are polynomial in the representation. -/
def wordMatrix (V : Q.Rep R ι) (k : Fin Q.s) (i₀ : ι k) (j : Fin Q.s) :
    Matrix Q.Word (ι j) R :=
  LinearMap.toMatrix' (Q.wordFun V k i₀ j)

theorem wordMatrix_map {S : Type*} [CommRing S] (f : R →+* S) (V : Q.Rep R ι) (k : Fin Q.s)
    (i₀ : ι k) (j : Fin Q.s) :
    (Q.wordMatrix V k i₀ j).map f = Q.wordMatrix (Q.mapArrowHom f V) k i₀ j := by
  ext w i
  simp only [wordMatrix, Matrix.map_apply, LinearMap.toMatrix'_apply, wordFun_apply]
  have hx : (fun p i' => f ((Pi.single j (Pi.single i 1) : (p : Fin Q.s) → ι p → R) p i')) =
      (Pi.single j (Pi.single i 1) : (p : Fin Q.s) → ι p → S) := by
    funext p i'
    by_cases hp : p = j
    · subst hp
      by_cases hi : i' = i
      · subst hi; simp
      · simp [Pi.single_eq_of_ne hi]
    · simp [Pi.single_eq_of_ne hp]
  rw [← hx, Q.wordLin_map f V]

variable {K : Type*} [Field K]

theorem rank_wordMatrix (V : Q.Rep K ι) (k : Fin Q.s) (i₀ : ι k) (j : Fin Q.s) :
    (Q.wordMatrix V k i₀ j).rank = Module.finrank K (LinearMap.range (Q.wordFun V k i₀ j)) := by
  rw [Matrix.rank, wordMatrix, ← Matrix.toLin'_apply', Matrix.toLin'_toMatrix']

/-- The kernels of the functionals `wordFun` form a **subrepresentation**. -/
theorem isSubrep_ker_wordFun (V : Q.Rep K ι) (k : Fin Q.s) (i₀ : ι k) :
    Q.IsSubrep V fun j => LinearMap.ker (Q.wordFun V k i₀ j) := by
  intro e v hv
  rw [LinearMap.mem_ker] at hv ⊢
  funext w
  have hsingle : (Pi.single (Q.tgt e) (V e *ᵥ v) : (p : Fin Q.s) → ι p → K) =
      Q.wordLin V [e] (Pi.single (Q.src e) v) := by
    rw [wordLin_cons, wordLin_nil, Pi.single_eq_same]
  rw [wordFun_apply, hsingle, ← wordLin_append, Pi.zero_apply]
  by_cases hw : (w.1 ++ [e]).length < Q.s
  · have := congrFun hv ⟨w.1 ++ [e], hw⟩
    rwa [wordFun_apply] at this
  · rw [Q.wordLin_apply_eq_zero V _ (Q.single_eq_zero_of_lt v) k (by omega), Pi.zero_apply]

/-- The quotient by the kernels of `wordFun` has dimensions the ranks of `wordFun`. -/
theorem hasQuotientOfDim_wordFun (V : Q.Rep K ι) (k : Fin Q.s) (i₀ : ι k) :
    Q.HasQuotientOfDim V fun j => Module.finrank K (LinearMap.range (Q.wordFun V k i₀ j)) :=
  ⟨_, Q.isSubrep_ker_wordFun V k i₀, fun j => by
    rw [add_comm, LinearMap.finrank_range_add_finrank_ker, Module.finrank_fintype_fun_eq_card]⟩

/-- Above `k`, the functionals vanish. -/
theorem wordFun_eq_zero_of_lt (V : Q.Rep K ι) {k j : Fin Q.s} (i₀ : ι k) (h : k < j) :
    Q.wordFun V k i₀ j = 0 := by
  refine LinearMap.ext fun v => funext fun w => ?_
  rw [wordFun_apply, Q.wordLin_apply_eq_zero V _ (Q.single_eq_zero_of_lt v) k
    (by have : k.val < j.val := h; omega)]
  rfl

/-- At `k`, the quotient is one-dimensional. -/
theorem finrank_range_wordFun_self (V : Q.Rep K ι) (k : Fin Q.s) (i₀ : ι k) :
    Module.finrank K (LinearMap.range (Q.wordFun V k i₀ k)) = 1 := by
  have h0 : 0 < Q.s := k.pos
  set w₀ : Q.Word := ⟨[], h0⟩
  -- only the empty word contributes
  have hval : ∀ v w, Q.wordFun V k i₀ k v w = if w = w₀ then v i₀ else 0 := by
    intro v w
    rw [wordFun_apply]
    split_ifs with hw
    · subst hw
      simp [w₀]
    · have hlen : w.1.length ≠ 0 := fun h => hw (Subtype.ext (List.eq_nil_of_length_eq_zero h))
      rw [Q.wordLin_apply_eq_zero V _ (Q.single_eq_zero_of_lt v) k (by omega), Pi.zero_apply]
  have hrange : LinearMap.range (Q.wordFun V k i₀ k) = K ∙ Pi.single w₀ 1 := by
    apply le_antisymm
    · rintro _ ⟨v, rfl⟩
      refine Submodule.mem_span_singleton.mpr ⟨v i₀, funext fun w => ?_⟩
      rw [hval]
      by_cases hw : w = w₀
      · subst hw; simp
      · simp [hw]
    · rw [Submodule.span_singleton_le_iff_mem]
      refine ⟨Pi.single i₀ 1, funext fun w => ?_⟩
      rw [hval]
      by_cases hw : w = w₀
      · subst hw; simp
      · simp [hw]
  rw [hrange, finrank_span_singleton]
  exact fun h => one_ne_zero (congrFun h w₀ |>.symm.trans (Pi.single_eq_same w₀ 1)).symm

/-- **The rank inequality.** Away from `k`, the rank of `wordFun` at `j` is at most the sum of
its ranks at the targets of the arrows starting at `j`. -/
theorem finrank_range_wordFun_le (V : Q.Rep K ι) {k j : Fin Q.s} (i₀ : ι k) (hjk : j ≠ k) :
    Module.finrank K (LinearMap.range (Q.wordFun V k i₀ j)) ≤
      ∑ a : Q.Arrow, if Q.src a = j then
        Module.finrank K (LinearMap.range (Q.wordFun V k i₀ (Q.tgt a))) else 0 := by
  -- the map `v ↦ V_a (v placed at j, read at src a)`
  let L : (a : Q.Arrow) → (ι j → K) →ₗ[K] (ι (Q.src a) → K) := fun a =>
    LinearMap.proj (Q.src a) ∘ₗ LinearMap.single K (fun p => ι p → K) j
  let g : (a : Q.Arrow) → (ι j → K) →ₗ[K] (Q.Word → K) := fun a =>
    Q.wordFun V k i₀ (Q.tgt a) ∘ₗ Matrix.toLin' (V a) ∘ₗ L a
  refine (finrank_range_le_sum_of_iInf_ker_le _ g ?_).trans (Finset.sum_le_sum fun a _ => ?_)
  · intro v hv
    simp only [Submodule.mem_iInf, LinearMap.mem_ker] at hv
    rw [LinearMap.mem_ker]
    funext w
    rw [wordFun_apply, Pi.zero_apply]
    rcases List.eq_nil_or_concat' w.1 with hw | ⟨w', a, hw⟩
    · rw [hw, wordLin_nil, Pi.single_eq_of_ne (Ne.symm hjk), Pi.zero_apply]
    · have hlen : w'.length < Q.s := by
        have := w.2
        rw [hw, List.length_append] at this
        simp at this
        omega
      have := congrFun (hv a) ⟨w', hlen⟩
      rw [hw, wordLin_append, wordLin_cons, wordLin_nil]
      simpa [g, L, wordFun_apply] using this
  · split_ifs with ha
    · exact Submodule.finrank_mono (LinearMap.range_comp_le_range _ _)
    · have : L a = 0 := LinearMap.ext fun v =>
        show (Pi.single j v : (p : Fin Q.s) → ι p → K) (Q.src a) = 0 from
          Pi.single_eq_of_ne (M := fun p => ι p → K) ha v
      simp [g, this]

end Words

/-! ### Generic quotient dimensions -/

/-- The sum over the arrows starting at `j`, in terms of arrow multiplicities. -/
theorem sum_arrow_ite_src (θ : Fin Q.s → ℕ) (j : Fin Q.s) :
    (∑ a : Q.Arrow, if Q.src a = j then θ (Q.tgt a) else 0) = ∑ i, Q.arrows j i * θ i := by
  rw [Fintype.sum_sigma, Fintype.sum_prod_type]
  simp only [src, tgt]
  rw [Finset.sum_eq_single j]
  · simp
  · intro p _ hp
    simp [hp]
  · simp

section GenericQuot

variable (K : Type*) [Field K] (ι : Fin Q.s → Type) [∀ p, Fintype (ι p)]
  [∀ p, DecidableEq (ι p)]

/-- The **generic quotient dimensions** for the covector `e_{i₀}^*` at the vertex `k`: the
generic ranks of the word matrices of the universal representation. -/
noncomputable def genericQuotDim (k : Fin Q.s) (i₀ : ι k) (j : Fin Q.s) : ℕ :=
  genericRank (Q.wordMatrix (Q.univRep K ι) k i₀ j)

variable {K ι}

theorem map_eval_wordMatrix_univRep (x : Q.Entry ι → K) (k : Fin Q.s) (i₀ : ι k)
    (j : Fin Q.s) :
    (Q.wordMatrix (Q.univRep K ι) k i₀ j).map (MvPolynomial.eval x) =
      Q.wordMatrix (Q.ofCoord x) k i₀ j := by
  rw [wordMatrix_map, mapArrowHom_eval_univArrowHom]
  rfl

/-- At a generic point, all the word matrices have their generic ranks. -/
theorem eventually_finrank_range_wordFun (k : Fin Q.s) (i₀ : ι k) :
    ∀ᶠ x in genericFilter K (Q.Entry ι), ∀ j,
      Module.finrank K (LinearMap.range (Q.wordFun (Q.ofCoord x) k i₀ j)) =
        Q.genericQuotDim K ι k i₀ j := by
  refine Filter.eventually_all.mpr fun j => ?_
  filter_upwards [eventually_rank_eq_genericRank (Q.wordMatrix (Q.univRep K ι) k i₀ j)] with x hx
  rw [← Q.rank_wordMatrix, ← map_eval_wordMatrix_univRep, hx]
  rfl

variable [Infinite K]

/-- **A general representation has a quotient of dimension `genericQuotDim`.** -/
theorem generalQuot_genericQuotDim (k : Fin Q.s) (i₀ : ι k) :
    Q.GeneralQuot K ι (Q.genericQuotDim K ι k i₀) := by
  refine (zariskiDense_of_eventually (Q.eventually_finrank_range_wordFun k i₀)).mono ?_
  intro x hx
  refine ⟨Q.ofCoord x, ?_, Q.coord_ofCoord x⟩
  have := Q.hasQuotientOfDim_wordFun (Q.ofCoord x) k i₀
  simp only [Set.mem_ofPred_eq] at hx
  simp only [hx] at this
  exact this

theorem genericQuotDim_self (k : Fin Q.s) (i₀ : ι k) : Q.genericQuotDim K ι k i₀ k = 1 := by
  obtain ⟨x, hx⟩ := (Q.eventually_finrank_range_wordFun (K := K) k i₀).exists
  rw [← hx k, finrank_range_wordFun_self]

theorem genericQuotDim_of_lt {k j : Fin Q.s} (i₀ : ι k) (h : k < j) :
    Q.genericQuotDim K ι k i₀ j = 0 := by
  obtain ⟨x, hx⟩ := (Q.eventually_finrank_range_wordFun (K := K) k i₀).exists
  rw [← hx j, Q.wordFun_eq_zero_of_lt _ i₀ h, LinearMap.range_zero, finrank_bot]

theorem genericQuotDim_le (k : Fin Q.s) (i₀ : ι k) {j : Fin Q.s} (hjk : j ≠ k) :
    Q.genericQuotDim K ι k i₀ j ≤ ∑ i, Q.arrows j i * Q.genericQuotDim K ι k i₀ i := by
  obtain ⟨x, hx⟩ := (Q.eventually_finrank_range_wordFun (K := K) k i₀).exists
  rw [← sum_arrow_ite_src, ← hx j]
  refine (Q.finrank_range_wordFun_le _ i₀ hjk).trans_eq (Finset.sum_congr rfl fun a _ => ?_)
  rw [hx]

omit [Infinite K] in
theorem genericQuotDim_le_card (k : Fin Q.s) (i₀ : ι k) (j : Fin Q.s) :
    Q.genericQuotDim K ι k i₀ j ≤ Fintype.card (ι j) :=
  genericRank_le_card_width _

/-- **Positivity of `liftWeight`** (Baldoni–Vergne–Walter, Lemma 4.4). If `∑_p σ_p β_p ≥ 0` for
every `β` such that a general representation on `ι` has a quotient of dimension `β`, then the
dimension vector `liftWeight` attached to `σ` and `dim ι` is nonnegative. -/
theorem liftWeight_nonneg_of_generalQuot (σ : Fin Q.s → ℤ)
    (hσ : ∀ β : Fin Q.s → ℕ, Q.GeneralQuot K ι β → 0 ≤ ∑ p, σ p * (β p : ℤ)) (k : Fin Q.s) :
    0 ≤ liftWeight Q.arrows (dimVec ι) σ k := by
  classical
  let θ : Fin Q.s → Fin Q.s → ℕ := fun k =>
    if h : Nonempty (ι k) then Q.genericQuotDim K ι k h.some else 0
  have hθ : ∀ k, dimVec ι k ≠ 0 → ∃ i₀ : ι k, θ k = Q.genericQuotDim K ι k i₀ := fun k hk => by
    have h : Nonempty (ι k) := Fintype.card_pos_iff.mp (Nat.pos_of_ne_zero hk)
    exact ⟨h.some, dite_eq_left h⟩
  refine liftWeight_nonneg Q.forward (dimVec ι) σ θ (fun k hk => ?_) (fun k hk j hj => ?_)
    (fun k hk j hj => ?_) (fun k hk j hj => ?_) (fun k hk => ?_) k
  · obtain ⟨i₀, h⟩ := hθ k hk
    rw [h, genericQuotDim_self]
  · obtain ⟨i₀, h⟩ := hθ k hk
    rw [h, genericQuotDim_of_lt _ i₀ hj]
  · obtain ⟨i₀, h⟩ := hθ k hk
    rw [h]
    exact Q.genericQuotDim_le k i₀ hj.ne
  · obtain ⟨i₀, h⟩ := hθ k hk
    rw [h]
    have := Q.genericQuotDim_le_card (K := K) k i₀ j
    rw [dimVec_apply] at hj
    omega
  · obtain ⟨i₀, h⟩ := hθ k hk
    rw [h]
    exact hσ _ (Q.generalQuot_genericQuotDim k i₀)

end GenericQuot

end FQuiver

end QuiverInvariants
