import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.LinearAlgebra.Matrix.MvPolynomial
import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
import Mathlib.RingTheory.Adjoin.Basic

/-!
# Polynomial functions on a group with coordinates

A *coordinate system* on a type `G` is a map `c : G → σ → K`. A function `G → K` is *polynomial*
in these coordinates when it is `g ↦ P(c g)` for a polynomial `P` in the variables `σ`. The
polynomial functions form the subalgebra `GLRep.coordFunctions K c` of `G → K`.

The coordinate systems used in this library are:

* `GLRep.glCoord K n`: the matrix entries of `g ∈ GL_n(K)`;
* `GLRep.leviCoord K d`: the matrix entries of all blocks of `g ∈ ∏_p GL_{d_p}(K)`;
* `GLRep.torusCoord K κ`: the entries of `t ∈ (Kˣ)^κ`.

Each of them has dense image in the Zariski sense: a polynomial vanishing at every point `c g`
is zero (`GLRep.IsZariskiDense`). For the general linear group this holds because `det · P`
vanishes on all matrices; this is what turns identities between polynomial functions on the group
into identities of polynomials.

## Main definitions

* `GLRep.coordEval`, `GLRep.coordFunctions`: evaluation of polynomials in the coordinates, and
  its range.
* `GLRep.IsZariskiDense`: polynomials are determined by their values at the points `c g`.
* `GLRep.LeviGroup K d`: the group `∏_{p < s} GL_{d_p}(K)`.

## Main results

* `GLRep.comp_mem_coordFunctions`: polynomial functions pull back along maps whose coordinates
  are polynomial.
* `GLRep.isZariskiDense_of_ne_zero`: a coordinate system whose image contains the complement of
  the zero set of a nonzero polynomial is dense, over an infinite domain.
* `GLRep.isZariskiDense_glCoord`, `GLRep.isZariskiDense_leviCoord`,
  `GLRep.isZariskiDense_torusCoord`.
-/

namespace GLRep

open MvPolynomial

noncomputable section

section Coordinates

variable (K : Type*) [CommRing K] {G : Type*} {σ : Type*}

/-- Evaluation of polynomials in the coordinates `c`: the algebra map sending `P` to the function
`g ↦ P(c g)`. -/
def coordEval (c : G → σ → K) : MvPolynomial σ K →ₐ[K] (G → K) :=
  aeval fun s g => c g s

theorem coordEval_apply (c : G → σ → K) (P : MvPolynomial σ K) (g : G) :
    coordEval K c P g = eval (c g) P := by
  simpa [coordEval, aeval_eq_eval] using
    comp_aeval_apply (fun s g => c g s) (Pi.evalAlgHom K (fun _ : G => K) g) P

/-- The functions on `G` that are polynomial in the coordinates `c`. -/
def coordFunctions (c : G → σ → K) : Subalgebra K (G → K) :=
  (coordEval K c).range

variable {K}

theorem mem_coordFunctions {c : G → σ → K} {f : G → K} :
    f ∈ coordFunctions K c ↔ ∃ P : MvPolynomial σ K, ∀ g, f g = eval (c g) P := by
  constructor
  · rintro ⟨P, rfl⟩
    exact ⟨P, fun g => coordEval_apply K c P g⟩
  · rintro ⟨P, hP⟩
    exact ⟨P, funext fun g => (coordEval_apply K c P g).trans (hP g).symm⟩

theorem eval_mem_coordFunctions (c : G → σ → K) (P : MvPolynomial σ K) :
    (fun g => eval (c g) P) ∈ coordFunctions K c :=
  mem_coordFunctions.mpr ⟨P, fun _ => rfl⟩

/-- The coordinates themselves are polynomial functions. -/
theorem coord_mem_coordFunctions (c : G → σ → K) (s : σ) :
    (fun g => c g s) ∈ coordFunctions K c :=
  mem_coordFunctions.mpr ⟨X s, fun g => by simp⟩

/-- The polynomial functions are the subalgebra generated by the coordinates. -/
theorem coordFunctions_eq_adjoin (c : G → σ → K) :
    coordFunctions K c = Algebra.adjoin K (Set.range fun s g => c g s) :=
  aeval_range _

/-- A subalgebra containing the coordinates contains every polynomial function. -/
theorem coordFunctions_le {c : G → σ → K} {A : Subalgebra K (G → K)}
    (h : ∀ s, (fun g => c g s) ∈ A) : coordFunctions K c ≤ A := by
  rw [coordFunctions_eq_adjoin, Algebra.adjoin_le_iff]
  rintro _ ⟨s, rfl⟩
  exact h s

/-- The algebra map `f ↦ f ∘ φ` between algebras of functions. -/
def precompAlgHom {H : Type*} (φ : H → G) : (G → K) →ₐ[K] (H → K) where
  toFun f := f ∘ φ
  map_one' := rfl
  map_mul' _ _ := rfl
  map_zero' := rfl
  map_add' _ _ := rfl
  commutes' _ := rfl

/-- **Pulling back polynomial functions.** If the coordinates of `φ h` are polynomial in the
coordinates `c'` of `h`, then `f ∘ φ` is polynomial whenever `f` is. -/
theorem comp_mem_coordFunctions {H τ : Type*} {c : G → σ → K} {c' : H → τ → K} (φ : H → G)
    (hφ : ∀ s, (fun h => c (φ h) s) ∈ coordFunctions K c') {f : G → K}
    (hf : f ∈ coordFunctions K c) : f ∘ φ ∈ coordFunctions K c' := by
  have hle : (coordFunctions K c).map (precompAlgHom (K := K) φ) ≤ coordFunctions K c' := by
    rw [coordFunctions_eq_adjoin, AlgHom.map_adjoin, Algebra.adjoin_le_iff]
    rintro _ ⟨_, ⟨s, rfl⟩, rfl⟩
    exact hφ s
  exact hle ⟨f, hf, rfl⟩

/-! ### Zariski density -/

/-- The coordinates `c` have **Zariski-dense image**: a polynomial vanishing at every point
`c g` is zero. -/
def IsZariskiDense (c : G → σ → K) : Prop :=
  ∀ P : MvPolynomial σ K, (∀ g, eval (c g) P = 0) → P = 0

theorem IsZariskiDense.eq_of_forall_eval_eq {c : G → σ → K} (hc : IsZariskiDense c)
    {P Q : MvPolynomial σ K} (h : ∀ g, eval (c g) P = eval (c g) Q) : P = Q :=
  sub_eq_zero.mp (hc _ fun g => by rw [map_sub, h, sub_self])

/-- Over a dense coordinate system, a polynomial function determines its polynomial. -/
theorem IsZariskiDense.injective_coordEval {c : G → σ → K} (hc : IsZariskiDense c) :
    Function.Injective (coordEval K c) := fun P Q h =>
  hc.eq_of_forall_eval_eq fun g => by
    rw [← coordEval_apply K c P g, ← coordEval_apply K c Q g, h]

/-- **A criterion for density.** Over an infinite integral domain, if every point at which a
nonzero polynomial `D` does not vanish is a point `c g`, then `c` has dense image. -/
theorem isZariskiDense_of_ne_zero [IsDomain K] [Infinite K] {c : G → σ → K}
    (D : MvPolynomial σ K) (hD : D ≠ 0) (h : ∀ x, eval x D ≠ 0 → ∃ g, c g = x) :
    IsZariskiDense c := by
  intro P hP
  have hDP : D * P = 0 := MvPolynomial.funext fun x => by
    rw [map_mul, map_zero]
    by_cases hx : eval x D = 0
    · rw [hx, zero_mul]
    · obtain ⟨g, rfl⟩ := h x hx
      rw [hP g, mul_zero]
  exact (mul_eq_zero.mp hDP).resolve_left hD

end Coordinates

/-! ### The general linear group -/

section GeneralLinear

variable (K : Type*) [CommRing K] (n : ℕ)

/-- The matrix entries of an element of `GL_n(K)`. -/
def glCoord : GL (Fin n) K → Fin n × Fin n → K := fun g p => (g : Matrix (Fin n) (Fin n) K) p.1 p.2

@[simp] theorem glCoord_apply (g : GL (Fin n) K) (i j : Fin n) :
    glCoord K n g (i, j) = (g : Matrix (Fin n) (Fin n) K) i j := rfl

/-- The generic determinant, a polynomial in the matrix entries. -/
def detPoly : MvPolynomial (Fin n × Fin n) K := (Matrix.mvPolynomialX (Fin n) (Fin n) K).det

/-- The matrix with entries `x`. -/
def entryMatrix {n : ℕ} (x : Fin n × Fin n → K) : Matrix (Fin n) (Fin n) K :=
  Matrix.of fun i j => x (i, j)

theorem eval_detPoly (x : Fin n × Fin n → K) : eval x (detPoly K n) = (entryMatrix K x).det := by
  rw [detPoly, Matrix.eval_det_mvPolynomialX]
  rfl

theorem detPoly_ne_zero [Nontrivial K] : detPoly K n ≠ 0 :=
  Matrix.det_mvPolynomialX_ne_zero (Fin n) K

theorem eval_glCoord_detPoly (g : GL (Fin n) K) :
    eval (glCoord K n g) (detPoly K n) = (g : Matrix (Fin n) (Fin n) K).det := by
  rw [eval_detPoly]
  rfl

/-- **`GL_n(K)` is Zariski dense in the matrices**, over an infinite field. -/
theorem isZariskiDense_glCoord (K : Type*) [Field K] [Infinite K] (n : ℕ) :
    IsZariskiDense (glCoord K n) := by
  refine isZariskiDense_of_ne_zero (detPoly K n) (detPoly_ne_zero K n) fun x hx => ?_
  rw [eval_detPoly] at hx
  refine ⟨Matrix.GeneralLinearGroup.mkOfDetNeZero (entryMatrix K x) hx, ?_⟩
  funext p
  rfl

end GeneralLinear

/-! ### Levi groups -/

section Levi

variable (K : Type*) [CommRing K] {s : ℕ} (d : Fin s → ℕ)

/-- The **standard Levi group** `∏_{p < s} GL_{d_p}(K)`. -/
abbrev LeviGroup : Type _ := (p : Fin s) → GL (Fin (d p)) K

/-- The index type of the matrix entries of all blocks of a Levi group. -/
abbrev LeviIndex : Type := Σ p : Fin s, Fin (d p) × Fin (d p)

/-- The matrix entries of all blocks of an element of the Levi group. -/
def leviCoord : LeviGroup K d → LeviIndex d → K :=
  fun g x => (g x.1 : Matrix (Fin (d x.1)) (Fin (d x.1)) K) x.2.1 x.2.2

@[simp] theorem leviCoord_apply (g : LeviGroup K d) (p : Fin s) (i j : Fin (d p)) :
    leviCoord K d g ⟨p, i, j⟩ = (g p : Matrix (Fin (d p)) (Fin (d p)) K) i j := rfl

/-- The determinant of block `p`, as a polynomial in the entries of all blocks. -/
def blockDetPoly (p : Fin s) : MvPolynomial (LeviIndex d) K :=
  rename (fun ij : Fin (d p) × Fin (d p) => (⟨p, ij⟩ : LeviIndex d)) (detPoly K (d p))

theorem eval_blockDetPoly (x : LeviIndex d → K) (p : Fin s) :
    eval x (blockDetPoly K d p) =
      (entryMatrix K fun ij : Fin (d p) × Fin (d p) => x ⟨p, ij⟩).det := by
  rw [blockDetPoly, eval_rename, eval_detPoly]
  rfl

/-- **The Levi group is Zariski dense** in the product of the matrix spaces of its blocks. -/
theorem isZariskiDense_leviCoord (K : Type*) [Field K] [Infinite K] {s : ℕ} (d : Fin s → ℕ) :
    IsZariskiDense (leviCoord K d) := by
  refine isZariskiDense_of_ne_zero (∏ p, blockDetPoly K d p)
    (Finset.prod_ne_zero_iff.mpr fun p _ => by
      rw [blockDetPoly, Ne, ← map_zero (rename _)]
      exact fun h => detPoly_ne_zero K (d p)
        (rename_injective _ (fun a b h => by simpa using h) h)) fun x hx => ?_
  rw [map_prod, Finset.prod_ne_zero_iff] at hx
  refine ⟨fun p => Matrix.GeneralLinearGroup.mkOfDetNeZero _
    (by simpa [eval_blockDetPoly] using hx p (Finset.mem_univ p)), ?_⟩
  funext ⟨p, i, j⟩
  rfl

end Levi

/-! ### Split tori -/

section Torus

variable (K : Type*) [CommRing K] (κ : Type*)

/-- The entries of a point of the split torus `(Kˣ)^κ`. -/
def torusCoord : (κ → Kˣ) → κ → K := fun t i => (t i : K)

@[simp] theorem torusCoord_apply (t : κ → Kˣ) (i : κ) : torusCoord K κ t i = t i := rfl

/-- **The split torus is Zariski dense** in `K^κ`, over an infinite field and for finite `κ`. -/
theorem isZariskiDense_torusCoord (K : Type*) [Field K] [Infinite K] (κ : Type*) [Fintype κ] :
    IsZariskiDense (torusCoord K κ) := by
  refine isZariskiDense_of_ne_zero (∏ i, X i) (Finset.prod_ne_zero_iff.mpr fun i _ => X_ne_zero i)
    fun x hx => ?_
  rw [map_prod, Finset.prod_ne_zero_iff] at hx
  refine ⟨fun i => Units.mk0 (x i) (by simpa using hx i (Finset.mem_univ i)), ?_⟩
  funext i
  rfl

end Torus

end

end GLRep
