import RSCounterexample.FlagVarieties.Normality.Fulton.RankConditions

/-!
# Kazhdan–Lusztig patches

For a permutation `v`, the chart `v̇ U⁻` of `Fl_n` (an affine space) consists of the matrices `M`
with `M_{v c, c} = 1` and `M_{v a, c} = 0` for `a < c`; its free coordinates are the entries
`(r, c)` with `r ∉ v{0..c}` (`ChartVar v`). `kazhdanLusztigPoint v z` is the point with coordinates
`z`, `kazhdanLusztigMatrix K v` the generic point, and `kazhdanLusztigSubst K v : K[x_ij] → K[z]`
the substitution `x ↦ kazhdanLusztigMatrix`.

The **Kazhdan–Lusztig patch** of `X_w` at `v` is
`kazhdanLusztigPatch K v w = {z | kazhdanLusztigPoint v z ∈ π⁻¹ X_w}`.

**`map_kazhdanLusztigSubst_fultonIdeal`**: over an algebraically closed field of characteristic `0`,
the ideal of the patch is generated by Fulton's minors of the generic point of the chart. In
particular this ideal is radical: the Kazhdan–Lusztig patches are defined scheme-theoretically by
Fulton's rank conditions.

The proof restricts `orbitIdeal_lowerSet_eq_fultonIdeal` to the chart:
`kazhdanLusztigRestrict v : 𝒪(GL_n) → K[z]` (`det ↦ ± 1`), and a polynomial on the patch is lifted
to `𝒪(GL_n)` by homogenization on the big cell `G_v` (`exists_homogenize_poly`); on the chart itself
the representative `L(M)` of a chart point `M` is `M` (`chartMatrix_of_shape`).
-/

open Schubert Demazure.FlagModule Demazure.SchubertUnions FinPermutation

namespace FlagVarieties.PointModel

noncomputable section

set_option backward.isDefEq.respectTransparency false

variable {K : Type*} [Field K] {n : ℕ}

/-! ### Matrices of chart shape -/

/-- On a matrix of the shape of the chart `v̇ U⁻`, the chart minors are `1`. -/
theorem evalAt_chartMinor_of_shape (v : Equiv.Perm (Fin n)) {M : Matrix (Fin n) (Fin n) K}
    (h0 : ∀ a c, a < c → M (v a) c = 0) (h1 : ∀ c, M (v c) c = 1) (c : Fin n) :
    evalAt M (chartMinor K v c) = 1 := by
  rw [chartMinor, evalAt_rowMinor]
  have hlow : (M.submatrix (leadRows v c) (prefixIndex c)).IsLowerTriangular := by
    intro a b hab
    have hab' : a < b := OrderDual.toDual_lt_toDual.mp hab
    exact h0 (prefixIndex c a) (prefixIndex c b) (by
      change (prefixIndex c a).val < (prefixIndex c b).val
      simp only [prefixIndex]
      exact hab')
  rw [Matrix.det_of_isLowerTriangular _ hlow]
  exact Finset.prod_eq_one fun a _ => h1 _

/-- On a matrix of chart shape, the numerators of the chart are the entries. -/
theorem evalAt_numMinor_of_shape (v : Equiv.Perm (Fin n)) {M : Matrix (Fin n) (Fin n) K}
    (h0 : ∀ a c, a < c → M (v a) c = 0) (h1 : ∀ c, M (v c) c = 1) (r c : Fin n) :
    evalAt M (numMinor K v r c) = M r c := by
  rw [numMinor, evalAt_rowMinor]
  have hlow : (M.submatrix (snocRows v c r) (prefixIndex c)).IsLowerTriangular := by
    intro a b hab
    have hab' : a < b := OrderDual.toDual_lt_toDual.mp hab
    have ha : a.val < c.val := by
      have := b.isLt
      have : a.val < b.val := hab'
      omega
    simp only [Matrix.submatrix_apply, snocRows, ha, dite_true]
    exact h0 _ _ (by
      change a.val < (prefixIndex c b).val
      simp only [prefixIndex]
      exact hab')
  rw [Matrix.det_of_isLowerTriangular _ hlow, Fin.prod_univ_castSucc]
  have hd : ∀ a : Fin c.val,
      M.submatrix (snocRows v c r) (prefixIndex c) a.castSucc a.castSucc = 1 := by
    intro a
    simp only [Matrix.submatrix_apply, snocRows, Fin.val_castSucc, a.isLt, dite_true]
    exact h1 _
  have hl : M.submatrix (snocRows v c r) (prefixIndex c) (Fin.last c.val) (Fin.last c.val) =
      M r c := by
    simp only [Matrix.submatrix_apply, snocRows, Fin.val_last, lt_irrefl, dite_false]
    rfl
  rw [Finset.prod_eq_one fun a _ => hd a, one_mul, hl]

/-- **The chart representative of a chart point is the point itself.** -/
theorem chartMatrix_of_shape (v : Equiv.Perm (Fin n)) {M : Matrix (Fin n) (Fin n) K}
    (h0 : ∀ a c, a < c → M (v a) c = 0) (h1 : ∀ c, M (v c) c = 1) :
    chartMatrix K v M = M := by
  ext r c
  rw [chartMatrix_apply, evalAt_numMinor_of_shape v h0 h1, evalAt_chartMinor_of_shape v h0 h1,
    div_one]

/-! ### The chart `v̇ U⁻` and its coordinates -/

/-- The free coordinates of the chart `v̇ U⁻`: the positions `(r, c)` with `r ∉ v{0..c}`. -/
def ChartVar (v : Equiv.Perm (Fin n)) : Type :=
  {rc : Fin n × Fin n // ∀ j ≤ rc.2, v j ≠ rc.1}

/-- The point of the chart `v̇ U⁻` with coordinates `z`. -/
def kazhdanLusztigPoint (v : Equiv.Perm (Fin n)) (z : ChartVar v → K) : Matrix (Fin n) (Fin n) K :=
  fun r c => if h : ∀ j ≤ c, v j ≠ r then z ⟨(r, c), h⟩ else if r = v c then 1 else 0

/-- The generic point of the chart `v̇ U⁻`. -/
def kazhdanLusztigMatrix (K : Type*) [Field K] (v : Equiv.Perm (Fin n)) :
    Matrix (Fin n) (Fin n) (MvPolynomial (ChartVar v) K) :=
  fun r c => if h : ∀ j ≤ c, v j ≠ r then MvPolynomial.X ⟨(r, c), h⟩ else if r = v c then 1 else 0

theorem kazhdanLusztigPoint_self (v : Equiv.Perm (Fin n)) (z : ChartVar v → K) (c : Fin n) :
    kazhdanLusztigPoint v z (v c) c = 1 := by
  simp [kazhdanLusztigPoint]

theorem kazhdanLusztigPoint_lt (v : Equiv.Perm (Fin n)) (z : ChartVar v → K) {a c : Fin n}
    (hac : a < c) :
    kazhdanLusztigPoint v z (v a) c = 0 := by
  have h1 : ¬ ∀ j ≤ c, v j ≠ v a := fun h => h a hac.le rfl
  have h2 : v a ≠ v c := fun h => hac.ne (v.injective h)
  simp only [kazhdanLusztigPoint, dite_eq_right h1, ite_eq_right h2]

theorem kazhdanLusztigPoint_free (v : Equiv.Perm (Fin n)) (z : ChartVar v → K) (x : ChartVar v) :
    kazhdanLusztigPoint v z x.1.1 x.1.2 = z x := by
  simp only [kazhdanLusztigPoint, dite_eq_left x.2]
  rfl

/-- A matrix of chart shape is the chart point of its free entries. -/
theorem kazhdanLusztigPoint_of_shape (v : Equiv.Perm (Fin n)) {M : Matrix (Fin n) (Fin n) K}
    (h0 : ∀ a c, a < c → M (v a) c = 0) (h1 : ∀ c, M (v c) c = 1) :
    kazhdanLusztigPoint v (fun x => M x.1.1 x.1.2) = M := by
  ext r c
  unfold kazhdanLusztigPoint
  split_ifs with h h'
  · rfl
  · subst h'
    exact (h1 c).symm
  · push Not at h
    obtain ⟨j, hj, rfl⟩ := h
    have hjc : j < c := lt_of_le_of_ne hj fun e => h' (by rw [e])
    exact (h0 j c hjc).symm

theorem chartMinor_kazhdanLusztigPoint (v : Equiv.Perm (Fin n)) (z : ChartVar v → K) (c : Fin n) :
    evalAt (kazhdanLusztigPoint v z) (chartMinor K v c) = 1 :=
  evalAt_chartMinor_of_shape v (fun _ _ hac => kazhdanLusztigPoint_lt v z hac)
      (kazhdanLusztigPoint_self v z) c

theorem chartMatrix_kazhdanLusztigPoint (v : Equiv.Perm (Fin n)) (z : ChartVar v → K) :
    chartMatrix K v (kazhdanLusztigPoint v z) = kazhdanLusztigPoint v z :=
  chartMatrix_of_shape v (fun _ _ hac => kazhdanLusztigPoint_lt v z hac)
      (kazhdanLusztigPoint_self v z)

theorem sign_mul_det_kazhdanLusztigPoint (v : Equiv.Perm (Fin n)) (z : ChartVar v → K) :
    (Equiv.Perm.sign v : K) * (kazhdanLusztigPoint v z).det = 1 := by
  have h := det_chartMatrix v (kazhdanLusztigPoint v z) fun c => by
    rw [chartMinor_kazhdanLusztigPoint]
    exact one_ne_zero
  rwa [chartMatrix_kazhdanLusztigPoint] at h

theorem map_eval_kazhdanLusztigMatrix (v : Equiv.Perm (Fin n)) (z : ChartVar v → K) :
    (kazhdanLusztigMatrix K v).map (MvPolynomial.eval z) = kazhdanLusztigPoint v z := by
  ext r c
  simp only [Matrix.map_apply, kazhdanLusztigMatrix, kazhdanLusztigPoint]
  split_ifs <;> simp

/-! ### Restriction to the chart -/

/-- The substitution `x ↦ kazhdanLusztigMatrix K v`. -/
def kazhdanLusztigSubst (K : Type*) [Field K] (v : Equiv.Perm (Fin n)) :
    MatrixEntryPolynomial K n →ₐ[K] MvPolynomial (ChartVar v) K :=
  MvPolynomial.aeval fun rc => kazhdanLusztigMatrix K v rc.1 rc.2

theorem eval_kazhdanLusztigSubst (v : Equiv.Perm (Fin n)) (z : ChartVar v → K)
    (p : MatrixEntryPolynomial K n) :
    MvPolynomial.eval z (kazhdanLusztigSubst K v p) = evalAt (kazhdanLusztigPoint v z) p := by
  induction p using MvPolynomial.induction_on with
  | C a => simp [kazhdanLusztigSubst, evalAt]
  | add p q hp hq => rw [map_add, map_add, hp, hq, map_add]
  | mul_X p rc hp =>
    rw [map_mul, map_mul, hp, map_mul, evalAt_X, kazhdanLusztigSubst, MvPolynomial.aeval_X,
      ← map_eval_kazhdanLusztigMatrix (K := K) v z, Matrix.map_apply]

theorem isUnit_kazhdanLusztigSubst_genericDetPoly [Infinite K] (v : Equiv.Perm (Fin n)) :
    IsUnit (kazhdanLusztigSubst K v (genericDetPoly K n)) := by
  have h : kazhdanLusztigSubst K v (genericDetPoly K n) * MvPolynomial.C (Equiv.Perm.sign v : K) =
      1 :=
    MvPolynomial.funext fun z => by
      rw [map_mul, MvPolynomial.eval_C, eval_kazhdanLusztigSubst, evalAt_genericDetPoly, mul_comm,
        sign_mul_det_kazhdanLusztigPoint, map_one]
  exact IsUnit.of_mul_eq_one _ h

/-- The restriction `𝒪(GL_n) → K[z]` to the chart `v̇ U⁻`. -/
def kazhdanLusztigRestrict [Infinite K] (v : Equiv.Perm (Fin n)) :
    GLCoord K n →ₐ[K] MvPolynomial (ChartVar v) K :=
  IsLocalization.liftAlgHom (M := Submonoid.powers (genericDetPoly K n))
      (f := kazhdanLusztigSubst K v) (by
    rintro ⟨y, k, rfl⟩
    simpa using (isUnit_kazhdanLusztigSubst_genericDetPoly (K := K) v).pow k)

theorem kazhdanLusztigRestrict_algebraMap [Infinite K] (v : Equiv.Perm (Fin n))
    (p : MatrixEntryPolynomial K n) :
    kazhdanLusztigRestrict v (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n) p) =
        kazhdanLusztigSubst K v p := by
  rw [kazhdanLusztigRestrict, IsLocalization.liftAlgHom_apply]
  exact IsLocalization.lift_eq _ _

/-! ### Kazhdan–Lusztig patches -/

/-- The **Kazhdan–Lusztig patch** `X_w ∩ v̇ U⁻ B / B`, in the coordinates of the chart. -/
def kazhdanLusztigPatch (K : Type*) [Field K] (v w : Equiv.Perm (Fin n)) : Set (ChartVar v → K) :=
  {z | ∃ g ∈ orbitSet K (lowerSet w), (g : Matrix (Fin n) (Fin n) K) = kazhdanLusztigPoint v z}

theorem evalAt_rename_chartVar (v : Equiv.Perm (Fin n)) (M : Matrix (Fin n) (Fin n) K)
    (P : MvPolynomial (ChartVar v) K) :
    evalAt M (MvPolynomial.rename (fun x : ChartVar v => x.1) P) =
      MvPolynomial.eval (fun x => M x.1.1 x.1.2) P := by
  rw [evalAt, MvPolynomial.aeval_rename]
  rfl

theorem kazhdanLusztigPoint_chartMatrix (v : Equiv.Perm (Fin n)) (g : Matrix (Fin n) (Fin n) K)
    (hg : ∀ c, evalAt g (chartMinor K v c) ≠ 0) :
    kazhdanLusztigPoint v (fun x => chartMatrix K v g x.1.1 x.1.2) = chartMatrix K v g :=
  kazhdanLusztigPoint_of_shape v (fun _ _ hac => chartMatrix_eq_zero v g hac)
    (fun c => chartMatrix_self v g c (hg c))

/-- On the big cell `G_v`, the chart coordinates of a point of `π⁻¹ X_w` lie in the patch. -/
theorem mem_kazhdanLusztigPatch_chartMatrix {v w : Equiv.Perm (Fin n)} {g : GL (Fin n) K}
    (hg : g ∈ orbitSet K (lowerSet w))
    (hgv : ∀ c, evalAt (g : Matrix (Fin n) (Fin n) K) (chartMinor K v c) ≠ 0) :
    (fun x : ChartVar v => chartMatrix K v g x.1.1 x.1.2) ∈ kazhdanLusztigPatch K v w := by
  obtain ⟨β, hβdef⟩ : ∃ β : GL (Fin n) K, (β : Matrix (Fin n) (Fin n) K) = chartBeta K v g :=
    ⟨unitOfDet (chartBeta K v g) (chartBeta_det_isUnit v g hgv), coe_unitOfDet _ _⟩
  have hβ : IsBorel β := by
    unfold IsBorel
    rw [hβdef]
    exact chartBeta_isUpperTriangular v (g : Matrix (Fin n) (Fin n) K)
  refine ⟨g * β, orbitSet_mul_borel hg hβ, ?_⟩
  rw [kazhdanLusztigPoint_chartMatrix v _ hgv, Units.val_mul, hβdef]
  rfl

/-- **Kazhdan–Lusztig patches are defined scheme-theoretically by Fulton's rank conditions**: the
ideal of the patch of `X_w` at `v` is generated by Fulton's minors of the generic chart point. -/
theorem map_kazhdanLusztigSubst_fultonIdeal [IsAlgClosed K] [CharZero K]
    (v w : Equiv.Perm (Fin n)) :
    (fultonIdeal K w).map (kazhdanLusztigSubst K v) = MvPolynomial.vanishingIdeal K
        (kazhdanLusztigPatch K v w) := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨k, q, I, J, hI, hJ, rfl⟩
    refine Ideal.mem_comap.mpr (MvPolynomial.mem_vanishingIdeal_iff.mpr ?_)
    rintro z ⟨g, hg, hgz⟩
    change MvPolynomial.eval z _ = 0
    rw [eval_kazhdanLusztigSubst, ← hgz]
    exact evalAt_minorRC_eq_zero hI hJ hg
  · intro P hP
    rw [MvPolynomial.mem_vanishingIdeal_iff] at hP
    simp only [MvPolynomial.aeval_eq_eval] at hP
    obtain ⟨N, a, -, ha⟩ :=
      exists_homogenize_poly v (MvPolynomial.rename (fun x : ChartVar v => x.1) P)
    -- the homogenization vanishes on `π⁻¹ X_w`
    have hq : algebraMap (MatrixEntryPolynomial K n) (GLCoord K n) (a * chartPoly K v) ∈
        orbitIdeal K (lowerSet w) := by
      refine algebraMap_mem_orbitIdeal fun g hg => ?_
      by_cases hgv : ∀ c, evalAt (g : Matrix (Fin n) (Fin n) K) (chartMinor K v c) ≠ 0
      · rw [map_mul, ha _ hgv, evalAt_rename_chartVar,
          hP _ (mem_kazhdanLusztigPatch_chartMatrix hg hgv),
          mul_zero, zero_mul]
      · push Not at hgv
        obtain ⟨c, hc⟩ := hgv
        rw [map_mul, chartPoly, map_prod, Finset.prod_eq_zero (Finset.mem_univ c) hc, mul_zero]
    rw [orbitIdeal_lowerSet_eq_fultonIdeal] at hq
    -- restrict to the chart
    have hle : (fultonIdeal K w).map (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n)) ≤
        ((fultonIdeal K w).map (kazhdanLusztigSubst K v)).comap (kazhdanLusztigRestrict v) := by
      rw [Ideal.map_le_iff_le_comap]
      intro p hp
      rw [Ideal.mem_comap, Ideal.mem_comap, kazhdanLusztigRestrict_algebraMap]
      exact Ideal.mem_map_of_mem _ hp
    have h1 := hle hq
    rw [Ideal.mem_comap, kazhdanLusztigRestrict_algebraMap] at h1
    have hPeq : kazhdanLusztigSubst K v (a * chartPoly K v) = P := MvPolynomial.funext fun z => by
      have hz : ∀ c, evalAt (kazhdanLusztigPoint v z) (chartMinor K v c) ≠ 0 := fun c => by
        rw [chartMinor_kazhdanLusztigPoint]
        exact one_ne_zero
      have hf : evalAt (kazhdanLusztigPoint v z) (chartPoly K v) = 1 := by
        rw [chartPoly, map_prod]
        exact Finset.prod_eq_one fun c _ => chartMinor_kazhdanLusztigPoint v z c
      have hfun : (fun x : ChartVar v => kazhdanLusztigPoint v z x.1.1 x.1.2) = z :=
        funext fun x => kazhdanLusztigPoint_free v z x
      rw [eval_kazhdanLusztigSubst, map_mul, ha _ hz, hf, chartMatrix_kazhdanLusztigPoint,
          evalAt_rename_chartVar, hfun,
        one_pow, one_mul, mul_one]
    rwa [hPeq] at h1

/-- **Reducedness of the Kazhdan–Lusztig patches**: Fulton's minors generate a radical ideal of
the coordinate ring of the chart. -/
theorem isRadical_map_kazhdanLusztigSubst_fultonIdeal [IsAlgClosed K] [CharZero K]
    (v w : Equiv.Perm (Fin n)) :
    ((fultonIdeal K w).map (kazhdanLusztigSubst K v)).IsRadical := by
  rw [map_kazhdanLusztigSubst_fultonIdeal]
  rintro P ⟨m, hm⟩
  refine MvPolynomial.mem_vanishingIdeal_iff.mpr fun z hz => ?_
  have := MvPolynomial.mem_vanishingIdeal_iff.mp hm z hz
  rw [map_pow] at this
  exact eq_zero_of_pow_eq_zero this

end

end FlagVarieties.PointModel
