import RSCounterexample.FlagVarieties.Normality.Fulton.Schubert

/-!
# Fulton's rank conditions

For a permutation `w`, `r_w(k, q) = bruhatRank w k q = #{j ≤ k | w j ≥ q}` is the rank of the
south-west submatrix `ẇ_{[q, n), [0, k]}` of the permutation matrix. **Fulton's ideal**
`fultonIdeal K w ⊆ K[x_ij]` is generated by the minors of size `r_w(k, q) + 1` of the south-west
submatrices `x_{[q, n), [0, k]}` of the generic matrix: the rank conditions
`rank g_{[q, n), [0, k]} ≤ r_w(k, q)`.

**`orbitIdeal_lowerSet_eq_fultonIdeal`**: over an algebraically closed field of
characteristic `0`, the ideal of `π⁻¹ X_w` in `𝒪(GL_n)` is generated by Fulton's minors. Since
`π : GL_n → Fl_n` is a `B`-torsor, Fulton's rank conditions define `X_w` scheme-theoretically; in
particular the ideal they generate in `𝒪(GL_n)` is radical (`isRadical_map_fultonIdeal`).

* `minorRC_mem_orbitIdeal`: the rank conditions hold on `π⁻¹ X_w`: on `b₁ v̇ b₂`, `v ≤ w`, the
  south-west submatrix factors through the masked permutation matrix, of rank `r_v(k, q)`.
* `schubertIdeal_le_fultonIdeal`: a flag minor `Δ_T` with `T ≰ w{0..k}` has more than `r_w(k, q)`
  rows `≥ q` for some `q`, so it lies in the ideal of the `(r_w(k, q) + 1)`-minors of those rows
  (`det_mem_of_minors_mem`, by Laplace expansion along the other rows).
* With `orbitIdeal_lowerSet_eq` (`Fulton/Schubert.lean`) this closes the circle.
-/

open Schubert Demazure.FlagModule Demazure.SchubertUnions FinPermutation

namespace FlagVarieties.PointModel

noncomputable section

set_option backward.isDefEq.respectTransparency false

variable {K : Type*} [Field K] {n : ℕ}

/-! ### Minors of minors -/

/-- **Laplace descent**: if `u` rows of a square matrix are marked, and all `u × u` minors on marked
rows lie in an ideal, then so does the determinant. -/
theorem det_mem_of_minors_mem {R : Type*} [CommRing R] (𝔦 : Ideal R) (u : ℕ) :
    ∀ (t : ℕ) (M : Matrix (Fin t) (Fin t) R) (sp : Fin t → Prop) [DecidablePred sp],
      u ≤ (Finset.univ.filter sp).card →
      (∀ I J : Fin u → Fin t, (∀ a, sp (I a)) → (M.submatrix I J).det ∈ 𝔦) → M.det ∈ 𝔦 := by
  intro t
  induction t with
  | zero =>
    intro M sp _ hu hM
    have hu0 : u = 0 := Nat.le_zero.mp (hu.trans (by simp))
    subst hu0
    simpa [Matrix.det_isEmpty] using hM Fin.elim0 Fin.elim0 fun a => a.elim0
  | succ t ih =>
    intro M sp _ hu hM
    by_cases hut : u = t + 1
    · subst hut
      have hall : ∀ a, sp a := by
        intro a
        by_contra ha
        have hlt : (Finset.univ.filter sp).card < (Finset.univ : Finset (Fin (t + 1))).card :=
          Finset.card_lt_card (Finset.filter_ssubset.mpr ⟨a, Finset.mem_univ a, ha⟩)
        rw [Finset.card_univ, Fintype.card_fin] at hlt
        omega
      simpa using hM id id hall
    · have hle : (Finset.univ.filter sp).card ≤ t + 1 :=
        (Finset.card_filter_le _ _).trans (by simp)
      obtain ⟨i, hi⟩ : ∃ i : Fin (t + 1), u ≤ ((Finset.univ.filter sp).erase i).card := by
        by_cases hns : ∃ i, ¬ sp i
        · obtain ⟨i, hi⟩ := hns
          refine ⟨i, ?_⟩
          rw [Finset.erase_eq_of_notMem (by simp [hi])]
          exact hu
        · push Not at hns
          refine ⟨0, ?_⟩
          have hfu : Finset.univ.filter sp = Finset.univ :=
            Finset.filter_true_of_mem fun a _ => hns a
          rw [hfu, Finset.card_erase_of_mem (Finset.mem_univ _), Finset.card_univ,
            Fintype.card_fin]
          rw [hfu, Finset.card_univ, Fintype.card_fin] at hle hu
          omega
      have hcount : (Finset.univ.filter fun a : Fin t => sp (i.succAbove a)).card =
          ((Finset.univ.filter sp).erase i).card := by
        rw [← Finset.card_image_of_injective _ (Fin.succAbove_right_injective (p := i))]
        congr 1
        ext b
        simp only [Finset.mem_image, Finset.mem_filter, Finset.mem_univ, true_and,
          Finset.mem_erase]
        constructor
        · rintro ⟨a, ha, rfl⟩
          exact ⟨Fin.succAbove_ne i a, ha⟩
        · rintro ⟨hb, hsp⟩
          obtain ⟨a, rfl⟩ := Fin.exists_succAbove_eq hb
          exact ⟨a, hsp, rfl⟩
      rw [Matrix.det_succ_row M i]
      refine Submodule.sum_mem _ fun j _ => Ideal.mul_mem_left _ _ ?_
      refine ih (M.submatrix i.succAbove j.succAbove) (fun a => sp (i.succAbove a))
        (by rw [hcount]; exact hi) fun I J hI => ?_
      rw [Matrix.submatrix_submatrix]
      exact hM _ _ hI

/-! ### Fulton's ideal -/

/-- The minor of the generic matrix with rows `I` and columns `J`. -/
def minorRC (K : Type*) [Field K] {t : ℕ} (I J : Fin t → Fin n) : MatrixEntryPolynomial K n :=
  (Matrix.of fun a b => (MvPolynomial.X (I a, J b) : MatrixEntryPolynomial K n)).det

theorem evalAt_minorRC (g : Matrix (Fin n) (Fin n) K) {t : ℕ} (I J : Fin t → Fin n) :
    evalAt g (minorRC K I J) = (g.submatrix I J).det := by
  rw [minorRC, AlgHom.map_det]
  congr 1
  ext a b
  simp [AlgHom.mapMatrix_apply]

/-- **Fulton's ideal**: the minors of size `r_w(k, q) + 1` of the submatrices
`x_{[q, n), [0, k]}`. -/
def fultonIdeal (K : Type*) [Field K] (w : Equiv.Perm (Fin n)) :
    Ideal (MatrixEntryPolynomial K n) :=
  Ideal.span {p | ∃ (k q : Fin n) (I J : Fin (bruhatRank w k q + 1) → Fin n),
    (∀ a, q ≤ I a) ∧ (∀ b, J b ≤ k) ∧ p = minorRC K I J}

/-- **The forbidden flag minors lie in Fulton's ideal.** -/
theorem rowMinor_mem_fultonIdeal {w : Equiv.Perm (Fin n)} {k : Fin n} {T : FlagMinorRowSet k}
    (hT : ¬ galeLE T (flagPrefixRows w k)) : rowMinor K k T.rows ∈ fultonIdeal K w := by
  classical
  obtain ⟨q, hq⟩ : ∃ q : Fin n, ((flagPrefixRows w k).val.filter fun x => q ≤ x).card <
      (T.val.filter fun x => q ≤ x).card := by
    unfold galeLE at hT
    push Not at hT
    exact hT
  rw [← bruhatRank_eq_card_filter] at hq
  have hcard : (Finset.univ.filter fun a : Fin (k.val + 1) => q ≤ T.rows a).card =
      (T.val.filter fun x => q ≤ x).card := by
    have hT' : T.val.filter (fun x => q ≤ x) =
        (Finset.univ.filter fun a => q ≤ T.rows a).image T.rows := by
      conv_lhs => rw [← Finset.image_orderEmbOfFin_univ T.val
        (Finset.mem_powersetCard.mp T.property).2]
      rw [Finset.filter_image]
      rfl
    rw [hT', Finset.card_image_of_injective _ T.rows.injective]
  refine det_mem_of_minors_mem (fultonIdeal K w) (bruhatRank w k q + 1) (k.val + 1) _
    (fun a => q ≤ T.rows a) (by rw [hcard]; exact hq) fun I J hI => ?_
  exact Ideal.subset_span ⟨k, q, fun a => T.rows (I a), fun b => prefixIndex k (J b), hI,
    fun b => by
      change (prefixIndex k (J b)).val ≤ k.val
      have := (J b).isLt
      simp only [prefixIndex]
      omega,
    rfl⟩

theorem schubertIdeal_le_fultonIdeal (w : Equiv.Perm (Fin n)) :
    schubertIdeal K w ≤ fultonIdeal K w := by
  refine iSup_le fun k => Ideal.span_le.mpr ?_
  rintro _ ⟨T, hT, rfl⟩
  exact rowMinor_mem_fultonIdeal hT

/-- On `b₁ v̇ b₂`, the south-west submatrix factors through the masked permutation matrix. -/
theorem submatrix_borel_perm_borel {b₁ b₂ : Matrix (Fin n) (Fin n) K}
    (h₁ : b₁.IsUpperTriangular) (h₂ : b₂.IsUpperTriangular) (v : Equiv.Perm (Fin n))
    {k q : Fin n} {t : ℕ} {I J : Fin t → Fin n} (hI : ∀ a, q ≤ I a) (hJ : ∀ b, J b ≤ k) :
    (b₁ * permMat K v * b₂).submatrix I J =
      (b₁ * permMat K v).submatrix I id *
        Matrix.diagonal (fun j => if j ≤ k ∧ q ≤ v j then (1 : K) else 0) *
          b₂.submatrix id J := by
  ext a c
  have lhs : (b₁ * permMat K v * b₂).submatrix I J a c = ∑ j, b₁ (I a) (v j) * b₂ j (J c) := by
    rw [Matrix.submatrix_apply, Matrix.mul_apply]
    exact Finset.sum_congr rfl fun j _ => by rw [mul_permMat]
  have rhs : ((b₁ * permMat K v).submatrix I id *
      Matrix.diagonal (fun j => if j ≤ k ∧ q ≤ v j then (1 : K) else 0) *
        b₂.submatrix id J) a c =
      ∑ j, b₁ (I a) (v j) * (if j ≤ k ∧ q ≤ v j then (1 : K) else 0) * b₂ j (J c) := by
    rw [Matrix.mul_apply]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [Matrix.mul_diagonal, Matrix.submatrix_apply, Matrix.submatrix_apply, mul_permMat]
    rfl
  rw [lhs, rhs]
  refine Finset.sum_congr rfl fun j _ => ?_
  by_cases hjk : j ≤ k
  · by_cases hq : q ≤ v j
    · simp [hjk, hq]
    · have hz : b₁ (I a) (v j) = 0 := h₁ (lt_of_lt_of_le (lt_of_not_ge hq) (hI a))
      simp [hz]
  · have hz : b₂ j (J c) = 0 := h₂ (lt_of_le_of_lt (hJ c) (lt_of_not_ge hjk))
    simp [hz]

/-- **The rank conditions hold on `π⁻¹ X_w`.** -/
theorem evalAt_minorRC_eq_zero {w : Equiv.Perm (Fin n)} {k q : Fin n}
    {I J : Fin (bruhatRank w k q + 1) → Fin n} (hI : ∀ a, q ≤ I a) (hJ : ∀ b, J b ≤ k)
    {g : GL (Fin n) K} (hg : g ∈ orbitSet K (lowerSet w)) :
    evalAt (g : Matrix (Fin n) (Fin n) K) (minorRC K I J) = 0 := by
  classical
  obtain ⟨v, hv, b₁, b₂, h₁, h₂, rfl⟩ := mem_orbitSet.mp hg
  rw [evalAt_minorRC, Units.val_mul, Units.val_mul, coe_permGL,
    submatrix_borel_perm_borel h₁ h₂ v hI hJ]
  by_contra hdet
  have hrank := Matrix.rank_of_isUnit _ ((Matrix.isUnit_iff_isUnit_det _).mpr
    (isUnit_iff_ne_zero.mpr hdet))
  rw [Fintype.card_fin] at hrank
  have hle : ((b₁ * permMat K v).submatrix I id *
      Matrix.diagonal (fun j => if j ≤ k ∧ q ≤ v j then (1 : K) else 0) *
        (b₂ : Matrix (Fin n) (Fin n) K).submatrix id J).rank ≤ bruhatRank v k q := by
    refine (Matrix.rank_mul_le_left _ _).trans ((Matrix.rank_mul_le_right _ _).trans ?_)
    rw [Matrix.rank_diagonal, Fintype.card_subtype]
    simp [bruhatRank]
  have hvw := mem_lowerSet.mp hv k q
  omega

/-- **Fulton's rank conditions define `X_w` scheme-theoretically** (ring form): the ideal of
`π⁻¹ X_w` in `𝒪(GL_n)` is generated by Fulton's minors. -/
theorem orbitIdeal_lowerSet_eq_fultonIdeal [IsAlgClosed K] [CharZero K] (w : Equiv.Perm (Fin n)) :
    orbitIdeal K (lowerSet w) =
      (fultonIdeal K w).map (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n)) := by
  apply le_antisymm
  · rw [orbitIdeal_lowerSet_eq]
    exact Ideal.map_mono (schubertIdeal_le_fultonIdeal w)
  · rw [Ideal.map_le_iff_le_comap]
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨k, q, I, J, hI, hJ, rfl⟩
    exact algebraMap_mem_orbitIdeal fun g hg => evalAt_minorRC_eq_zero hI hJ hg

/-- Vanishing ideals are radical. -/
theorem isRadical_orbitIdeal (S : Finset (Equiv.Perm (Fin n))) : (orbitIdeal K S).IsRadical := by
  rintro t ⟨m, hm⟩ g hg
  have h := hm g hg
  rw [map_pow] at h
  exact eq_zero_of_pow_eq_zero h

/-- **Reducedness of Fulton's ideal** in `𝒪(GL_n)`. -/
theorem isRadical_map_fultonIdeal [IsAlgClosed K] [CharZero K] (w : Equiv.Perm (Fin n)) :
    ((fultonIdeal K w).map (algebraMap (MatrixEntryPolynomial K n) (GLCoord K n))).IsRadical := by
  rw [← orbitIdeal_lowerSet_eq_fultonIdeal]
  exact isRadical_orbitIdeal _

end

end FlagVarieties.PointModel
