import Schubert.FlagVarieties.Schubert.Preimage
import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion

/-!
# Minimal parabolic subgroups

For `i + 1 < n`, with simple reflection `sᵢ = (i, i+1)`:

* `FlagVarieties.parabolicBlock i`: the block function `k ↦ k` for `k ≠ i + 1`, `i + 1 ↦ i`; a
  matrix is block upper triangular for it iff its entries below the diagonal vanish, except possibly
  the entry `(i+1, i)`.
* **`FlagVarieties.ParabolicScheme R n i`**: the minimal parabolic subgroup scheme
  `Pᵢ = B ∪ B sᵢ B ⊆ GLₙ`, `Spec (𝒪(GLₙ) ⧸ parabolicIdeal R n i)`, with its closed immersion
  `parabolicInclusion` and its group structure (`parabolicCounit`, `parabolicComul`).
* `FlagVarieties.parabolicIdeal_le_schubertOrbitIdeal`: `B sᵢ B ⊆ Pᵢ`.
* `FlagVarieties.isCoprime_mk_parabolic`: on `Pᵢ` (indeed on every closed subscheme of `Pᵢ`), the
  two entries `xᵢᵢ` and `x_{i+1,i}` of the `i`-th column generate the unit ideal.
-/

noncomputable section

namespace FlagVarieties

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits
open scoped TensorProduct

universe u

variable (R : Type u) [CommRing R] (n : ℕ)

/-- The simple reflection `sᵢ = (i, i+1)`. -/
def simpleReflection (i : ℕ) (hi : i + 1 < n) : Equiv.Perm (Fin n) :=
  Equiv.swap ⟨i, by omega⟩ ⟨i + 1, hi⟩

/-- The block function of `Pᵢ`: `k ↦ k` for `k ≠ i + 1`, and `i + 1 ↦ i`. -/
def parabolicBlock (i : ℕ) (k : Fin n) : ℕ :=
  if k.val = i + 1 then i else k.val

variable {n} in
theorem parabolicBlock_monotone (i : ℕ) : Monotone (parabolicBlock n i) := by
  intro a b hab
  have hab' : a.val ≤ b.val := hab
  unfold parabolicBlock
  split_ifs <;> omega

variable {n} in
theorem parabolicBlock_lt_iff (i : ℕ) (r c : Fin n) :
    parabolicBlock n i c < parabolicBlock n i r ↔
      c.val < r.val ∧ ¬(r.val = i + 1 ∧ c.val = i) := by
  unfold parabolicBlock
  split_ifs <;> omega

variable {n} in
/-- Upper triangular matrices are block upper triangular for `parabolicBlock`. -/
theorem blockTriangular_parabolicBlock_of_upper {A : Type*} [CommRing A] (i : ℕ)
    {M : Matrix (Fin n) (Fin n) A} (hM : M.BlockTriangular id) :
    M.BlockTriangular (parabolicBlock n i) := fun _ _ h =>
  hM (lt_of_not_ge fun hrc => (h.trans_le (parabolicBlock_monotone i hrc)).false)

variable {n} in
/-- The permutation matrix of `sᵢ` lies in `Pᵢ`. -/
theorem blockTriangular_permMatrix_simpleReflection {A : Type*} [CommRing A] (i : ℕ)
    (hi : i + 1 < n) :
    (permMatrix (A := A) n (simpleReflection n i hi)).BlockTriangular (parabolicBlock n i) := by
  intro r c h
  rw [parabolicBlock_lt_iff] at h
  rw [permMatrix_apply]
  split_ifs with hrc
  · exfalso
    rw [simpleReflection, Equiv.swap_apply_def] at hrc
    split_ifs at hrc with h1 h2 <;> (subst hrc; simp_all [Fin.ext_iff])
  · rfl

/-! ### The ideal and the coordinate ring of `Pᵢ` -/

/-- The ideal of `Pᵢ ⊆ GLₙ`: generated by the entries of the generic matrix below the diagonal,
except `x_{i+1,i}`. -/
def parabolicIdeal (i : ℕ) : Ideal (GLCoord R n) :=
  Ideal.span (Set.range fun p : {p : Fin n × Fin n //
    parabolicBlock n i p.2 < parabolicBlock n i p.1} => genericMatrix R n p.1.1 p.1.2)

/-- The coordinate ring `𝒪(Pᵢ) = 𝒪(GLₙ) ⧸ parabolicIdeal`. -/
abbrev ParabolicCoord (i : ℕ) : Type u :=
  GLCoord R n ⧸ parabolicIdeal R n i

/-- The generic point of `Pᵢ`. -/
def parabolicMatrix (i : ℕ) : Matrix (Fin n) (Fin n) (ParabolicCoord R n i) :=
  (genericMatrix R n).map (Ideal.Quotient.mk (parabolicIdeal R n i))

theorem parabolicMatrix_blockTriangular (i : ℕ) :
    (parabolicMatrix R n i).BlockTriangular (parabolicBlock n i) := by
  intro r c h
  simp only [parabolicMatrix, Matrix.map_apply]
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span ⟨⟨(r, c), h⟩, rfl⟩

theorem isUnit_det_parabolicMatrix (i : ℕ) : IsUnit (parabolicMatrix R n i).det :=
  isUnit_det_map_ringHom _ (TauCeti.GeneralLinear.isUnit_det_localizedGenericMatrix R n)

variable {R n} in
/-- A point of `GLₙ` whose matrix lies in `Pᵢ` is a point of `Pᵢ`. -/
def parabolicPointOfMatrix {A : Type*} [CommRing A] [Algebra R A] (i : ℕ)
    (g : Matrix (Fin n) (Fin n) A) (hg : IsUnit g.det)
    (hb : g.BlockTriangular (parabolicBlock n i)) :
    ParabolicCoord R n i →ₐ[R] A :=
  Ideal.Quotient.liftₐ (parabolicIdeal R n i) (glPointOfMatrix R g hg) (by
    have hle : parabolicIdeal R n i ≤ RingHom.ker (glPointOfMatrix R g hg).toRingHom := by
      rw [parabolicIdeal, Ideal.span_le]
      rintro _ ⟨⟨⟨r, c⟩, hrc⟩, rfl⟩
      have h := congrFun (congrFun (genericMatrix_map_glPointOfMatrix R g hg) r) c
      simp only [Matrix.map_apply] at h
      simp only [SetLike.mem_coe, RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, h]
      exact hb hrc
    exact fun a ha => hle ha)

variable {R n} in
theorem parabolicMatrix_map_parabolicPointOfMatrix {A : Type*} [CommRing A] [Algebra R A]
    (i : ℕ) (g : Matrix (Fin n) (Fin n) A) (hg : IsUnit g.det)
    (hb : g.BlockTriangular (parabolicBlock n i)) :
    (parabolicMatrix R n i).map (parabolicPointOfMatrix i g hg hb) = g := by
  ext r c
  exact congrFun (congrFun (genericMatrix_map_glPointOfMatrix R g hg) r) c

variable {R n} in
/-- `R`-algebra maps out of `𝒪(Pᵢ)` are determined by the image of the generic point. -/
theorem parabolicMatrix_algHom_ext {A : Type*} [CommRing A] [Algebra R A] {i : ℕ}
    {k k' : ParabolicCoord R n i →ₐ[R] A}
    (h : (parabolicMatrix R n i).map k = (parabolicMatrix R n i).map k') : k = k' := by
  apply Ideal.Quotient.algHom_ext
  apply genericMatrix_algHom_ext
  exact h

/-! ### The group structure of `Pᵢ` -/

/-- The unit of `Pᵢ`: evaluation at the identity matrix. -/
def parabolicCounit (i : ℕ) : ParabolicCoord R n i →ₐ[R] R :=
  parabolicPointOfMatrix i (1 : Matrix (Fin n) (Fin n) R) (by simp) Matrix.blockTriangular_one

/-- The multiplication of `Pᵢ`: `𝒪(Pᵢ) → 𝒪(Pᵢ) ⊗ 𝒪(Pᵢ)`, `p ↦ p₁ p₂`. -/
def parabolicComul (i : ℕ) :
    ParabolicCoord R n i →ₐ[R] ParabolicCoord R n i ⊗[R] ParabolicCoord R n i :=
  parabolicPointOfMatrix i
    ((parabolicMatrix R n i).map
        (Algebra.TensorProduct.includeLeft : ParabolicCoord R n i →ₐ[R] _) *
      (parabolicMatrix R n i).map
        (Algebra.TensorProduct.includeRight : ParabolicCoord R n i →ₐ[R] _))
    (by
      rw [Matrix.det_mul]
      exact (isUnit_det_map_ringHom _ (isUnit_det_parabolicMatrix R n i)).mul
        (isUnit_det_map_ringHom _ (isUnit_det_parabolicMatrix R n i)))
    (by
      apply Matrix.BlockTriangular.mul
      · intro r c h
        simp [Matrix.map_apply, parabolicMatrix_blockTriangular R n i h]
      · intro r c h
        simp [Matrix.map_apply, parabolicMatrix_blockTriangular R n i h])

/-- `B ⊆ Pᵢ`: the restriction `𝒪(Pᵢ) → 𝒪(B)`. -/
def parabolicToBorel (i : ℕ) : ParabolicCoord R n i →ₐ[R] BorelCoord R n :=
  parabolicPointOfMatrix i (borelMatrix R n) (isUnit_det_borelMatrix R n)
    (blockTriangular_parabolicBlock_of_upper i (borelMatrix_blockTriangular R n))

/-! ### The scheme `Pᵢ` -/

/-- **The minimal parabolic subgroup scheme `Pᵢ = B ∪ B sᵢ B ⊆ GLₙ`**: the matrices that are block
upper triangular with diagonal blocks of sizes `1, …, 1, 2, 1, …, 1` (the block `2` in rows and
columns `i, i+1`), i.e. whose entries below the diagonal vanish except possibly the entry
`(i+1, i)`. -/
abbrev ParabolicScheme (i : ℕ) : Scheme.{u} :=
  Spec (CommRingCat.of (ParabolicCoord R n i))

/-- The closed immersion `Pᵢ ⟶ GLₙ`. -/
def parabolicInclusion (i : ℕ) : ParabolicScheme R n i ⟶ GLScheme R n :=
  Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk (parabolicIdeal R n i))) ≫
    (TauCeti.GeneralLinear.groupSchemeSpecIso R n).inv

instance (i : ℕ) : IsClosedImmersion (parabolicInclusion R n i) := by
  have : IsClosedImmersion
      (Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk (parabolicIdeal R n i)))) :=
    IsClosedImmersion.spec_of_surjective _ Ideal.Quotient.mk_surjective
  unfold parabolicInclusion
  infer_instance

/-! ### `B sᵢ B ⊆ Pᵢ` -/

theorem schubertOrbitMatrix_blockTriangular (i : ℕ) (hi : i + 1 < n) :
    (schubertOrbitMatrix R n (simpleReflection n i hi)).BlockTriangular (parabolicBlock n i) := by
  rw [schubertOrbitMatrix]
  refine Matrix.BlockTriangular.mul (Matrix.BlockTriangular.mul ?_
    (blockTriangular_permMatrix_simpleReflection i hi)) ?_
  · exact blockTriangular_parabolicBlock_of_upper i
      (blockTriangular_map_algHom (borelMatrix_blockTriangular R n) _)
  · exact blockTriangular_parabolicBlock_of_upper i
      (blockTriangular_map_algHom (borelMatrix_blockTriangular R n) _)

/-- **`B sᵢ B ⊆ Pᵢ`**: the ideal of `Pᵢ` vanishes on `B sᵢ B`. -/
theorem parabolicIdeal_le_schubertOrbitIdeal (i : ℕ) (hi : i + 1 < n) :
    parabolicIdeal R n i ≤ schubertOrbitIdeal R n (simpleReflection n i hi) := by
  rw [parabolicIdeal, Ideal.span_le]
  rintro _ ⟨⟨⟨r, c⟩, hrc⟩, rfl⟩
  rw [SetLike.mem_coe, schubertOrbitIdeal, RingHom.mem_ker]
  have h := congrFun (congrFun (genericMatrix_map_glPointOfMatrix R
    (schubertOrbitMatrix R n (simpleReflection n i hi))
    (isUnit_det_schubertOrbitMatrix R n _)) r) c
  rw [Matrix.map_apply] at h
  change schubertOrbitComorphism R n (simpleReflection n i hi) (genericMatrix R n r c) = 0
  rw [schubertOrbitComorphism, h]
  exact schubertOrbitMatrix_blockTriangular R n i hi hrc

/-! ### The `i`-th column on `Pᵢ` -/

/-- **On `Pᵢ`, the entries `xᵢᵢ` and `x_{i+1,i}` generate the unit ideal**: modulo both and the
ideal of `Pᵢ`, the generic matrix is upper triangular with a zero on the diagonal, so its
determinant vanishes. -/
theorem one_mem_parabolicIdeal_sup (i : ℕ) (hi : i + 1 < n) :
    (1 : GLCoord R n) ∈ parabolicIdeal R n i ⊔ Ideal.span
      {genericMatrix R n ⟨i, by omega⟩ ⟨i, by omega⟩,
        genericMatrix R n ⟨i + 1, hi⟩ ⟨i, by omega⟩} := by
  set K := parabolicIdeal R n i ⊔ Ideal.span
      {genericMatrix R n ⟨i, by omega⟩ ⟨i, by omega⟩,
        genericMatrix R n ⟨i + 1, hi⟩ ⟨i, by omega⟩}
  let M := (genericMatrix R n).map (Ideal.Quotient.mk K)
  have hM : M.BlockTriangular id := by
    intro r c hrc
    simp only [M, Matrix.map_apply]
    rw [Ideal.Quotient.eq_zero_iff_mem]
    by_cases h : r.val = i + 1 ∧ c.val = i
    · have hr : r = ⟨i + 1, hi⟩ := Fin.ext h.1
      have hc : c = ⟨i, by omega⟩ := Fin.ext h.2
      rw [hr, hc]
      exact Ideal.mem_sup_right (Ideal.subset_span (by simp))
    · exact Ideal.mem_sup_left (Ideal.subset_span
        ⟨⟨(r, c), (parabolicBlock_lt_iff i r c).mpr ⟨hrc, h⟩⟩, rfl⟩)
  have hdiag : M ⟨i, by omega⟩ ⟨i, by omega⟩ = 0 := by
    simp only [M, Matrix.map_apply]
    rw [Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.mem_sup_right (Ideal.subset_span (by simp))
  have hdet : M.det = 0 := by
    rw [Matrix.det_of_isUpperTriangular hM]
    exact Finset.prod_eq_zero (Finset.mem_univ _) hdiag
  have hunit : IsUnit M.det :=
    isUnit_det_map_ringHom _ (TauCeti.GeneralLinear.isUnit_det_localizedGenericMatrix R n)
  rw [hdet, isUnit_zero_iff] at hunit
  rw [← Ideal.Quotient.eq_zero_iff_mem, map_one]
  exact hunit.symm

/-- On any closed subscheme `Spec (𝒪(GLₙ) ⧸ J)` of `Pᵢ`, the entries `xᵢᵢ` and `x_{i+1,i}` are
coprime. -/
theorem isCoprime_mk_parabolic (i : ℕ) (hi : i + 1 < n) {J : Ideal (GLCoord R n)}
    (hJ : parabolicIdeal R n i ≤ J) :
    IsCoprime (Ideal.Quotient.mk J (genericMatrix R n ⟨i, by omega⟩ ⟨i, by omega⟩))
      (Ideal.Quotient.mk J (genericMatrix R n ⟨i + 1, hi⟩ ⟨i, by omega⟩)) := by
  obtain ⟨p, hp, q, hq, hpq⟩ := Submodule.mem_sup.mp (one_mem_parabolicIdeal_sup R n i hi)
  obtain ⟨a, b, rfl⟩ := Ideal.mem_span_pair.mp hq
  refine ⟨Ideal.Quotient.mk J a, Ideal.Quotient.mk J b, ?_⟩
  have h1 := congrArg (Ideal.Quotient.mk J) hpq
  rw [map_add, Ideal.Quotient.eq_zero_iff_mem.mpr (hJ hp), zero_add, map_add, map_mul,
    map_mul, map_one] at h1
  exact h1

end FlagVarieties
